### ISSUE TITLE
Use time range filter in a template query

### ISSUE THREAD

**Issue by MikhailKalashnikov** [Vertamedia/clickhouse-grafana#10]
Is it possible to use time range filter (i.e. $from, $to or $timeFilter) in template query?
In Grafana documentation I see "Set this only to On Time Range Change if your variable options query contains a time range filter or is dependent on dashboard time range."
But when I try to use time range filter ($from, $to or $timeFilter)  in template query it sends query to CH as is, without replacing $from, $to or $timeFilter

**Comment by hagen1778** [comment]
@MikhailKalashnikov, As I know this feature is not supported by Grafana
see - https://github.com/grafana/grafana/issues/1909

Anyway, I can't use $from, $to or $timeFilter at template variables while using other datasources. Correct me if I'm wrong

**Comment by MikhailKalashnikov** [comment]
Yes. You are right. 
It seems that it is not supported in Grafana
