### ISSUE TITLE
Can i add variable for control chart visibility?

### ISSUE THREAD

**Issue by sergeyykt** [Vertamedia/clickhouse-grafana#105]
For example, i have a number of values of query variable. And i want to generate similar charts with own variable values in one Graph Panel . Is that possible?

**Comment by hagen1778** [comment]
Hi @sergeyykt 
Probably you need something like [this](http://docs.grafana.org/reference/templating/#repeating-panels).

**Comment by hagen1778** [comment]
closed due to lack of activity
