### ISSUE TITLE
No yarn?

### ISSUE THREAD

**Issue by simPod** [Vertamedia/clickhouse-grafana#108]
Hi, just wanted to ask what is the reason for this?

https://github.com/Vertamedia/clickhouse-grafana/commit/75bb8b96c389e2ae67e6cc0944190bb679a471b2

This works with npm and yarn as well.

**Comment by hagen1778** [comment]
Hi! I thought it won't work with `yarn`. That was my mistake and poor js environment knowledge. Reverted in https://github.com/Vertamedia/clickhouse-grafana/commit/ba76cb1334775a1555100411ca55a0d2bac62604

**Comment by simPod** [comment]
Cool. They work pretty much the same. Only yarn fixed/added some essential functionality npm once missed. Since npm 5 it pretty much caught up so now they're almost equal. But yarn still has better caching and concurrent download that npm doesn't have AFAIK. Or didn't have in 2018, not sure about the current state.
