### ISSUE TITLE
Better Reporting of Failed Queries

### ISSUE THREAD

**Issue by PeterZaitsev** [Vertamedia/clickhouse-grafana#114]
I'm comparing ClickHouse to MySQL DataSource 

MySQL DataSource has a lot better query debugging functionality where the error text is delivered back to Grafana allowing to understand what is going wrong.  With ClickHouse I only see "Request Error" which is not very helpful for troubleshooting.

**Comment by negbie** [comment]
Seems to work fine in recent releases.
![cerr](https://user-images.githubusercontent.com/20154956/95654755-74105680-0b02-11eb-9cfb-d7b325b90d20.jpg)

**Comment by Slach** [comment]
It is the last release of Grafana 7.2.x?
Cause we did nothing on ClickHouse-Grafana 2.1.0

ok. I close ticket

**Comment by negbie** [comment]
Yes it's Grafana 7.2.0.
