### ISSUE TITLE
$from Documentation is Incorrect

### ISSUE THREAD

**Issue by PeterZaitsev** [Vertamedia/clickhouse-grafana#115]
"Help" Says the following:

$from - replaced with timestamp/1000 value of selected "Time Range:From"

While I see $from in my case as UnixTimestamp value of the start date with no division:

SELECT toDate(1393289997)

┌─toDate(1393289997)─┐
│         2014-02-25 │
└────────────────────┘

1 rows in set. Elapsed: 0.001 sec.

**Comment by Slach** [comment]
@PeterZaitsev there is not a bug, there is a misunderstanding between documentation and interpretation of term "timestamp"

timestamp in Grafana JavaScript it's a UnixTime + ms momentjs

please look at
https://github.com/Vertamedia/clickhouse-grafana/blob/master/src/sql_query.ts#L475 
https://github.com/Vertamedia/clickhouse-grafana/blob/master/src/datasource.ts#L138

dateMatch.parse convert string to `momentjs.com` DateTime format which contains microseconds "2013-02-08 24:00:00.000" 
so, I will change documentation for more clear
