### ISSUE TITLE
Inconvenient Transition Back to the Query Editor

### ISSUE THREAD

**Issue by PeterZaitsev** [Vertamedia/clickhouse-grafana#116]
When you open up ClickHouse Query Editor you see this

![image](https://user-images.githubusercontent.com/3651746/53308641-f3d7a780-3870-11e9-930d-c840947283d3.png)

You can click on the Go to Query To see something else

![image](https://user-images.githubusercontent.com/3651746/53308649-08b43b00-3871-11e9-8a8f-ec8c1f17a8c7.png)

However this screen does not have any links to go back to the previous settings. 

Suggestion: It would be better if link is added (as exists in MySQL Data Source for Example)

**Comment by olafbuitelaar** [comment]
For me, pressing the pencil button in the raw query view, brings me back to the query builder. Is this what you're after?
<img width="208" alt="Annotation 2020-02-21 132049" src="https://user-images.githubusercontent.com/12065895/75034294-35635880-54ad-11ea-9af7-ce8a5c4b8d48.png">

**Comment by negbie** [comment]
I think this can be closed as it works like @olafbuitelaar pointed out.

**Comment by Slach** [comment]
@negbie ok, let's close issue
