### ISSUE TITLE
One Day Rounding does not work as expected 

### ISSUE THREAD

**Issue by PeterZaitsev** [Vertamedia/clickhouse-grafana#117]
I'm plotting statistical data which is available with 1 day resolution.  As I configure my query I specify 1d for step and rounding.   The data on the graph however ends up not to be one day aligned and confusing:

![image](https://user-images.githubusercontent.com/3651746/53311022-18398100-387d-11e9-88d4-e235a577fd16.png)

![image](https://user-images.githubusercontent.com/3651746/53311051-3bfcc700-387d-11e9-989a-677b4ef464fc.png)

Note in the second graph we can see the interval is aligned to 20:00  (as it is on all days)  not to 20:00 as it is in the database.

Is there any way to avoid it ?

**Comment by albenik** [comment]
Same for me!
I investigated this problem a little bit and found that `$timeSeres` macro with `step 1d` produces SQL `(intDiv(toUInt32(ts), 86400) * 86400) * 1000 as t` which gets different result comparing with handmade SQL `toUInt32(dt) * 86400 * 1000 as t`

**Comment by kbespalov** [comment]
+1 the same issue

**Comment by Slach** [comment]
@PeterZaitsev, @albenik, @kbespalov 
Hi guys,
this rounding behavior related to grafana core data transformation for time series data, `grafana-clickhouse` data source plugin pass $timeSeries to grafana as UInt64 timestamp with ms and grafana graph panel transform it to "browser local datetime"

@PeterZaitsev I reproduce your query on https://github.com/Vertamedia/clickhouse-grafana/pull/219
and got a following results:
![image](https://user-images.githubusercontent.com/105560/86611592-4e862500-bfc8-11ea-9f93-0e89a2e9abd2.png)

![image](https://user-images.githubusercontent.com/105560/86611509-33b3b080-bfc8-11ea-9848-0b34f9f0339c.png)

![image](https://user-images.githubusercontent.com/105560/86611413-11219780-bfc8-11ea-99be-a5f563f36562.png)
