### ISSUE TITLE
ClickHouse-Grafana seems to be incompatible with Explore UI in Grafana 6.0 

### ISSUE THREAD

**Issue by PeterZaitsev** [Vertamedia/clickhouse-grafana#118]
Looks like there is some incompatibility.  The queries are not generated  -  see Generated SQL showing simply "true"

![image](https://user-images.githubusercontent.com/3651746/53345670-700ad300-38e3-11e9-9169-b3acd85a6ce4.png)

**Comment by Slach** [comment]
@PeterZaitsev I try to reproduce this behavior on latest master `docker-compose.yaml` with a changed image to `grafana:6.0.2` and failed

looks like the current master branch works fine with grafana 6.0 explore mode without apply
https://github.com/Vertamedia/clickhouse-grafana/pull/129

![image](https://user-images.githubusercontent.com/105560/84868749-9c2d0300-b096-11ea-9650-d3fe39987dfd.png)

I also tested lates `master` with grafana 6.7 and grafana 7.0
and explore also works fine
![image](https://user-images.githubusercontent.com/105560/84869324-50c72480-b097-11ea-8661-c18c5b718027.png)

**Comment by PeterZaitsev** [comment]
Thank you. Indeed this was fixed in one of the releases since I reported the issue
