### ISSUE TITLE
[Feature request] Округление даты в макросе $from для улучшения cache hit ratio

### ISSUE THREAD

**Issue by kshvakov** [Vertamedia/clickhouse-grafana#12]
плагин отправляет запросы вида
```sql 
SELECT t,
       groupArray((App,C/10))
FROM
  (SELECT (intDiv(toUInt32(EventTime), 3600) * 3600) * 1000 AS t,
          CASE
              WHEN ApplicationID = 12 THEN 'XXX'
              WHEN ApplicationID = 30 THEN 'XXX mobile'
              ELSE 'Other'
          END AS App,
          SUM(Impressions) AS C
   FROM metrics.metrics
   WHERE EventDate >= toDate(1500715771)
     AND EventTime >= toDateTime(1500715771)
   GROUP BY t,
            App
   ORDER BY t,
            App)
GROUP BY t
ORDER BY t FORMAT JSON
```

$from вставляется в toDate и toDateTime (toDate(1500715771), toDateTime(1500715771))

$from меняется каждые N секунд указаные в параметре рефреша 

проблема в том, что если открыто 10 окон то будет 10 разных $from т.к. открыты они были в разное время (допустим с шагом в 1 секунду)

хотелось бы таймстамп начала "сессии" затранкейтить чтоб уменьшить количество уникальных запросов и закешировать их на nginx

**Comment by hagen1778** [comment]
Привет @kshvakov 
В мастер-ветку была добавлена опция Round:
![round](https://user-images.githubusercontent.com/2902918/28582647-dbd795de-716e-11e7-8bc2-c70966415615.png)
Дефолтное значение - 0s. Округление происходит всегда в меньшую сторону

**Comment by kshvakov** [comment]
Спасибо

**Comment by kshvakov** [comment]
Обновились, выставил round в 1m на $from и $timeFiler это никак не повлияло, как шли по секунде так и идут (1500881708, 1500881709 ...) используем Grafana v4.1.1

**Comment by hagen1778** [comment]
Да, моя ошибка - забыл обновить скомпиленые js файлы

**Comment by iShift** [comment]
Есть подозрение, что округляется только from поле, а $to - нет, если так - очень грустно и хотелось бы $to

**Comment by hagen1778** [comment]
$to действительно не округляется, так как в этом нет потребности:
```
   WHERE EventDate >= toDate(1500715771)
     AND EventTime >= toDateTime(1500715771)
```
здесь используется только $from
Плагин строит такое условие, если $to == 'now', а это верно для всех случаев `lastN`. Исключением может быть использование `time shift` опции в панели, тогда Grafana генерирует четкие таймстампы для $from и $to

**Comment by iShift** [comment]
Но поле now тоже же меняется, а хотелось бы:
1) Округлять Now до нескольких минут 
2) При выборке назад тоже производить округление обоих вариантов

Нет ли планов\желания реализовать подобное?

**Comment by hagen1778** [comment]
Это очень легко сделать и не сделано это было только потому, что в этом не было надобности - как я упоминал выше, $to не используется в запросах `lastN`. Опишите, пожалуйста, Ваш кейс подробнее, чтобы я удостоверился, что мы говорим об одном и том же.

**Comment by iShift** [comment]
Кейс у меня следующий:
Льётся очень много статистики в узкую таблицу в Clickhouse, есть набор дашбордов на которых показывается верхнеуровневая проблема и генерация одного графика занимает около минуты.

Следовательно я прогреваю кэш дашбордов через переодический опрос ch-proxy по целевым запросам (они же забиты в графану). Графики - часовы, показ на графике - неделя\месяц - это я храню в кэше и быстро рисую.

Но когда нужно отобразить конкретную проблему - идет приближение графика с сужением выборки по времени - ch на лету достаточно быстро отрисовывает график.

И остается третий кейс - когда 10 человек мониторят проблему по последним данным которые кэшируются очень редко или не кэшируются (грубо говоря - 2 человека и у каждого дата окончания выборки - now и авторефреш) - такие запросы я не могу кэшировать, а очень бы хотелось. 

Как решение этой проблемы я вижу обрезку даты now до минуты(или нескольких) или часа

**Comment by hagen1778** [comment]
Добавил округление $to в https://github.com/Vertamedia/clickhouse-grafana/releases/tag/1.2.6
Но все равно странно, что у Вас используется $from в запросах "дата окончания выборки - now"

**Comment by iShift** [comment]
Сразу уточню - для конструкции $timeFilter работать будет же? там from работает

**Comment by hagen1778** [comment]
Да, $timefilter раскладывается в:
```
$dateCol BETWEEN toDate($from) AND toDate($to) AND $dateTimeCol BETWEEN $from AND $to
```
Или в случае с `from N to now` в:
```
'$dateCol >= toDate($from) AND $dateTimeCol >=$from
```

**Comment by iShift** [comment]
Спасибо огромное! Ушел тестировать.
