### ISSUE TITLE
Table and World map visualization regression between 1.8.0 and 1.8.1

### ISSUE THREAD

**Issue by champtar** [Vertamedia/clickhouse-grafana#124]
Hi,

grafana_version: "6.1.4-1"
grafana_plugin_clickhouse_version: "1.8.0"
grafana_plugin_worldmap_version: "0.2.0"
Everything is ok
![Capture d’écran du 2019-04-22 19-56-02](https://user-images.githubusercontent.com/3536755/56538373-39df7d80-6539-11e9-85f6-9553afab3bf1.png)

grafana_version: "6.1.4-1"
grafana_plugin_clickhouse_version: "1.8.1"
grafana_plugin_worldmap_version: "0.2.0"
The maximum circle size doesn't work anymore
![Capture d’écran du 2019-04-22 19-58-57](https://user-images.githubusercontent.com/3536755/56538420-5f6c8700-6539-11e9-8629-633748f1bbb0.png)

Looking at the commits, I would guess this commit https://github.com/Vertamedia/clickhouse-grafana/commit/731768f12c3c2b4c0128b800d5ef57757e565f5b is the culprit by I haven't tested

Thanks for this great plugin

**Comment by champtar** [comment]
1.8.1 also break table visualisation
1.8.0:
![image](https://user-images.githubusercontent.com/3536755/56542891-369ebe80-6546-11e9-994e-7ac43da4be51.png)
1.8.1:
![image](https://user-images.githubusercontent.com/3536755/56543212-2c30f480-6547-11e9-83e7-62f632e64558.png)

Also when using 1.8.1 the table visualisation sorting sort the numbers as strings
![image](https://user-images.githubusercontent.com/3536755/56543335-8fbb2200-6547-11e9-9954-272adac052ac.png)

**Comment by hodgesrm** [comment]
Thanks for the report @champtar.  We are working on setting up tests for the plugin and will be correcting bugs as soon as we can get them running.  

If you see additional problems please do not hesitate to log them.

**Comment by hagen1778** [comment]
I guess this is related #97

**Comment by ishirav** [comment]
+1
I also encountered the problem of tables sorting numeric columns as strings

**Comment by champtar** [comment]
Looking at query inspector:
```
  "response": {
    "meta": [
      {
        "name": "user_agent",
        "type": "LowCardinality(String)"
      },
      {
        "name": "nbreq",
        "type": "UInt64"
      },
      {
        "name": "bitrate",
        "type": "Float64"
      },
      {
        "name": "uniqueip",
        "type": "UInt64"
      }
    ],
    "data": [
      {
        "user_agent": "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
        "nbreq": "6199945",
        "bitrate": 324.73602604443874,
        "uniqueip": "2929"
      },
....
    ],
    "rows": 10,
    "rows_before_limit_at_least": 217,
    "statistics": {
      "elapsed": 6.328078072,
      "rows_read": 192561455,
      "bytes_read": 6153374830
    }
  }
```
Int* comes in as string in "data"

**Comment by champtar** [comment]
Just found an ugly workaround, just wrap all your numbers into toFloat64() in your ClickHouse query
```
    "meta": [
      {
        "name": "user_agent",
        "type": "LowCardinality(String)"
      },
      {
        "name": "nbreq",
        "type": "Float64"
      },
      {
        "name": "uniqueip",
        "type": "Float64"
      },
      {
        "name": "bitrate",
        "type": "Float64"
      }
    ],
    "data": [
      {
        "user_agent": "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
        "nbreq": 6199945,
        "uniqueip": 2929,
        "bitrate": 324.73602604443954
      }
...
```

**Comment by champtar** [comment]
ClickHouse quote UInt64 and Int64 by default because most javascript implementations uses IEEE 754, so max safe integer value is 2^53-1
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/MAX_SAFE_INTEGER
We can configure ClickHouse to not quote the 64 bit integers:
https://clickhouse.tech/docs/en/operations/settings/settings/#session_settings-output_format_json_quote_64bit_integers

**Comment by champtar** [comment]
@gimm3fuel (you seem to be merging everything) is it just a doc issue for you or do you want to to add this param in every queries ?

**Comment by Slach** [comment]
Hello @champtar, sorry for the late response, I promise we will get more quickly and qualified feedback in issues for our plugin users

could you check your issue with latest 2.0.2 or 2.0.1 plugin version? 

Look like latest grafana with latest plugin version show table "short" format and WorldMap correctly
![table short](https://user-images.githubusercontent.com/105560/86764755-b89ed880-c061-11ea-9ec1-0065f6cb171d.png)
![worldmap](https://user-images.githubusercontent.com/105560/86764872-dd934b80-c061-11ea-8116-924e12ea7452.png)
