### ISSUE TITLE
Graph message: "No data points" with subquery

### ISSUE THREAD

**Issue by dmitrysdm** [Vertamedia/clickhouse-grafana#127]
grafana v6.1.6 clickhouse-datasource 1.8.1
Working Query: as result i see graph

```
SELECT
    $timeSeries as t,
    count() as c
FROM $table
WHERE $timeFilter
GROUP BY t
ORDER BY t
```
result in query inspector:

```
{
  "xhrStatus": "complete",
  "request": {
    "method": "GET",
    "url": "api/datasources/proxy/8/?query=SELECT%20%20%20%20%20(intDiv(toUInt32(EventTime)%2C%201)%20*%201)%20*%201000%20as%20t%2C%20%20%20%20%20count()%20as%20c%20FROM%20em.users%20WHERE%20EventDate%20%3E%3D%20toDate(1558019528)%20AND%20EventTime%20%3E%3D%20toDateTime(1558019528)%20GROUP%20BY%20t%20ORDER%20BY%20t%20FORMAT%20JSON"
  },
  "response": {
    "meta": [
      {
        "name": "t",
        "type": "UInt64"
      },
      {
        "name": "c",
        "type": "UInt64"
      }
    ],
    "data": [
      {
        "t": "1558019633000",
        "c": "91"
      },
      {
        "t": "1558019634000",
        "c": "216"
      }
    ],
    "rows": 2,
    "statistics": {
      "elapsed": 0.003194378,
      "rows_read": 9777,
      "bytes_read": 58662
    }
  }
}
```
But if i try to do subquery:

```
SELECT * FROM (
  SELECT
      $timeSeries as t,
      count() as c
  FROM $table
  WHERE $timeFilter
  GROUP BY t
  ORDER BY t
)
GROUP BY c, t
```

i see same result in query inspector as previously:
```
{
  "xhrStatus": "complete",
  "request": {
    "method": "GET",
    "url": "api/datasources/proxy/8/?query=SELECT%20*%20FROM%20(%20SELECT%20%20%20%20%20(intDiv(toUInt32(EventTime)%2C%201)%20*%201)%20*%201000%20as%20t%2C%20%20%20%20%20count()%20as%20c%20FROM%20em.users%20WHERE%20EventDate%20%3E%3D%20toDate(1558019589)%20AND%20EventTime%20%3E%3D%20toDateTime(1558019589)%20GROUP%20BY%20t%20ORDER%20BY%20t%20)%20GROUP%20BY%20c%2C%20t%20FORMAT%20JSON"
  },
  "response": {
    "meta": [
      {
        "name": "t",
        "type": "UInt64"
      },
      {
        "name": "c",
        "type": "UInt64"
      }
    ],
    "data": [
      {
        "t": "1558019634000",
        "c": "216"
      },
      {
        "t": "1558019633000",
        "c": "91"
      }
    ],
    "rows": 2,
    "statistics": {
      "elapsed": 0.003641224,
      "rows_read": 9777,
      "bytes_read": 58662
    }
  }
}
```

but instead graph, i see message: 
"No data points"
without any messages about errors.

**Comment by dmitrysdm** [comment]
With grafana-6.2.0-beta2 i have the same result :(

**Comment by juris** [comment]
Same here with 6.7.1.

Moreover, it shows "No data" if I specify fixed time range. Presets like "Last X days" work fine. Defined ranges, like "From now-30 to now-1" produce "No data".

**Comment by juris** [comment]
> Same here with 6.7.1.
> 
> Moreover, it shows "No data" if I specify fixed time range. Presets like "Last X days" work fine. Defined ranges, like "From now-30 to now-1" produce "No data".

Figured out why I'm seeing it. We have a DateTime column named "t". So I was able to overcome my issue by changing :
```
SELECT
    $timeSeries as t
```
to
```
SELECT
    $timeSeries as time
```

**Comment by Slach** [comment]
@dmitrysdm 
if you change your query
from
```sql
SELECT * FROM (
  SELECT
      $timeSeries as t,
      count() as c
  FROM $table
  WHERE $timeFilter
  GROUP BY t
  ORDER BY t
)
GROUP BY c, t
```

to
```sql
SELECT * FROM (
  SELECT
      $timeSeries as t,
      count() as total
  FROM $table
  WHERE $timeFilter
  GROUP BY t
)
ORDER BY t
```
I will see results

"no data" which you see related to behavior how to `clickhouse-grafana` plugin detect which columns should be represented as "groups" or "labels" and which columns should be represented as "value"
please look to:
- https://github.com/Vertamedia/clickhouse-grafana/blob/2.0.2/src/datasource.ts#L109
- https://github.com/Vertamedia/clickhouse-grafana/blob/2.0.2/src/datasource.ts#L164

when SQL query contains `GROUP BY` 
all columns used in `GROUP BY` should be combined to "label values" or name of time series depends on how much columns not used  in `GROUP BY`

so, when you use `GROUP BY c, t` you automatically exclude "c" from list of columns which should represent as "value"
