### ISSUE TITLE
[Bug] Incorrent works with multiple vars

### ISSUE THREAD

**Issue by iShift** [Vertamedia/clickhouse-grafana#13]
$KPI = some_kpi_name
$d_kpi = _d
$n_kpi = _n

This example works ok:
`SELECT $timeSeries as t, ($KPI$d_kpi/$KPI$n_kpi)*100 FROM $table WHERE $timeFilter and ucell_oid = $ucell_oid  ORDER BY t`

this is not:
```
$rateColumns(
    net_oid AS nets, 
     (SUM($KPI$n_kpi)/SUM($KPI$d_kpi))*100 c)
FROM $table  
ALL  INNER JOIN obj_ucell USING ucell_oid
```

After transform i get space between $KPI and $d_kpi

**Comment by hagen1778** [comment]
Hi @iShift! Thank you for feedback!
Current parser implentation treats every token as separate statement and divides them with spaces. Until now there was no need in such using of templates as you described above. I have to think about this a bit more time.

**Comment by hagen1778** [comment]
Hi! It must be ok now. Check latter master changes
