### ISSUE TITLE
AST parse error when query contains remote

### ISSUE THREAD

**Issue by minaevmike** [Vertamedia/clickhouse-grafana#130]
I have simple query on single stat panel
```
SELECT
    toFloat64(sum(bid))
FROM remote('$clickhouse_host', events)
WHERE  and action_type = 'view' AND date >= toStartOfMonth(now())
```
In browser console i see error
```
sql_query.ts:86 AST parser error:  TypeError: this.tree[this.rootToken].push is not a function
    at Scanner.push (scanner.ts:79)
    at Scanner.toAST (scanner.ts:118)
    at SqlQuery.replace (sql_query.ts:43)
    at ClickHouseDatasource.createQuery (datasource.ts:135)
    at eval (datasource.ts:85)
    at Qt (lodash.js:639)
    at Function.Ja [as map] (lodash.js:9555)
    at d (lodash.js:16993)
    at Ba (lodash.js:8797)
    at lodash.js:4374
```
With debugger i found that problem is located in `remote` function after i delete it and add `GROUP BY 1` this issue fixed.
Also it's not obvious that i need `GROUP BY` statement for single stat panel

**Comment by hagen1778** [comment]
Hi @minaevmike 

Most likely function `remote` is not supported in plugin - see [this link](https://github.com/Vertamedia/clickhouse-grafana/blob/92cc05d3db0c550ed36f5d01bd60deb5566d5fd2/src/clickhouse-info.js) for full list.

**Comment by v-zhuravlev** [comment]
Had the same error while trying to use `groupArrayMovingAvg`. It is also not the list.

**Comment by hagen1778** [comment]
Same error happens for following query:
```
select
  name,
  sum(data_compressed_bytes) as bytes,
  sum(data_uncompressed_bytes) as uncompressed_bytes,
  round(sum(data_uncompressed_bytes) / sum(data_compressed_bytes), 3) AS compressionRatio
from cluster('foo', 'system.columns')
where database = 'bar' and table = 'baz'
group by name
order by bytes desc
```

**Comment by Slach** [comment]
@hagen1778, @minaevmike 
look like
the latest `master` version works fine with remote() and cluster() functions and template variables inside them
I use the following SQL query for `remote_host` variable:
```sql
SELECT DISTINCT concat(host_name, ':', toString(port)) AS remote_host FROM system.clusters |   |   |   |  
```
![image](https://user-images.githubusercontent.com/105560/86428365-f5876a00-bd05-11ea-8ebc-278f62a01463.png)

and following for `cluster_name` 
```sql
SELECT DISTINCT cluster FROM system.clusters
```
![image](https://user-images.githubusercontent.com/105560/86428774-05537e00-bd07-11ea-9e47-538c9364318f.png)

I will add these examples to clickhouse_dashboard.json

**Comment by Slach** [comment]
@hagen1778 and @minaevmike could you check the latest `master` branch?

**Comment by hagen1778** [comment]
Thanks for doing this!
