### ISSUE TITLE
Empty time series view

### ISSUE THREAD

**Issue by dnspress** [Vertamedia/clickhouse-grafana#131]
When I run a query it works properly.
![image](https://user-images.githubusercontent.com/40758698/59116069-543bb200-8953-11e9-95a3-bab56c2bc681.png)

Data inspector shows received data from server
![image](https://user-images.githubusercontent.com/40758698/59115902-f0b18480-8952-11e9-8932-014d05b80ca3.png)
but view is empty:
![image](https://user-images.githubusercontent.com/40758698/59115871-db3c5a80-8952-11e9-850f-d1cfee855264.png)

is it problem with grafana UI or plugin's engine?

Versions:
grafana-server -v
Version 6.1.4 (commit: fef1733, branch: HEAD)

**Comment by hagen1778** [comment]
Hi @dnspress 
I assume the problem with timestamps - try to divide them by 1000. 
Have you checked default query generated by plugin:
```
SELECT $timeSeries as t, count() 
FROM $table
 WHERE $timeFilter 
GROUP BY t 
ORDER BY t
```

**Comment by dnspress** [comment]
@hagen1778 thanks for the clue!
The problem was with timestamps. I used toStartOfDay(<datetime field>) and it is return a string but grafana waits a long. So toRelativeSecondNum(toStartOfDay(ts))*1000 as "time" fixed the problem.
