### ISSUE TITLE
Feature in macro, with fill slots

### ISSUE THREAD

**Issue by ctaity** [Vertamedia/clickhouse-grafana#134]
Is there a way to somehow fill the whole given interval? Like InfluxDB has fill argument for group or TimescaleDb's time_bucket() function with generate_series() I tried to search ClickHouse documentation and github issues and it seems this is not implemented yet so the question perhaps is whether there's any workaround.

In click house this feature can be implemented with a union. Here an example:
```
SELECT SUM(metric),
       time
  FROM (
        SELECT toStartOfQuarter(toDate(1514761200+number*30*24*3600))  time,
               toUInt16(0) AS metric
          FROM numbers(30)

     UNION ALL 

          SELECT toStartOfQuarter(created_at) AS time,
               metric
          FROM mytable
         WHERE created_at >= toDate(1514761200)
           AND created_at >= toDateTime(1514761200)
           AND created_at <= toDate(1546210800)
           AND created_at <= toDateTime(1546210800)
       )
 GROUP BY time
 ORDER BY time
```
maybe is use full have a checbox, or modify the query template to have this feature. 
Thanks

**Comment by Slach** [comment]
on latest ClickHouse testing version
we have `ORDER BY time WITH FILL`
please look to https://github.com/ClickHouse/ClickHouse/pull/12410

**Comment by Slach** [comment]
Dear @ctaity 
I think implements WITH FILL analog for $macros inside clickhouse-grafana is too complicated and out of scope for data source plugin 

Current macros architecture just stateless convert $macros to SQL queries and pass it to Clickhouse server 

Feel free reopen this issue or create pull request if you disagree

Feel free make Pull Request or repoen issue if you
