### ISSUE TITLE
$__from and $__to changing the rawQuery value in the dashboard and triggering save prompt.

### ISSUE THREAD

**Issue by dan-hughes** [Vertamedia/clickhouse-grafana#135]
I have the Grafana $__from and $__to built-in variables used in a dashboard panel. 
When these change in the dashboard the rawQuery value in the dashboard JSON model changes which is triggering a save changes prompt.

Culprit looks to be [here](https://github.com/Vertamedia/clickhouse-grafana/blob/bec8b079030756c88354dfeb79150c009ea38492/src/sql_query.ts#L100).

Looking at the Grafana datasource plugins these mostly still include any dashboard variables and not the expanded variable values.

I'll look at giving it a go myself but I need to understand how the query or rawQuery is executed.

**Comment by hagen1778** [comment]
Hi @dan-hughes !

Thank you for the question!

`Query` is the query you write in the Grafana query field. `RawQuery` is a final query which should be executed by ClickHouse after all replacements and modifications. For example, if `query` contains `$timeFilter` macros then `rawQuery` will be populated with current time filters. That means `rawQuery` is almost always changing with every execution. However, I've never seen issue you mentioned. Are you sure that nothing else were changed?

**Comment by dan-hughes** [comment]
Hi @hagen1778, 

I do use the $__from and $__to Grafana time variables if this makes any difference but I have tried the clickhouse-grafana $from and $to variables too. 
I have opened a dashboard last saved another day and saved the dashboard when prompted and not changed anything else. I have then compared the JSON models for the dashboard from the two saves and the only difference is the variables in the query being updated/expanded. I do use the 'Yesterday/day before yesterday' timeranges, therefore, the time is expected to change each day the dashboard is viewed.

I have looked at another datasource to see what rawQuery is used for. In the InfluxDB datasource for example (which I also use) the rawQuery field is used to determine if the Grafana query editor is in builder mode or raw SQL mode. 
It does not look like they expand any variables out and write them into the dashboard JSON model which then does not trigger a save prompt.

**Comment by Slach** [comment]
@dan-hughes 
could you share your dashboard JSON or maybe make screencast which captures triggering "save prompt"?

I tried to reproduce use $__from, $__to inside SQL query
"save prompt" doesn't trigger when I change time range in grafana UI

![image](http://g.recordit.co/THBTq4Gv8E.gif)
