### ISSUE TITLE
failed to connect to my clickhouse server

### ISSUE THREAD

**Issue by tlightsky** [Vertamedia/clickhouse-grafana#136]
use [docker-clickhouse-grafana](https://github.com/lmangani/docker-clickhouse-grafana) to setup the env
and add my datasource to it,
it can connect to the server inside in same `docker-compose.yml` file,
but can't connect to my real server
the hint is:
```
lvl=eror msg="Basic auth failed" logger=context error="User not found"
```

**Comment by hagen1778** [comment]
Hi @tlightsky 
Looks like your real server is behind some authentification system (likely basic auth) and datasource should be configured accordingly. So this is more question of configuring datasource in Grafana than datasource issue.
Keep in mind, that Grafana supports two ways of access to datasource: server and proxy. Server means that request to datasource will be send from Grafana backend, from instance where Grafana installed. Proxy means all requests will go through your browser. So if you able to query ClickHouse via your browser, Grafana can do that to.

**Comment by tlightsky** [comment]
thanks for reply, 
maybe it's about the docker,
i'll try to run it in host and see can i get it work

**Comment by tlightsky** [comment]
deployed without docker, seems ok now, not sure why it doesn't inside docker
