### ISSUE TITLE
Use variables for column names when column names are complex

### ISSUE THREAD

**Issue by aayush210** [Vertamedia/clickhouse-grafana#139]
Hello,
I am facing an issue trying to use a token variable as column name in the query like done in #37 ...
 But it doesn't work even when using the new $unescape macro.. Turns out that my column names have space and hyphens and so back-quoting is needed.

It seems that the the fix #120 does not account for this particular case when column names contain space etc. Can we have a macro similar to $unescape which puts back-quotes if column names are complex.?

**Comment by Slach** [comment]
Hello @aayush210, sorry for the late response, I promise we will give more quickly and qualified feedback to users of our plugin

 could you share SQL table schema and SQL query example to reproduce your issue?

**Comment by Slach** [comment]
I close issue cause feedback is missed

@aayush210 feel free to reopen the issue if this still actual for you
