### ISSUE TITLE
Problem with symbols encoding

### ISSUE THREAD

**Issue by Foxsa** [Vertamedia/clickhouse-grafana#14]
Im trying to make a simple query:
```
SELECT
    $timeSeries as t,
    avg(response_time)
FROM logs.nginx
GROUP BY t
WHERE $timeFilter
```
This transformed into:

```SELECT     (intDiv(toUInt32(time_iso), 5) * 5) * 1000 as t,     avg(response_time) FROM logs.nginx GROUP BY t WHERE log_date >= toDate(1501751601) AND time_iso >= toDateTime(1501751601)```

And I got an error:

```Code: 62, e.displayText() = DB::Exception: Syntax error: failed at position 120: WHERE log_date &gt;= toDate(1501751601) AND time_iso &gt;= toDateTime(1501751601) FORMAT JSON, expected end of query, e.what() = DB::Exception&#10;```

In tabix.io this query is OK

**Comment by hagen1778** [comment]
Hi @Foxsa 
Could you provide me with your browser type and version and datasource version?

**Comment by Foxsa** [comment]
Browser Google Chromium 
Version 59.0.3071.109 (Developer Build) Built on Ubuntu , running on Ubuntu 16.04 (64-bit)

datasource version 0.0.2 from Grafana store

**Comment by hagen1778** [comment]
At first i thought that problem is in `&gt;` characters. But it's just GitHub format. There is an error in the request. You can't do `GROUP BY` before `WHERE` statement in that request. See documentation http://clickhouse.readthedocs.io/en/latest/reference_ru.html#SELECT

So all you need - just swap `WHERE` and `GROUP BY` like next:
```
SELECT
    $timeSeries as t,
    avg(response_time)
FROM logs.nginx
WHERE $timeFilter
GROUP BY t
```
I hope it helps

**Comment by hagen1778** [comment]
> In tabix.io this query is OK
I am wondering - how? :-)

**Comment by Foxsa** [comment]
Ok, now it works, i.e. without errors.
My mistake, fixed it copying to tabix

But now grafana not drawing plot, only strange horisontal lines
![screenshot_grafana1](https://user-images.githubusercontent.com/4919407/28921608-4cbf7f36-785f-11e7-8353-1e63e014ec93.png)

**Comment by hagen1778** [comment]
It's because you fetched data without ordering by time. Now you need to add:
```
SELECT
    $timeSeries as t,
    avg(response_time)
FROM logs.nginx
WHERE $timeFilter
GROUP BY t
ORDER BY t
```

Take a look at documentation https://github.com/Vertamedia/clickhouse-grafana#raw-sql-editor

**Comment by Foxsa** [comment]
Oh, thank you again! Sorry for dumb questions

**Comment by hagen1778** [comment]
You are welcome! Plz, close the issue if problem solved
