### ISSUE TITLE
clickhouse plugin does not work with grafana 6.4 Beta 1

### ISSUE THREAD

**Issue by TH-HA** [Vertamedia/clickhouse-grafana#143]
Hello 
I'm not understand exactly why but the plugin is no more compatible with grafana starting at version 6.4.0 Beta 1. It seems to be an issue with the editor ( a lot of change apparently occur around ace and brace ) - may be web optimization such async import. 
The error message is 
Error: ace is not defined Evaluating http://<HOSTNAME>:3000/public/plugins/vertamedia-clickhouse-datasource/module.js Loading plugins/vertamedia-clickhouse-datasource/module

**Comment by alex-zaitsev** [comment]
@gimm3fuel ^

**Comment by levonet** [comment]
clickhouse plugin does not work with grafana 6.4.0 release now

**Comment by Slach** [comment]
same issue

using plugin with latest grafana in docker-compose
https://github.com/Slach/grafana-flamegraph-panel/blob/master/demo/docker-compose.yml

i see error
```
ClickHouse plugin failed
Error: ace is not defined Evaluating http://172.16.2.77:3000/public/plugins/vertamedia-clickhouse-datasource/module.js Loading plugins/vertamedia-clickhouse-datasource/module
```

**Comment by POPSuL** [comment]
Probably broken by https://github.com/grafana/grafana/pull/18544

**Comment by Nex-Otaku** [comment]
Same.

**Comment by volkovartem77** [comment]
The same issue. Grafana 6.4.1

**Comment by alex-zaitsev** [comment]
Thank you for reports, we will address it next week and make a patch release.

**Comment by nbonavia** [comment]
I've seen the same issue on Grafana 6.4.2 - reverted back to grafana 6.3.6 to make it work, but quite keen on using the latest Grafana.

**Comment by ekbfh** [comment]
Thank you for the fix.
Do you plan include this in next release?

**Comment by gondaz** [comment]
Hi! Thanks for the new release that fixed this issue. When will you add this (1.9.2) release to the Grafana plugin store? As of now, it still downloads the previous 1.9.0 version while Docker container building with `GF_INSTALL_PLUGINS` variable.

**Comment by amonakhov** [comment]
> Hi! Thanks for the new release that fixed this issue. When will you add this (1.9.2) release to the Grafana plugin store? As of now, it still downloads the previous 1.9.0 version while Docker container building with a `GF_INSTALL_PLUGINS` variable.

There is a pull request for Grafana already. I might be available in a few days.

**Comment by filipehdbr** [comment]
I am still having the same issue with Grafana 6.4.4 + Clickhouse 1.9.3. Any clue?
