### ISSUE TITLE
Please support Timestamp column additional to DateTime

### ISSUE THREAD

**Issue by bzed** [Vertamedia/clickhouse-grafana#15]
carbon-clickhouse uses a Timestamp column, not DateTime. It would be nice if we could use that in the query editor.

thanks,

bernd

**Comment by valyala** [comment]
@hagen1778 , what do you think about this?

**Comment by hagen1778** [comment]
Nice idea! Seems like it's pretty easy to implement. I'll take a look on it next weekend

**Comment by hagen1778** [comment]
Hi @bzed ! Plz, check #18 for Timestamp column support

**Comment by hagen1778** [comment]
Hi, check https://github.com/Vertamedia/clickhouse-grafana/releases/tag/1.1.0
