### ISSUE TITLE
"Ad Hoc Filters fix" breaks complex filters in version 1.9.2

### ISSUE THREAD

**Issue by Kenterfie** [Vertamedia/clickhouse-grafana#151]
Complex filters are impossible with the latest change to sql_query.ts:74

We often use the IN operator which unfortunately become impossible with the change, but its a common operator in clickhouse queries.

Expected Filter Clause
ipv4DstString IN ('172.0.0.1', '172.0.0.2', '172.0.0.3')
Current Filter Clause with 1.9.2
ipv4DstString IN '('172.0.0.1', '172.0.0.2', '172.0.0.3')'

I can't find anything about the reason why the "fix" was required. Possible a more general fix would be great to match both requirements.

**Comment by alex-zaitsev** [comment]
@Kenterfie , should be fixed in 1.9.3 by https://github.com/Vertamedia/clickhouse-grafana/pull/153/commits/4b1d3bffd48a8bfff1c610b603a23adb7bad81f4

Could you confirm, please?

**Comment by Kenterfie** [comment]
Thanks for the quick fix.

**Comment by Kenterfie** [comment]
Ok, change has broken more. I have reverted the change entirely.

On integer values also the new quoting produce errors.

dstPort < '1024'
->
Code: 43, e.displayText() = DB::Exception: Illegal types of arguments (UInt16, String) of function less, e.what() = DB::Exception

**Comment by alex-zaitsev** [comment]
@Kenterfie , this is technically correct. '1024' is a string and ClickHouse is strictly typed. How do you suggest it can be fixed for generic case?

**Comment by Slach** [comment]
@Kenterfie is this error still relevant for you?
