### ISSUE TITLE
Feature: Data Source Permissions

### ISSUE THREAD

**Issue by wisefool769** [Vertamedia/clickhouse-grafana#154]
Can we add a permissions tab to the clickhouse data source settings page, as seen here: 
https://grafana.com/docs/permissions/datasource_permissions/

This will enable restriction of data source access based on User / Team membership. 
We need this because we want multiple teams to use one instance of Grafana, without being able to see each others' data.

**Comment by Slach** [comment]
sorry but Data source permissions it's a Grafana Enterprise only feature, so I don't know how we can implement it, cause Enterprise Grafana core source part is not public, also permissions are out of scope for data source plugin

as a workaround, you can try to do the following things:
- create separate ClickHouse users and profiles with separate row policy for each  Team on clickhouse server
https://clickhouse.tech/docs/en/sql-reference/statements/create/#create-row-policy-statement 
- create separate Clickhouse data source for each team, and generate all your dashboards with change data source use templating  mechanism like https://github.com/grafana/grafonnet-lib
