### ISSUE TITLE
Cannot show multiple series when using subquery

### ISSUE THREAD

**Issue by variantf** [Vertamedia/clickhouse-grafana#156]
I got some wired result and don't know if it's a grafana's bug or this plugin's bug. Please help me, Thank you in advance.

My query is like this:
```
select
    $timeSeries t,
    extract(InstrumentID, '[a-zA-Z]+') ProductID,
    sum(Turnover) Turnover
from (select t1.*, t2.Product from futures.daily_bar t1 left join futures.instrument  t2 on t1.InstrumentID = t2.Symbol)
WHERE $timeFilter
group by t, ProductID
order by t, ProductID
```

it will show the graph correctly:
![image](https://user-images.githubusercontent.com/2265407/68923824-3142e300-07ba-11ea-953a-738ae67b6a19.png)
However, when I make table t1 as a subquery, like:

```
select
    $timeSeries t,
    extract(InstrumentID, '[a-zA-Z]+') ProductID,
    sum(Turnover) Turnover
from (select t1.*, t2.Product from (select * from futures.daily_bar) t1 left join futures.instrument  t2 on t1.InstrumentID = t2.Symbol)
WHERE $timeFilter
group by t, ProductID
order by t, ProductID
```

the graph is:
![image](https://user-images.githubusercontent.com/2265407/68923946-8c74d580-07ba-11ea-9a9e-8bddd90f7b17.png)

looks like it cannot generate multiple series by the second column. 

I also check the query inspector and I'm sure that the response meta/data is exactly same.

**Comment by hyberdk** [comment]
@variantf did you ever solve this issue? I have the exact same problem... it took me a while to figure out that it was the subquery that was the problem as the output from clickhouse looks the same to me.

**Comment by hyberdk** [comment]
@variantf, it looks like pull #206 fixes this issue..

This is the same query as before.

![image](https://user-images.githubusercontent.com/3530739/85716765-1429a780-b6ed-11ea-857a-e2e5ef508d04.png)

@Slach, I pretty sure your fix for my crash also fixed this issue.. it works for me at least ;-)
