### ISSUE TITLE
Generated SQL panel misbehaving

### ISSUE THREAD

**Issue by hagen1778** [Vertamedia/clickhouse-grafana#159]
It is happening sometimes that `Generated SQL` panel shows old query (not actual changes) or even just shows `true` instead of query:
![image](https://user-images.githubusercontent.com/2902918/69416420-7b721a00-0d0e-11ea-96ce-39d41fadee22.png)

Despite that fact plugin sends the correct query to CH, so it is just a display bug.

**Comment by grodrock** [comment]
Also waiting for it

**Comment by jackpgao** [comment]
waiting + 1

**Comment by hagen1778** [comment]
Looks like it was merged, so I'm closing this.
