### ISSUE TITLE
non-existent values extrapolated

### ISSUE THREAD

**Issue by maxxch** [Vertamedia/clickhouse-grafana#161]
I have sflow data where if we don't have data there is no record so then nearest data points are beeing connected(which i need to keep as zero)
![30069d6985acc9f6e6ae7a9958f070b2](https://user-images.githubusercontent.com/23478301/69871108-33c13480-12b2-11ea-84a9-abdb5010259f.png)
as shown on graph there was data missing since 11/26 afternoon till 11/29 around 10am.
Can you please help me to fix it or correct my settings?

**Comment by Slach** [comment]
@maxxch sorry for the late response, I promise we will get more quality feedback our plugin users

could check your error with the latest 2.0.1 version plugin which published on https://grafana.com/grafana/plugins/vertamedia-clickhouse-datasource? 

please turn off "Extrapolate" on Query Editor -> Go To Query mode

**Comment by maxxch** [comment]
Thanks Eugene, I will try and let you know
