### ISSUE TITLE
repeating panel works incorrectly

### ISSUE THREAD

**Issue by homekuanyi** [Vertamedia/clickhouse-grafana#162]
when i select "All" for a template varible, but the query params do not change anything for each repeated panel, so all of repeated panels have the same query result ( like "All" )

**Comment by Slach** [comment]
@homekuanyi could you explain what exactly works incorrectly?
I tried to reproduce your issue on the latest `master` branch, but look like everything works fine
![image](http://g.recordit.co/kBCaXpVnPX.gif)

**Comment by Slach** [comment]
I just add repeated template variable example to clickhouse_dashboard.json
@homekuanyi you can reproduce repeated behavior with following steps
```bash
git clone git@github.com:Vertamedia/clickhouse-grafana.git
cd clickhouse-grafana
docker-compose up -d grafana
```
open http://localhost:3000/dashboards -> clickhouse dashboard

feel free reopen issue if still reproduce
