### ISSUE TITLE
Please add source sql table to readme.

### ISSUE THREAD

**Issue by patsevanton** [Vertamedia/clickhouse-grafana#165]
Hello!

I read this query.
![image](https://user-images.githubusercontent.com/10828883/71639721-f16e8700-2ca5-11ea-8533-b4212987eb60.png)

And don`t understernt source sql table.

**Comment by hagen1778** [comment]
Hi @patsevanton! Could you please elaborate a bit more? What is exactly `source sql table`?

**Comment by patsevanton** [comment]
Clickhouse-grafana have example query without schema table of clickhouse.

**Comment by Slach** [comment]
@patsevanton i hope your issue covered by https://github.com/Vertamedia/clickhouse-grafana/pull/211/files#diff-04c6e90faac2675aa89e2176d2eec7d8R545
