### ISSUE TITLE
Error in console, when subquery have an alias

### ISSUE THREAD

**Issue by artemnikonov** [Vertamedia/clickhouse-grafana#167]
Hello.

If I create SQL-query with sybquery whitch have an alias, I get error in chrome console.
For example:
![image](https://user-images.githubusercontent.com/59960907/72531315-456e9380-3882-11ea-9008-7df95db26d62.png)
![image](https://user-images.githubusercontent.com/59960907/72531340-4ef7fb80-3882-11ea-9a17-f0636b9647c3.png)

But if I make subquery without alias, I have not any errors.
![image](https://user-images.githubusercontent.com/59960907/72531428-81095d80-3882-11ea-9238-85a8d7377899.png)

Grafana v6.4.3;
ClickHouse plagin v1.9.3

**Comment by Slach** [comment]
@artemnikonov closed by https://github.com/Vertamedia/clickhouse-grafana/pull/206
please check the latest `master` branch
and subscribe to https://github.com/grafana/grafana-plugin-repository/pull/656 for notifying when 2.x release will be published
