### ISSUE TITLE
Clickhouse based annotations don't seem to work

### ISSUE THREAD

**Issue by camtarn** [Vertamedia/clickhouse-grafana#168]
Hi,

I have set up an annotations table in Clickhouse, hoping to show annotations on my Clickhouse-based graphs. Using Grafana's own built-in annotations DB, I can get annotations to show up.

However, using Clickhouse, the annotations do not appear.

If I select a time range with 3 annotations, I can see the annotation query executing successfully in the Clickhouse logs. 

If I purposely break the annotation query, I can verify that the error is properly shown in the UI and in the Clickhouse logs.

If I use a dev version of clickhouse-grafana and put a breakpoint on annotationQuery() I can see the annotation results coming back and being passed to transformAnnotationResponse(). It looks like the annotations are being returned to Grafana correctly. There are no console or network errors in dev tools.

Unfortunately I haven't succeeded in building an unminified version of the Grafana front-end source, and the minified source is too gnarly for me to trace any further.

I have also set up a table panel with an identical query, so I can show that the annotations correctly follow the time selector.

There's nothing much in the Grafana back-end logs, even with logging turned up to debug.

Is there anything I could be doing wrong, or any leads to investigate further?

Thanks,
Andy

Clickhouse-grafana version: 1.9.5
Grafana version: v6.5.3 (05025c5)
Setup: Grafana in Docker, on AWS Ubuntu instance, fronted by Nginx

**Comment by camtarn** [comment]
Oh. Never mind: I've just spotted that although the response parser is returning results, time is NaN in all of them. That would definitely do it!

This is because my time column is a Clickhouse DateTime, but it seems that the response parser expects epoch time. The result is coming back as the string "2019-12-11 10:27:17", but the response parser is doing `time: Math.floor(row.time),` causing it to become NaN.

Seems like it should be an easy fix for me to just query for epoch time instead.

However, since the documentation for the Clickhouse plugin annotations says this:

"column with alias: time for the annotation event time. Use epoch time or any native date data type."

I think there's either a documentation bug, or the parser should support native DateTime.

**Comment by camtarn** [comment]
Having now worked around that issue by returning epoch time in my query, I'm still stuck with no annotations displaying. I also added a title and a tag just in case Grafana was expecting them, but no luck.

Here's what transformAnnotationResponse() is returning:

![image](https://user-images.githubusercontent.com/16687934/72853674-ff626700-3ca9-11ea-8231-c9a36703a08a.png)

**Comment by camtarn** [comment]
Having now worked around that issue by returning epoch time in my query, I'm still stuck with no annotations displaying. I also added a title and a tag just in case Grafana was expecting them, but no luck.

Here's what transformAnnotationResponse() is returning:

![image](https://user-images.githubusercontent.com/16687934/72853749-42bcd580-3caa-11ea-800a-a6af32ec8339.png)

**Comment by Slach** [comment]
@camtarn is this issue still relevant for you?
latest master version + grafana 7.x in docker-compose
for following Annotation SQL query
```
SELECT 
       toUInt64(event_time)*1000 AS time,
       if(rand() % 2 = 1, '[begin] description', '[end] description') AS text,
       arrayStringConcat(['test1', 'test2', service_name],',') AS tags
FROM default.test_grafana
WHERE
  rand() % 100 IN (1,2) AND
  toUInt64(event_time) >= $from AND toUInt64(event_time) < $to
```

show all works fine
![image](https://user-images.githubusercontent.com/105560/86387578-d0b2d880-bcac-11ea-95e0-93ce6e91fabf.png)

could you check latest `master` branch?
