### ISSUE TITLE
'opt.value.match is not a function' error when using array variable.

### ISSUE THREAD

**Issue by ryanmickler** [Vertamedia/clickhouse-grafana#169]
https://github.com/Vertamedia/clickhouse-grafana/blob/50d46ef5138f5b5d8098c1cbacc7f0d3f56e16a9/src/sql_query.ts#L548

I'm getting an error when trying to use an array variable.

My variable is called `modcha` and is a `query` variable, set up as follows. 
`SELECT DISTINCT [Module, Channel] FROM mydb.my_table`
This works fine, and see the variables getting correctly populated `[0,1], [1,1], [2,0],...`

However, in the visualization, im trying to use:
`... WHERE [Module, Channel] == [ $modcha ] ...`
And I get the error
`opt.value.match is not a function`

Using grafana v6.2.5, and installing clickhouse plugin from the cli
`grafana-cli plugins install vertamedia-clickhouse-datasource`

UPDATE:

there's even more crazy stuff going on. if I write
`... WHERE [Module, Channel] == ${modcha:json} ...`
i no longer get the `opt.value.match` error, however the generated SQL is
`WHERE [Module, Channel] == [[1,0],[1,1],[2,0],[2,1],[3,0],[3,1],[4,0],[4,1],[5,0],[5,1],[6,0],[6,1],[7,0],[7,1],[8,0],[8,1]]`
i.e. its not using an element, but the whole list of `modcha` values.

UPDATE UPDATE:
found a problem. I had enabled the `All` option for my variable, hence i was seeing the whole list. Disabling the `All` option fixed that. 
I got this to work as i wanted:
`... WHERE [Module, Channel] == [${modcha:csv}] ...`

**Comment by Slach** [comment]
@ryanmickler unfortunately, grafana 7.x broke template variables for cases when the data source plugin return each variable value as  `["string", "string"]`, but for grafana 6.7.x latest version of master works fine

as a workaround, we can use
using `SELECT arrayStringConcat(array_field,",")  ... ` for template variable  and `WHERE arrayStringConcat([field1, field2], ",") IN (${variable_name})` 
https://clickhouse.tech/docs/en/sql-reference/functions/splitting-merging-functions/#arraystringconcatarr-separator
