### ISSUE TITLE
[HELP] How can I compile it?

### ISSUE THREAD

**Issue by Denis1983** [Vertamedia/clickhouse-grafana#170]
Here ist just a question.
how can I compile it into one file like in dist folder?
If I am using tsconfig.json, it is compiled into many files.
And if acesss compiled plugin via grafana I get error:
Error: Unable to dynamically transpile ES module A loader plugin needs to be configured via `SystemJS.config

**Comment by hagen1778** [comment]
Hello! Please see https://github.com/Vertamedia/clickhouse-grafana#development. Let me know if you have any questions.

**Comment by Denis1983** [comment]
> Hello! Please see https://github.com/Vertamedia/clickhouse-grafana#development. Let me know if you have any questions.

Thank you that works!
