### ISSUE TITLE
Can`t get data from ClickHouse database

### ISSUE THREAD

**Issue by Shanginre** [Vertamedia/clickhouse-grafana#171]
I can’t get data from the clickhouse database. I have tried various settings of the data source: various access options, various authorization options. And ... did not get any result.

I have made the settings in the graphana like this:
![image](https://user-images.githubusercontent.com/11506233/75090443-b2153600-5584-11ea-8d1b-106fff1a123a.png)

This is my request. If I copy it and execute on the clickhouse console, then I get the data. That is, the request is formed rules.
![image](https://user-images.githubusercontent.com/11506233/75090530-9eb69a80-5585-11ea-9d63-ed109ffb6e4b.png)

ClickHouse database is on localhost:8123 (in console: curl 'http://localhost:8123/'     Ok.)
Grafana is on localhost:3000.
All servises are on the same machine.

I am using clickhouse server version 20.1.4 revision 54431 and grafana 6.6.2.

**Comment by hagen1778** [comment]
Hi @Shanginre! Are you sure that datasource is actually working and you CH instance receiving requests from Grafana? You may check it in Grafana Query Inspector or by simply looking into [network activity](https://developers.google.com/web/tools/chrome-devtools/network) in your browser.

**Comment by Shanginre** [comment]
CH server is actually working (in console: curl 'http://localhost:8123/' Ok.)
Grafana Query Inspector can't load (endless cycle)
In the Network panel I see the folliwing error: 

"Access to XMLHttpRequest at 'localhost:8123/?query=SELECT%20%20%20%20%20(intDiv(toUInt32(undefined)%2C%2060)%20*%2060)%20*%201000%20as%20t%2C%20%20%20%20%20count()%20FROM%20default.undefined%20WHERE%20undefined%20%3E%3D%20toDateTime(1582493563)%20GROUP%20BY%20t%20ORDER%20BY%20t%20FORMAT%20JSON&database=default' from origin 'http://localhost:3000' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https."

How can I fix this error?

**Comment by hagen1778** [comment]
There should be setting in Datasource settings `Enable CORS` or something similar. 
![image](https://user-images.githubusercontent.com/2902918/75136423-96bd3e80-56dc-11ea-8d07-6a6f0de5bd70.png)

If it won't help pls see https://community.grafana.com/t/how-to-allow-access-control-allow-origin-for-all-the-apis/2045

**Comment by Shanginre** [comment]
I have added CORS setting in Datasource settings.
I have installed the nginx web server and configured it for CORS, but no results.
I have installed the CHProxy web server and made CORS settings CORS as well, but no results.

It is very strange that I don’t even have the opportunity to select PROXY in the access settings! Is this a release feature? How can I tell Grafana to use a proxy?

![image](https://user-images.githubusercontent.com/11506233/75220972-87182580-57c2-11ea-8b79-facbc6497d3c.png)

**Comment by Shanginre** [comment]
this is very strange, but I cannot specify proxy for other types of sources, such as Prometheus, etc.

**Comment by hagen1778** [comment]
I guess this may be connected with Grafana update - https://github.com/grafana/grafana/issues/22169
Can you try older versions of Grafana?

**Comment by Shanginre** [comment]
I installed version 5.4.5 and the error went away! A very strange mistake! 

**I think you should test the plugin for newer versions of Grafana.**

Please tell me, on which latest version of grafana does the CH plugin works correctly?

**Comment by alex-zaitsev** [comment]
@Shanginre , it works with Grafana 6 before the latest update from GrafanaLabs that seem to break the compatibility.
