### ISSUE TITLE
How to measure Total cpu utilisation of cluster 

### ISSUE THREAD

**Issue by AbhinandanKurakure** [Vertamedia/clickhouse-grafana#173]
I am a beginner to clickhouse DB.I am using clickhouse DB to store the metrics and using clickhouse plugin for grafana.I have a metric named 'node_cpu_seconds_total' which is a counter which contains total cpu time spent.
I am using clickhouse plugin for grafana,and the datasource being clickhouse.
How can I show(visualize in grafana) the total cpu usage of a cluster using the above metric.

**Comment by hagen1778** [comment]
Hi @AbhinandanKurakure!
You probably need the "speed" of how that counter changes, so try to use `$rate` macros for that. You may find its description in README of the plugin.

**Comment by AbhinandanKurakure** [comment]
@hagen1778   can you provide an explanation of how to exactly used `$rate` macro as there is only one  example provided in the README of the plugin.Except that example i am unable to think of way to use '$rate' macro.This is the first time i am working on a TSDB so i am finding it a little difficult

**Comment by hagen1778** [comment]
$rate(countIf(Type = 200) AS good, countIf(Type != 200) AS bad) FROM requests
`$rate(column)` accepts a column name or expression as argument and calculates the per-second average rate of increase for that argument. It is very similar to [Prometheus rate](https://prometheus.io/docs/prometheus/latest/querying/functions/#rate) function.

Let's take for example your counter `node_cpu_seconds_total`. The counters are always growing, so in CH table it will be stored like following:
Time | Value
12:00  100
12:01  150
12:02  200
12:03  250
12:04  300

To get the CPU usage graph you'd need to calculate the "speed" of the counter increase. So if we want to get the CPU usage between 12:00 and 12:01 we would need to get the difference between values in those datapoints and divide by amount of seconds in that range:
`(150 - 100) / (12:01-12:00) = 50 / 60 = 0.83` - the CPU usage was 0.83

`$rate` macros builds a CH query which calculates exactly that - the difference between values in moments of time Tn and Tn+1, and divides them by the amount of seconds between them.

So your query will look like following:
`$rate(node_cpu_seconds_total) FROM <your_table_name>`

Please note, that time filter will be automatically added to query based on Grafana datetime picker.

**Comment by AbhinandanKurakure** [comment]
Thank you for the excellent answer @hagen1778.One more doubt, but the `$rate` always expects an aggregate operation

**Comment by AbhinandanKurakure** [comment]
I have checked your #78 issue where you are provided `$perSecond()` macro.So is it better to use `$perSecond()` macro rather than `$rate()`?

**Comment by hagen1778** [comment]
Oh, you're right! I totally forgot how everything works(( Rate doesn't calculate difference between values, but `$perSecond` does. Sorry for miss leading you.

**Comment by AbhinandanKurakure** [comment]
My query in clickhouse will yield the following result where `mdlbl_cpu` is cpu core and `mdlbl_mode` is linux mode.

SELECT 
    startTime, 
    endTime, 
    doubleVal
FROM telemetry
WHERE (md_type = 'node_cpu_seconds_total') AND (mdlbl_cpu = '1') AND (mdlbl_mode IN ('user')) 

┌───────────startTime─┬─────────────endTime─┬─doubleVal─┐
│ 2020-03-30 00:15:04 │ 2020-03-30 00:15:04 │  31760.62 │
│ 2020-03-30 00:39:04 │ 2020-03-30 00:39:04 │  31817.48 │
│ 2020-03-30 01:19:04 │ 2020-03-30 01:19:04 │   31915.1 │
│ 2020-03-30 01:27:04 │ 2020-03-30 01:27:04 │  31934.19 │
│ 2020-03-30 01:43:04 │ 2020-03-30 01:43:04 │  31971.88 │
│ 2020-03-30 01:51:04 │ 2020-03-30 01:51:04 │  31988.56 │
│ 2020-03-30 02:31:04 │ 2020-03-30 02:31:04 │  32078.36 │
│ 2020-03-30 02:39:04 │ 2020-03-30 02:39:04 │  32096.77 │
│ 2020-03-30 02:55:04 │ 2020-03-30 02:55:04 │   32133.1 │
│ 2020-03-30 03:03:04 │ 2020-03-30 03:03:04 │  32152.76 │
│ 2020-03-30 03:11:04 │ 2020-03-30 03:11:04 │  32174.81 │
│ 2020-03-30 03:19:04 │ 2020-03-30 03:19:04 │  32195.54 │
│ 2020-03-30 03:35:04 │ 2020-03-30 03:35:04 │   32234.1 │
│ 2020-03-30 03:51:04 │ 2020-03-30 03:51:04 │  32272.77 │
│ 2020-03-30 04:15:04 │ 2020-03-30 04:15:04 │  32330.48 │
│ 2020-03-30 04:23:04 │ 2020-03-30 04:23:04 │     32347 │
│ 2020-03-30 04:31:04 │ 2020-03-30 04:31:04 │  32365.88 │
│ 2020-03-30 04:39:04 │ 2020-03-30 04:39:04 │  32383.15 │
│ 2020-03-30 04:47:04 │ 2020-03-30 04:47:04 │  32404.85 │
│ 2020-03-30 05:03:04 │ 2020-03-30 05:03:04 │  32448.73 │
│ 2020-03-30 05:11:04 │ 2020-03-30 05:11:04 │  32467.53 │
│ 2020-03-30 05:27:04 │ 2020-03-30 05:27:04 │  32510.53 │
│ 2020-03-30 05:35:04 │ 2020-03-30 05:35:04 │  32528.52 │
│ 2020-03-30 05:43:04 │ 2020-03-30 05:43:04 │  32548.69 │
│ 2020-03-30 06:07:04 │ 2020-03-30 06:07:04 │  32608.75 │
│ 2020-03-30 06:55:04 │ 2020-03-30 06:55:04 │  32719.19 │
│ 2020-03-30 07:03:04 │ 2020-03-30 07:03:04 │  32738.55 │
└─────────────────────┴─────────────────────┴───────────┘
┌───────────startTime─┬─────────────endTime─┬─doubleVal─┐
│ 2020-03-29 08:39:04 │ 2020-03-29 08:39:04 │  29455.87 │
│ 2020-03-29 08:47:04 │ 2020-03-29 08:47:04 │  29473.14 │
│ 2020-03-29 08:55:04 │ 2020-03-29 08:55:04 │   29493.6 │
│ 2020-03-29 09:11:04 │ 2020-03-29 09:11:04 │  29535.15 │
│ 2020-03-29 09:19:04 │ 2020-03-29 09:19:04 │  29552.15 │
│ 2020-03-29 09:27:04 │ 2020-03-29 09:27:04 │  29577.62 │
│ 2020-03-29 09:35:04 │ 2020-03-29 09:35:04 │  29597.61 │
│ 2020-03-29 09:59:04 │ 2020-03-29 09:59:04 │  29656.29 │
│ 2020-03-29 10:07:04 │ 2020-03-29 10:07:04 │   29676.8 │
│ 2020-03-29 10:15:04 │ 2020-03-29 10:15:04 │   29697.4 │
│ 2020-03-29 10:23:04 │ 2020-03-29 10:23:04 │  29716.44 │
│ 2020-03-29 10:55:04 │ 2020-03-29 10:55:04 │  29787.19 │
│ 2020-03-29 11:27:04 │ 2020-03-29 11:27:04 │  29859.93 │
│ 2020-03-29 11:43:04 │ 2020-03-29 11:43:04 │  29898.75 │
│ 2020-03-29 11:59:04 │ 2020-03-29 11:59:04 │  29939.35 │
│ 2020-03-29 12:07:04 │ 2020-03-29 12:07:04 │  29955.04 │
│ 2020-03-29 12:23:04 │ 2020-03-29 12:23:04 │  29996.93 │
│ 2020-03-29 12:31:04 │ 2020-03-29 12:31:04 │  30016.47 │
│ 2020-03-29 12:47:04 │ 2020-03-29 12:47:04 │  30053.76 │
│ 2020-03-29 12:55:04 │ 2020-03-29 12:55:04 │  30071.21 │
│ 2020-03-29 13:19:04 │ 2020-03-29 13:19:04 │  30134.43 │
│ 2020-03-29 13:27:04 │ 2020-03-29 13:27:04 │  30156.18 │
│ 2020-03-29 13:59:04 │ 2020-03-29 13:59:04 │  30230.64 │
│ 2020-03-29 14:23:04 │ 2020-03-29 14:23:04 │  30287.38 │
│ 2020-03-29 14:39:04 │ 2020-03-29 14:39:04 │  30329.89 │
│ 2020-03-29 14:47:04 │ 2020-03-29 14:47:04 │  30351.74 │
│ 2020-03-29 14:55:04 │ 2020-03-29 14:55:04 │  30370.42 │
│ 2020-03-29 15:03:04 │ 2020-03-29 15:03:04 │  30387.35 │
│ 2020-03-29 15:35:04 │ 2020-03-29 15:35:04 │  30477.18 │
│ 2020-03-29 15:43:04 │ 2020-03-29 15:43:04 │  30497.31 │
│ 2020-03-29 16:07:04 │ 2020-03-29 16:07:04 │   30552.2 │
│ 2020-03-29 16:23:04 │ 2020-03-29 16:23:04 │  30589.27 │
│ 2020-03-29 16:31:04 │ 2020-03-29 16:31:04 │  30610.48 │
│ 2020-03-29 16:55:04 │ 2020-03-29 16:55:04 │  30664.79 │
│ 2020-03-29 17:19:04 │ 2020-03-29 17:19:04 │  30720.28 │
│ 2020-03-29 17:27:04 │ 2020-03-29 17:27:04 │  30739.86 │
│ 2020-03-29 17:35:04 │ 2020-03-29 17:35:04 │  30760.42 │
│ 2020-03-29 17:43:04 │ 2020-03-29 17:43:04 │  30778.43 │
│ 2020-03-29 17:51:04 │ 2020-03-29 17:51:04 │  30799.04 │
│ 2020-03-29 18:07:04 │ 2020-03-29 18:07:04 │  30834.86 │
│ 2020-03-29 18:23:04 │ 2020-03-29 18:23:04 │  30868.95 │
│ 2020-03-29 18:31:04 │ 2020-03-29 18:31:04 │  30892.31 │
│ 2020-03-29 18:39:04 │ 2020-03-29 18:39:04 │  30909.81 │
│ 2020-03-29 19:03:04 │ 2020-03-29 19:03:04 │   30976.5 │
│ 2020-03-29 19:11:04 │ 2020-03-29 19:11:04 │  30995.32 │
│ 2020-03-29 19:35:04 │ 2020-03-29 19:35:04 │  31053.39 │
│ 2020-03-29 19:43:04 │ 2020-03-29 19:43:04 │  31074.51 │
│ 2020-03-29 19:51:04 │ 2020-03-29 19:51:04 │  31092.59 │
│ 2020-03-29 19:59:04 │ 2020-03-29 19:59:04 │  31109.29 │
│ 2020-03-29 20:07:04 │ 2020-03-29 20:07:04 │  31126.03 │
│ 2020-03-29 20:39:04 │ 2020-03-29 20:39:04 │  31203.82 │
│ 2020-03-29 20:55:04 │ 2020-03-29 20:55:04 │  31245.42 │
│ 2020-03-29 21:03:04 │ 2020-03-29 21:03:04 │  31266.08 │
│ 2020-03-29 21:11:04 │ 2020-03-29 21:11:04 │  31283.65 │
│ 2020-03-29 21:35:04 │ 2020-03-29 21:35:04 │  31343.15 │
│ 2020-03-29 21:43:04 │ 2020-03-29 21:43:04 │  31360.89 │
│ 2020-03-29 22:07:04 │ 2020-03-29 22:07:04 │  31425.97 │
│ 2020-03-29 22:23:04 │ 2020-03-29 22:23:04 │  31466.37 │
│ 2020-03-29 22:55:04 │ 2020-03-29 22:55:04 │  31554.45 │
│ 2020-03-29 23:19:04 │ 2020-03-29 23:19:04 │  31613.28 │
│ 2020-03-29 23:51:04 │ 2020-03-29 23:51:04 │  31700.66 │
│ 2020-03-29 23:59:04 │ 2020-03-29 23:59:04 │  31719.34 │
└─────────────────────┴─────────────────────┴───────────┘
┌───────────startTime─┬─────────────endTime─┬─doubleVal─┐
│ 2020-03-29 09:03:04 │ 2020-03-29 09:03:04 │  29513.14 │
│ 2020-03-29 09:43:04 │ 2020-03-29 09:43:04 │  29615.83 │
│ 2020-03-29 09:51:04 │ 2020-03-29 09:51:04 │  29635.17 │
│ 2020-03-29 10:31:04 │ 2020-03-29 10:31:04 │   29734.7 │
│ 2020-03-29 10:39:04 │ 2020-03-29 10:39:04 │   29753.7 │
│ 2020-03-29 10:47:04 │ 2020-03-29 10:47:04 │   29771.7 │
│ 2020-03-29 11:03:04 │ 2020-03-29 11:03:04 │  29804.35 │
│ 2020-03-29 11:11:04 │ 2020-03-29 11:11:04 │  29824.21 │
│ 2020-03-29 11:19:04 │ 2020-03-29 11:19:04 │  29841.13 │
│ 2020-03-29 11:35:04 │ 2020-03-29 11:35:04 │  29877.68 │
│ 2020-03-29 11:51:04 │ 2020-03-29 11:51:04 │  29919.24 │
│ 2020-03-29 12:15:04 │ 2020-03-29 12:15:04 │  29978.21 │
│ 2020-03-29 12:39:04 │ 2020-03-29 12:39:04 │  30035.81 │
│ 2020-03-29 13:03:04 │ 2020-03-29 13:03:04 │  30090.86 │
│ 2020-03-29 13:11:04 │ 2020-03-29 13:11:04 │  30114.32 │
│ 2020-03-29 13:35:04 │ 2020-03-29 13:35:04 │  30175.32 │
│ 2020-03-29 13:43:04 │ 2020-03-29 13:43:04 │  30191.68 │
│ 2020-03-29 13:51:04 │ 2020-03-29 13:51:04 │  30214.04 │
│ 2020-03-29 14:07:04 │ 2020-03-29 14:07:04 │   30248.7 │
│ 2020-03-29 14:15:04 │ 2020-03-29 14:15:04 │  30266.74 │
│ 2020-03-29 14:31:04 │ 2020-03-29 14:31:04 │  30314.19 │
│ 2020-03-29 15:11:04 │ 2020-03-29 15:11:04 │  30409.68 │
│ 2020-03-29 15:19:04 │ 2020-03-29 15:19:04 │  30437.13 │
│ 2020-03-29 15:27:04 │ 2020-03-29 15:27:04 │  30455.38 │
│ 2020-03-29 15:51:04 │ 2020-03-29 15:51:04 │  30515.03 │
│ 2020-03-29 15:59:04 │ 2020-03-29 15:59:04 │  30533.92 │
│ 2020-03-29 16:15:04 │ 2020-03-29 16:15:04 │  30570.48 │
│ 2020-03-29 16:39:04 │ 2020-03-29 16:39:04 │  30629.07 │
│ 2020-03-29 16:47:04 │ 2020-03-29 16:47:04 │  30648.24 │
│ 2020-03-29 17:03:04 │ 2020-03-29 17:03:04 │   30685.7 │
│ 2020-03-29 17:11:04 │ 2020-03-29 17:11:04 │   30702.5 │
│ 2020-03-29 17:59:04 │ 2020-03-29 17:59:04 │  30816.41 │
│ 2020-03-29 18:15:04 │ 2020-03-29 18:15:04 │  30852.14 │
│ 2020-03-29 18:47:04 │ 2020-03-29 18:47:04 │  30934.29 │
│ 2020-03-29 18:55:04 │ 2020-03-29 18:55:04 │  30958.01 │
│ 2020-03-29 19:19:04 │ 2020-03-29 19:19:04 │  31013.25 │
│ 2020-03-29 19:27:04 │ 2020-03-29 19:27:04 │  31032.68 │
│ 2020-03-29 20:15:04 │ 2020-03-29 20:15:04 │  31142.38 │
│ 2020-03-29 20:23:04 │ 2020-03-29 20:23:04 │   31166.7 │
│ 2020-03-29 20:31:04 │ 2020-03-29 20:31:04 │  31184.46 │
│ 2020-03-29 20:47:04 │ 2020-03-29 20:47:04 │  31225.75 │
│ 2020-03-29 21:19:04 │ 2020-03-29 21:19:04 │  31303.97 │
│ 2020-03-29 21:27:04 │ 2020-03-29 21:27:04 │   31326.2 │
│ 2020-03-29 21:51:04 │ 2020-03-29 21:51:04 │  31384.24 │
│ 2020-03-29 21:59:04 │ 2020-03-29 21:59:04 │  31406.07 │
│ 2020-03-29 22:15:04 │ 2020-03-29 22:15:04 │  31448.52 │
│ 2020-03-29 22:31:04 │ 2020-03-29 22:31:04 │  31488.55 │
│ 2020-03-29 22:39:04 │ 2020-03-29 22:39:04 │  31511.77 │
│ 2020-03-29 22:47:04 │ 2020-03-29 22:47:04 │  31532.39 │
│ 2020-03-29 23:03:04 │ 2020-03-29 23:03:04 │  31575.78 │
│ 2020-03-29 23:11:04 │ 2020-03-29 23:11:04 │  31593.15 │
│ 2020-03-29 23:27:04 │ 2020-03-29 23:27:04 │  31632.48 │
│ 2020-03-29 23:35:04 │ 2020-03-29 23:35:04 │  31654.34 │
│ 2020-03-29 23:43:04 │ 2020-03-29 23:43:04 │  31679.48 │
└─────────────────────┴─────────────────────┴───────────┘
┌───────────startTime─┬─────────────endTime─┬─doubleVal─┐
│ 2020-03-30 00:07:04 │ 2020-03-30 00:07:04 │  31742.47 │
│ 2020-03-30 00:23:04 │ 2020-03-30 00:23:04 │  31779.49 │
│ 2020-03-30 00:31:04 │ 2020-03-30 00:31:04 │  31797.54 │
│ 2020-03-30 00:47:04 │ 2020-03-30 00:47:04 │  31837.91 │
│ 2020-03-30 00:55:04 │ 2020-03-30 00:55:04 │  31856.43 │
│ 2020-03-30 01:03:04 │ 2020-03-30 01:03:04 │   31876.9 │
│ 2020-03-30 01:11:04 │ 2020-03-30 01:11:04 │  31897.03 │
│ 2020-03-30 01:35:04 │ 2020-03-30 01:35:04 │  31950.53 │
│ 2020-03-30 01:59:04 │ 2020-03-30 01:59:04 │  32006.92 │
│ 2020-03-30 02:07:04 │ 2020-03-30 02:07:04 │  32022.71 │
│ 2020-03-30 02:15:04 │ 2020-03-30 02:15:04 │  32045.37 │
│ 2020-03-30 02:23:04 │ 2020-03-30 02:23:04 │  32062.83 │
│ 2020-03-30 02:47:04 │ 2020-03-30 02:47:04 │  32115.05 │
│ 2020-03-30 03:27:04 │ 2020-03-30 03:27:04 │   32216.9 │
│ 2020-03-30 03:43:04 │ 2020-03-30 03:43:04 │  32254.02 │
│ 2020-03-30 03:59:04 │ 2020-03-30 03:59:04 │  32293.59 │
│ 2020-03-30 04:07:04 │ 2020-03-30 04:07:04 │  32313.13 │
│ 2020-03-30 04:55:04 │ 2020-03-30 04:55:04 │  32424.73 │
│ 2020-03-30 05:19:04 │ 2020-03-30 05:19:04 │  32491.14 │
│ 2020-03-30 05:51:04 │ 2020-03-30 05:51:04 │  32567.87 │
│ 2020-03-30 05:59:04 │ 2020-03-30 05:59:04 │  32589.79 │
│ 2020-03-30 06:15:04 │ 2020-03-30 06:15:04 │  32627.75 │
│ 2020-03-30 06:23:04 │ 2020-03-30 06:23:04 │  32645.54 │
│ 2020-03-30 06:31:04 │ 2020-03-30 06:31:04 │  32664.45 │
│ 2020-03-30 06:39:04 │ 2020-03-30 06:39:04 │  32682.95 │
│ 2020-03-30 06:47:04 │ 2020-03-30 06:47:04 │  32699.03 │
└─────────────────────┴─────────────────────┴───────────┘

So in grafana code and output is 

![image](https://user-images.githubusercontent.com/46265395/77899761-a6f7a900-729a-11ea-95ec-121452127cc1.png)
Is it Correct?

**Comment by hagen1778** [comment]
Looks correct. Let's try to calculate manually. Last values are:
```
│ 2020-03-30 06:15:04 │ 2020-03-30 06:15:04 │ 32627.75 │
│ 2020-03-30 06:23:04 │ 2020-03-30 06:23:04 │ 32645.54 │
│ 2020-03-30 06:31:04 │ 2020-03-30 06:31:04 │ 32664.45 │
│ 2020-03-30 06:39:04 │ 2020-03-30 06:39:04 │ 32682.95 │
│ 2020-03-30 06:47:04 │ 2020-03-30 06:47:04 │ 32699.03 │
```
You use `endTime` as DateTime column, so we will base calculation on that:
1. skip first datapoint since nothing to compare with
2. (32645.54  - 32627.75) / (2020-03-30 06:23:04 - 2020-03-30 06:15:04) = (32645.54  - 32627.75) / (8*60) = 0.037 // step is always the same - 8 minutes
3. (32664.45 - 32645.54) / (8*60) = 0.039
4. (32682.95 - 32664.45) / (8*60) = 0.038
5. (32699.03 - 32682.95) / (8*60) = 0.033

Looks correct. Do you have doubts?

**Comment by AbhinandanKurakure** [comment]
No more Doubts.Thanks you very much
