### ISSUE TITLE
/mode-clickhouse.js request

### ISSUE THREAD

**Issue by juris** [Vertamedia/clickhouse-grafana#174]
For some reason, when panel with ClickHouse datasource is loading, there is a request to:
https://<SERVER_ROOT>/mode-clickhouse.js
Which returns nothing.

Grafana 6.7.1

**Comment by Slach** [comment]
yep. confirmed, but I don't know why this happens inside grafana app in public/build/brace*.js 
this URL return HTML instead of Javascript
