### ISSUE TITLE
Wrong current value on graph or table but correct in query inspector

### ISSUE THREAD

**Issue by diywarrior** [Vertamedia/clickhouse-grafana#179]
Hello,
My case is really specific but hope that someone could help me. 

So in short, i have materialized view with summary information on amount of mailed users of my service. Example: 
![Selection_086](https://user-images.githubusercontent.com/18305071/79438293-04e6f900-7fdc-11ea-9142-4a4af040e3f7.png)

As i need optional aggregation (by day, week, month, year) - i'm generating timeseries this way: 
```
(intDiv(toUInt32(toStartOfDay(send_time)), 1200) * 1200) * 1000                 AS period_day,
(intDiv(toUInt32(toStartOfDay(toStartOfWeek(send_time))), 1200) * 1200) * 1000  AS period_week,
(intDiv(toUInt32(toStartOfDay(toStartOfMonth(send_time))), 1200) * 1200) * 1000 AS period_month,
(intDiv(toUInt32(toStartOfDay(toStartOfYear(send_time))), 1200) * 1200) * 1000  AS period_year
```

Here  is example of query: 
```
SELECT
        multiIf('$period_of_aggregation' = 'week', period_week, '$period_of_aggregation' = 'month', period_month,
            '$period_of_aggregation' = 'year', period_year, period_day) as t,
      sum(sent) as sent
    FROM dc.mails_aggregated
    WHERE
        $timeFilter
        AND status = 'sent'
        AND dispatch_type in ($dispatch_type)
        AND domain in ($domains)
    GROUP BY t
    ORDER BY t
```
**Issue:** point of graph (or line in table) for current day differs value, returned by query inspector if picked timerange is more than 7days, if it's 7days or less - value is correct.

Example: 
Table: 
![Selection_087](https://user-images.githubusercontent.com/18305071/79439187-2e545480-7fdd-11ea-9607-c0b2b1594d3a.png)

![Selection_088](https://user-images.githubusercontent.com/18305071/79439373-6bb8e200-7fdd-11ea-920f-2a6072163674.png)

If i pick time range 7 days - value for current day becomes correct (105.24 K)

Same behavior is for graph representation. 

I tried  this on different grafana and CH-plugin versions, including latest. I'm ablre to reproduce this everywhere. 

I will be grateful for your thoughts and advice.

**Comment by kirik** [comment]
Have just the same problem

**Comment by diywarrior** [comment]
@kirik It worked like a charm! 
Thank you for suggestion
Closing issue.

**Comment by kirik** [comment]
@diywarrior could you please reopen issue? I believe this is a bug.
I'm not sure is it grafana or ch-grafana related - I have ES and Prometheus datasources and they works just fine for any range of time.

**Comment by diywarrior** [comment]
Same stack and issue for me. 
Currently this workaround is good enough for me, but you're right.
Maybe better to resolve this

**Comment by Slach** [comment]
value for last N datapoint in `time series` format extrapolated 
it's described on FAQ 
https://github.com/Vertamedia/clickhouse-grafana#faq
maybe this behavior should be optional

**Comment by kirik** [comment]
Thank you @Slach for explanation!
And yes I think too that this behavior should be optional (or off by default) because it produce wrong numbers.
