### ISSUE TITLE
Add extremes to the output

### ISSUE THREAD

**Issue by Felixoid** [Vertamedia/clickhouse-grafana#180]
Hello colleagues, and thank you for a great plugin!

ClickHouse has pretty cool features [GROUP BY WITH TOTAL](https://clickhouse.tech/docs/en/sql_reference/statements/select/#with-totals-modifier) and [extremes](https://clickhouse.tech/docs/en/operations/settings/settings/#extremes). When added, they add objects `totals` and `extremes` accordingly into json payload:

```json
{
	"meta":
	[
		{
			"name": "project",
			"type": "String"
		},
		{
			"name": "perc_95",
			"type": "Int64"
		}
	],
	"data":
	[
         .........
	],
	"totals":
	{
		"project": "",
		"perc_95": "1280689048"
	},
	"extremes":
	{
		"min":
		{
			"project": "a",
			"perc_95": 6
		},
		"max":
		{
			"project": "w",
			"perc_95": 704863237
		}
	},
	"rows": 11,
	"statistics":
	{
		"elapsed": 4.749738699,
		"rows_read": 33802496,
		"bytes_read": 2563889693
	}
}
```

It would be great to add these object to data somehow!

**Comment by Slach** [comment]
Could you suggest examples and use cases for this data inside grafana? 
I think this proposal restrict by grafana visualization and panel plugins

only one visualization plugin would be applied for total and extremes it's a `table` plugin, but total, min, max already implemented on https://grafana.com/docs/grafana/latest/features/panels/table_panel/  and can be calculated on "client-side"

**Comment by Felixoid** [comment]
Hello @Slach, sorry for a long silence.

You are right, my problem was in the Int64+json. https://clickhouse.tech/docs/en/operations/settings/settings/#session_settings-output_format_json_quote_64bit_integers

Basically, this setting has solved the issue and now this ticket is completely redundant.
