### ISSUE TITLE
plugin no longer works in grafana 7.0+

### ISSUE THREAD

**Issue by malsumis** [Vertamedia/clickhouse-grafana#188]
Hi,

after upgrading to grafana 7.0.1 the Vertamedia Clickhouse plugin no longer works. It fails with the following error:

> ace is not defined Evaluating https://grafana/public/plugins/vertamedia-clickhouse-datasource/module.js Loading plugins/vertamedia-clickhouse-datasource/module
Data Source Error

**Comment by Slach** [comment]
@malsumis 
could you check latest grafana 7.0.3 with latest master?

you need make something like this
```
rm -rfv /var/lib/grafana/plugins/vertamedia-clickhouse/
git clone https://github.com/Vertamedia/clickhouse-grafana /var/lib/grafana/plugins/vertamedia-clickhouse/
systemctl restart grafana
```

**Comment by malsumis** [comment]
Sorry for the late reply. Got caught in other stuff. Seems to work fine with thhe latest master.

Big thanks!

**Comment by xuanyuanaosheng** [comment]
@Slach  The official grafan is using  `grafana-cli plugins install vertamedia-clickhouse-datasource`.  The plugin dir is /var/lib/grafana/plugins/vertamedia-clickhouse-datasource

**Comment by Slach** [comment]
@xuanyuanaosheng do you mean plugin still not work with your grafana 7.x?

could you provide more context and steps to reproduce?
which error message you see?

**Comment by Slach** [comment]
@xuanyuanaosheng, please look https://github.com/Vertamedia/clickhouse-grafana/issues/235#issuecomment-657258015
this solution is applicable for you?
