### ISSUE TITLE
Grafana ignoring NULL value

### ISSUE THREAD

**Issue by iShift** [Vertamedia/clickhouse-grafana#19]
Grafana ignoring NULL value is clickhouse send "NULL" but works if manual send "null"

**Comment by iShift** [comment]
Temporary fix for me - if(isNull(value), toString('null'), toString(value))

**Comment by hagen1778** [comment]
Hi @iShift 
Pls, check https://github.com/Vertamedia/clickhouse-grafana/releases/tag/1.2.1
