### ISSUE TITLE
Does your plugin use Custom HTTP headers?

### ISSUE THREAD

**Issue by kotchuprik** [Vertamedia/clickhouse-grafana#190]
Hey! I continue to be happy with your data source plugin and just tried to use Browser fetch requests instead of Server and turned on the flag for sending CORS query param, but it works when API sends Origin param, I did set, and no Origin param sends. Checked the source code and haven't found any mentions about custom headers. Is it correct, or am I wrong?

![image](https://user-images.githubusercontent.com/802946/83338188-78ae3e00-a2ca-11ea-9f13-9dcbb6cfaeb0.png)

**Comment by Slach** [comment]
@kotchuprik as I can see in https://github.com/grafana/grafana/pull/11643/files
and here https://github.com/grafana/grafana/pull/17846

grafana support custom HTTP headers only for "Server" access mode, cause HTTP Headers values is secureJSON area and add on server side golang proxy
