### ISSUE TITLE
Null values are displayed in a graph panel 

### ISSUE THREAD

**Issue by adivinho** [Vertamedia/clickhouse-grafana#194]
We have got a strange behavior with null values in graph panels.
Our table has records with one of two possible service types mysql, postgresql
![Screenshot_20200615_193757](https://user-images.githubusercontent.com/25184101/84683346-c0c29700-af3f-11ea-870f-66c828966b97.png)

So if mysql services are stopped and data in the table is related to postgresql only
then charts still shows some values for disabled mysql services.  
![Screenshot_20200615_190918](https://user-images.githubusercontent.com/25184101/84683396-d1730d00-af3f-11ea-9158-2bca9620d0d0.png)

If used time range covers only one of action (stop/start) for mysql service than charts are correct but tooltip shows nearest known value (181, 470) instead of 0.
![Screenshot_20200615_190952](https://user-images.githubusercontent.com/25184101/84683409-d6d05780-af3f-11ea-935d-46a968a2d670.png)

![Screenshot_20200615_191028](https://user-images.githubusercontent.com/25184101/84683419-da63de80-af3f-11ea-945a-dff6c033a03e.png)

**Comment by Slach** [comment]
@adivinho which version `clickhouse-grafana` plugin do you use? 1.9.5 or latest 2.0.0?
could also provide more context?
- did you try to turn off "Extrapolation" option when editing query in grafana clickhouse plugin?
- did you try to toggle "staircase" option in "visualization"?
- which mode do you use for null values for "stacked" graph? did you try to use "null as zero"?

I tried to reproduce your use case with following table structure and data:

```
CREATE TABLE IF NOT EXISTS default.test_grafana(event_time DateTime, service_name LowCardinality(String))
ENGINE=MergeTree()
    PARTITION BY toYYYYMM(event_time)
    ORDER BY (event_time, service_name);

INSERT INTO default.test_grafana SELECT toDateTime(now()-(number*10)) AS event_time, if(rand() % 2 = 1,'mysql','postgresql') AS service_name FROM numbers(1000);

INSERT INTO default.test_grafana SELECT toDateTime(now()+(number*10)) AS event_time, 'mysql' AS service_name FROM numbers(1000);

INSERT INTO default.test_grafana SELECT toDateTime(now()+((500+number)*10)) AS event_time, 'postgresql' AS service_name FROM numbers(1000);

```

for following grafana query:
```
SELECT
    $timeSeries as t,
    countIf(service_name='mysql') AS mysql,
    countIf(service_name='postgresql') AS postgresql
FROM $table
WHERE $timeFilter
GROUP BY t
ORDER BY t
```
I got expected zero values for time range where MySQL is not exists
![image](https://user-images.githubusercontent.com/105560/84895565-f096a980-b0bb-11ea-934d-3ceeda8a4d09.png)

```

**Comment by adivinho** [comment]
I have just tested it with the latest 2.0.0 version and now all charts are shown correctly. 
![Screenshot_20200617_164554](https://user-images.githubusercontent.com/25184101/84906029-18850d80-b0ba-11ea-839a-4516e1c0cf14.png)
