### ISSUE TITLE
golang part not works with $columns, $perSecond and $perSecondColumns macros

### ISSUE THREAD

**Issue by Slach** [Vertamedia/clickhouse-grafana#197]
@bmanth60 
could you help us solve
https://github.com/grafana/grafana-plugin-repository/pull/656#issuecomment-645432626
ASAP?

**Comment by bmanth60** [comment]
Thanks for resolving this, sorry I was tied up with work.

**Comment by Slach** [comment]
@bmanth60 also, I think we need refactoring and rewrite from `https://github.com/grafana/grafana-plugin-model` to `https://github.com/grafana/grafana-plugin-sdk-go/`
