### ISSUE TITLE
Full Support "ad-hoc filter" variable type "values" filter

### ISSUE THREAD

**Issue by Slach** [Vertamedia/clickhouse-grafana#198]
the current implementation only supports Enum fields values
we need to add processing and cache `SELECT DISTINCT field FROM table LIMIT X` for getTagValues

**Comment by PeterZaitsev** [comment]
Right. You probably also want to use the current time range  to this query so only relevant values pulled in

**Comment by Slach** [comment]
@PeterZaitsev adhoc values filter basic functionality implemented
unfortunately, grafana core doesn't provide additional context to `adhoc.ts` functions, so only
```sql 
SELECT DISTINCT {field} AS value FROM {database}.{table} LIMIT 300
```
was implement, it can be suboptimal for high cardinality values and make full column scan (PK scan or secondary index scan for some cases) in ClickHouse table
