### ISSUE TITLE
[HELP] How to Install plugin?

### ISSUE THREAD

**Issue by vvp83** [Vertamedia/clickhouse-grafana#2]
Please tell how install plugin to grafana 4.1.x?

**Comment by vvp83** [comment]
Copy source to /var/lib/grafana/plugins.
Restart grafana

**Comment by f1yegor** [comment]
@hagen1778 you could probably investigate how to add this plugin to grafana.net. More visibility, easier installation, updates notifier

**Comment by hagen1778** [comment]
@f1yegor i think that plugin is not ready for grafana.net - no tests, no alerts and annotations support
