### ISSUE TITLE
An unexpected error happened

### ISSUE THREAD

**Issue by hyberdk** [Vertamedia/clickhouse-grafana#202]
Hi all, 

I have a tendency to get "unexpected errors" from Grafane using the ClickHouse plugin. Here is the output I get.. Im not sure how to troubleshoot it exactly, so any guidance will be appriciated.

My enviroment is:
Grafana 7.0.3 (in docker) 
clickhouse-grafana 2.0.1 plugin (manually dropped in the plugins folder)
ClickHouse server version 20.4.4 revision 54434 (also in docker)

here is the fault I get:

```
An unexpected error happened
Details
TypeError: Cannot read property 'length' of undefined

    in t
    in t
    in div
    in div
    in div
    in div
    in div
    in t
    in t
    in t
    in div
    in Ma
    in div
    in on
    in div
    in div
    in t
    in div
    in t
    in div
    in t
    in div
    in t
    in div
    in div
    in t
    in x
    in div
    in t
    in x
    in r
    in Unknown
    in t
    in Unknown
    in h
    in Unknown
    in Unknown
    in t
    in t
    in l
```

If I want to reproduce it I do this query:

```
select 
  sum(bytes) as total,
  mysql_app_name
  FROM
  $table CLICKHOUSE
INNER JOIN (SELECT app_id_hex, app_name AS mysql_app_name FROM netflow.applications) MYSQL
ON CLICKHOUSE.appid = MYSQL.app_id_hex
WHERE $timeFilter AND hostname = '$hostname' AND (iface_out_desc = '$iface' OR iface_in_desc = '$iface')
GROUP BY mysql_app_name
ORDER BY total DESC
```

it looks like this when I put it into a table:
![image](https://user-images.githubusercontent.com/3530739/85271916-be01fd80-b47b-11ea-8213-2a98fcbe0d69.png)

So it looks like the query is fine, but as soon as I change the "Visualization" to a Pie Chart, it crashes with the above fault. 

Any ideas?

**Comment by hyberdk** [comment]
Hi Eugene (@Slach), 

thanks a lot for looking into this problem.. I really appropriate it.

I can confirm that the Pie Chart now works, but there is one catch..

I _have_ to select "Format as Time series", if I select "Format as Table" I still get an error

This is what I mean: "Time series" works, "Table" no joy..

![image](https://user-images.githubusercontent.com/3530739/85711191-4f28dc80-b6e7-11ea-94d9-a4e6c37c809c.png)

to be sure that I was using the latest master, I forked the repo changed the version to 2.0.2-hyberdk and used that package.

![image](https://user-images.githubusercontent.com/3530739/85711367-80091180-b6e7-11ea-8136-cdf09a755bd8.png)


Anyways, this is the error that I am getting (looks like the same as before):

```
An unexpected error happened
Details
TypeError: Cannot read property 'length' of undefined

    in t
    in t
    in div
    in div
    in div
    in div
    in div
    in t
    in t
    in t
    in div
    in Ma
    in div
    in on
    in div
    in div
    in t
    in div
    in t
    in div
    in t
    in div
    in t
    in div
    in div
    in t
    in x
    in div
    in t
    in x
    in r
    in Unknown
    in t
    in Unknown
    in h
    in Unknown
    in Unknown
    in t
    in t
    in l
```

Its not critical as the other works, but it still annoying as if you by mistake select the wrong one the dashboard crashes and you have lost all your changes since last save..

Again thanks a lot for looking to my problem!

Esben

**Comment by Slach** [comment]
@hyberdk could you explain how you make PIE Chart visualization? I don't see PIE chart in default grafana7 visualization plugin list

I also tried to reproduce query look like yours
and currently last master works OK
![image](https://user-images.githubusercontent.com/105560/85716870-527f9080-b706-11ea-9fa5-c9c94e36c8f3.png)

**Comment by Slach** [comment]
@hyberdk also the same query from your issue in table format looks good:

![image](https://user-images.githubusercontent.com/105560/85719440-ddfa2100-b708-11ea-9211-4e1a441d1b62.png)

**Comment by Slach** [comment]
I catch it
![image](https://user-images.githubusercontent.com/105560/85746647-0b05fe00-b720-11ea-8b69-50f74df59842.png)

```
  grafana:
    image: grafana/grafana:latest
    environment:
      - GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=vertamedia-clickhouse-datasource
      - GF_INSTALL_PLUGINS=grafana-piechart-panel 1.5.0
```

so error happens inside Pie Chart plugin
look like PieChart can't work with "table" format
see https://github.com/grafana/piechart-panel/issues/113

**Comment by hyberdk** [comment]
Awesome, thanks for investigating this!
