### ISSUE TITLE
plugin shows a wrong version

### ISSUE THREAD

**Issue by adivinho** [Vertamedia/clickhouse-grafana#203]
It was installed the latest plugin version **_2.0.1_** but it's still shown as **_2.0.0_**

![Screenshot_20200622_155339](https://user-images.githubusercontent.com/25184101/85289750-95d8c580-b4a0-11ea-9332-d2a70f093c72.png)

**Comment by Slach** [comment]
@adivinho thanks a lot for reporting

**Comment by adivinho** [comment]
@Slach It looks like you have missed to set the new version here too
dist/plugin.json
![Screenshot_20200623_124238](https://user-images.githubusercontent.com/25184101/85388726-1bb34a00-b54f-11ea-8dba-9fccfcd6de7b.png)
