### ISSUE TITLE
can't install latest version

### ISSUE THREAD

**Issue by Gongruixiao** [Vertamedia/clickhouse-grafana#209]
![image](https://user-images.githubusercontent.com/8455456/85937040-63ace500-b932-11ea-975b-249ee9d347b6.png)

**Comment by Gongruixiao** [comment]
#188 have solve this issue

**Comment by Slach** [comment]
@Gongruixiao please subscribe to https://github.com/grafana/grafana-plugin-repository/pull/656
currently, PR not merged and I trying to reproduce error message on "alert" golang part
