### ISSUE TITLE
Implements sign process and add dist/MANIFEST.txt 

### ISSUE THREAD

**Issue by Slach** [Vertamedia/clickhouse-grafana#212]
look at https://grafana.com/docs/grafana/latest/developers/plugins/sign-a-plugin/
and https://grafana.com/docs/grafana/latest/plugins/plugin-signature-verification/
currently, only "grafana team" plugins can be signed correctly

**Comment by levonet** [comment]
I have same problems with Grafana 7.x docker container.
`t=2020-07-16T16:44:18+0000 lvl=eror msg="Failed to load plugin" logger=plugins error="plugin \"vertamedia-clickhouse-datasource\" is unsigned" pluginPath=/var/lib/grafana/plugins/vertamedia-clickhouse-datasource/dist`

**Comment by Slach** [comment]
@levonet please look to https://github.com/Vertamedia/clickhouse-grafana/#quick-start

apply  changes into grafana.ini
```
[plugins]
allow_loading_unsigned_plugins=vertamedia-clickhouse-datasource
```
or setup environment variable
```
GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=vertamedia-clickhouse-datasource 
```

**Comment by ryn9** [comment]
Has the team submitted for a Community signature per the instructions noted below? [https://grafana.com/docs/grafana/latest/developers/plugins/sign-a-plugin/#sign-a-public-plugin](url)

**Comment by Slach** [comment]
@ryn9 thanks a lot for link, I will make request and prepare signin process related files

**Comment by ryn9** [comment]
Many thanks. Looking forward to getting this signed :)

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by levonet** [comment]
@Slach When to expect a new version?

**Comment by Slach** [comment]
@levonet couple of weeks
i need resolve another issues and implements some new functions
