### ISSUE TITLE
Support extra filtering query

### ISSUE THREAD

**Issue by Civil** [Vertamedia/clickhouse-grafana#22]
I think it's easier to explain what I mean by example.

We are trying to store graphite data in clickhouse, but because if clickhouse's nature we need to construct our queries in something like that:
```
SELECT Path, Value, Time from graphite where Path IN ('path1', 'path2', 'path3')
```
Those 'path1', 'path2' stored in clickhouse in another table.

What we do now:
select groupUniqArray(Path) from graphite_tree where Path like 'path%'

and then use the results in an 'IN' clause.

With current grafana clickhouse plugin I was unable to find a way to get data and then reuse it in another query.

**Comment by hagen1778** [comment]
Hi @Civil 
Try to use template variables - http://docs.grafana.org/reference/templating/#adding-a-variable
Using that you will be able to cache those values in variable, for example `$path` and then build query:
`SELECT Path, Value, Time from graphite where Path IN $path` 

Also you can find examples of using template variables here - https://grafana.com/dashboards/2515

**Comment by Civil** [comment]
Ok, thanks. That should work ok as a workaround, but it'll be really nice to have something like that on a graph-level, otherwise I'll end up having a template variable per graph :)

**Comment by hagen1778** [comment]
Hmm, every graph can consist of multiple queries and all of them can be displayed as line or couple of lines. If we add additional query - interface became huge.
And even if we do, what is the difference between additional query and query:
`SELECT Path, Value, Time from graphite where Path IN (select uniqExact(Path) from graphite_tree where Path like 'path%')`
The performance must be the same or even better for latter option.

**Comment by Civil** [comment]
At this moment ```where Path IN ( select ... )``` causes a full table scan always. If you specify arbitrary list of paths, query will use indexes.

As an example:
```
:) Select distinct Path from graphite_tree WHERE Path like 'carbon.agents.clickhouse-00%.tcp.metricsReceived'

SELECT DISTINCT Path
FROM graphite_tree
WHERE Path LIKE 'carbon.agents.clickhouse-00%.tcp.metricsReceived'

┌─Path────────────────────────────────────────────────────────────────┐
│ carbon.agents.clickhouse-001.tcp.metricsReceived │
│ carbon.agents.clickhouse-002.tcp.metricsReceived │
└─────────────────────────────────────────────────────────────────────┘

2 rows in set. Elapsed: 0.053 sec. Processed 893.25 thousand rows, 95.52 MB (16.92 million rows/s., 1.81 GB/s.)

:) SELECT count() FROM graphite WHERE Path IN ('carbon.agents.clickhouse-001.tcp.metricsReceived', 'carbon.agents.clickhouse-002.tcp.metricsReceived')

SELECT count()
FROM graphite
WHERE Path IN ('carbon.agents.clickhouse-001.tcp.metricsReceived', 'carbon.agents.clickhouse-002.tcp.metricsReceived')

┌─count()─┐
│    6287 │
└─────────┘

1 rows in set. Elapsed: 0.107 sec. Processed 2.28 million rows, 212.38 MB (21.30 million rows/s., 1.99 GB/s.)

:) SELECT count() FROM graphite WHERE Path IN ( Select distinct Path from graphite_tree WHERE Path like 'carbon.agents.clickhouse-00%.tcp.metricsReceived' )

SELECT count()
FROM graphite
WHERE Path IN
(
    SELECT DISTINCT Path
    FROM graphite_tree
    WHERE Path LIKE 'carbon.agents.clickhouse-00%.tcp.metricsReceived'
)

Ok.
Query was cancelled.

0 rows in set. Elapsed: 23.471 sec. Processed 4.10 billion rows, 608.36 GB (174.59 million rows/s., 25.92 GB/s.)
```

**Comment by hagen1778** [comment]
I see now. Seems like an old CH problem which is promised for being fixed for a year already :-)
Adding an additional query field which must be executed before the main query/queries looks very tricky. Especially when this additionally query used only for one purpose - to avoid old bug in CH.
However I don't see clear solution right now. This issue will be open for other users in case of new ideas

**Comment by Civil** [comment]
That's no a bug, it's by design :)

**Comment by hagen1778** [comment]
I thought it's all about this issue - https://github.com/yandex/ClickHouse/issues/687
