### ISSUE TITLE
Problem with alerts with multiple lines (group by)

### ISSUE THREAD

**Issue by oleg-savko** [Vertamedia/clickhouse-grafana#230]
When I try to add alerts for graph with multiple lines with group by, its seems like try to parse all columns to float and throw exception when parse label:

**Example query:**

```
SELECT
    $timeSeries as t,
    splitByChar('?', host)[1] as h,
    quantile(0.95)(request_time)
FROM $table
WHERE $timeFilter
GROUP BY t, h
ORDER BY t, h
```

**Throw exception:**

`"tsdb.HandleRequest() error rpc error: code = Unknown desc = unable to parse value /client-area/registration/route/UPLOAD for 'h': strconv.ParseFloat: parsing "/client-area/registration/route/UPLOAD": invalid syntax"`

**Expected behavior:** check alert for every line individually and not try to parse labels to float

**Comment by Slach** [comment]
@oleg-savko, thanks for reporting, do you use time Series format or table Format for your query?

**Comment by oleg-savko** [comment]
I use Time Series format.

**Comment by Slach** [comment]
@oleg-savko 

as a quick workaround
you can try use following macros
```
$columns(
    splitByChar('?', host)[1] as h,
    quantile(0.95)(request_time)
) FROM $table
WHERE $timeFilter
```

I going fix your issue tomorrow

**Comment by oleg-savko** [comment]
@Slach Great! Thank you very much!)
