### ISSUE TITLE
I do not see the installed plugin in the list of plugins

### ISSUE THREAD

**Issue by ponikrf** [Vertamedia/clickhouse-grafana#235]
I installed the new grafane version 7.0.6 on ubuntu 20.04, all according to instructions.
```
grafana-cli plugins install vertamedia-clickhouse-datasource
service grafana-server restart
```
But I don't see the clickhouse plugin list

I installed random plug-ins and I see them on the list.

I went to see the folder `/var/lib/grafana/plugins` here.

<img width="529" alt="Снимок экрана 2020-07-12 в 11 57 33" src="https://user-images.githubusercontent.com/3146693/87242598-e0fa4e80-c436-11ea-8afa-447c708f821f.png">

SimpleJson and JSON  is on the plugin list, but clickhouse is missing.

There were no such problems before, and everything started to work at once.

**Comment by Slach** [comment]
@ponikrf thanks you for reporting, 
did you try to add 
environment variable:
```
GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=vertamedia-clickhouse-datasource 
```

or change grafana.ini settings
```
[plugins]
allow_loading_unsigned_plugins=vertamedia-clickhouse-datasource
```
?

Unfortunately, grafana currently doesn't support worked signing method for community plugins
https://community.grafana.com/t/how-to-create-a-signed-backend-plugin/30068/2

**Comment by ponikrf** [comment]
Thank you, it really works (I changed grafana.ini). It's weird that the other Unsigned plug-ins showed up right away, it caused me questions.

**Comment by Slach** [comment]
these plugins don't support "alerts" backend functionality

**Comment by sunyongsheng112** [comment]
it helps me too ~
