### ISSUE TITLE
Macros $interval not correct parse

### ISSUE THREAD

**Issue by oleg-savko** [Vertamedia/clickhouse-grafana#238]
When use custom interval (variable with type Interval) macros $interval not correct parsed.

In docs said that it should parsed to seconds:
_$interval - replaced with selected "Group by a time interval" value (as a number of seconds)_

but it doesnt.

**plugin version**: 2.0.1

**Example artificial:**
table:

```
create table mx_master.test_interval (
    d DateTime,
    x UInt32
) engine = Null;
```

query:

```
SELECT
    $timeSeries as t,
    count(x) * $interval
FROM $table t
where $timeFilter
GROUP BY t
ORDER BY t

```
parsed to:
`
SELECT     (intDiv(toUInt32(d), 600) * 600) * 1000 as t,     count(x) * 10m FROM mx_master.test_interval t where d >= toDateTime(1594047643) GROUP BY t ORDER BY t`

**expected result:**
`SELECT     (intDiv(toUInt32(d), 600) * 600) * 1000 as t,     count(x) * 600 FROM mx_master.test_interval t where d >= toDateTime(1594047643) GROUP BY t ORDER BY t`

**Comment by Slach** [comment]
;) as we figure out in telegram,
there is $interval is not a macro,  it's a template variable with the same name as macro
and this template variable has type "Interval"

unfortunately, grafana core doesn't pass grafana specific template variable type  to plugin during replacement

so, as workaround we should change variable type from "Interval" to "Query"
and use following SQL query for clickhouse datasource

```sql
SELECT (arrayJoin(variable) as x).1 AS __text, x.2 AS __value
FROM (
  SELECT
    arrayMap((x, y) -> (x, y),
        splitByChar(',', '1m,10m,30m,1h,6h,12h,1d,7d,14d,30d'),
        splitByChar(',', '60,600,1800,3600,21600,43200,86400,604800,1209600,2592000')
    ) AS variable
)
```
