### ISSUE TITLE
Can't use $unescape($column) in SELECT request when $column is multiple-value variable

### ISSUE THREAD

**Issue by wordsappadmin** [Vertamedia/clickhouse-grafana#245]
Plugin has example in Show Help:
> $unescape - unescapes variable value by removing single quotes.
>             Used for multiple-value string variables: "SELECT $unescape($column) FROM requests WHERE $unescape($column) = 5"
>
When $column is multiple value variable this example don't work.

**Usecase 1**
$column is multiple-value variable  with value 'id'
```
#Template
SELECT $unescape($column) FROM requests WHERE $unescape($column) = 5
#Generated SQL
SELECT [id] FROM requests WHERE [id] = 5
```
**Usecase 2**
$columns is multiple-value variable with two values: 'date', 'id'
```
#Template
SELECT $unescape($columns) FROM requests
#Generated SQL
SELECT [date,id] FROM requests
```

The question is how to remove brackets [] from multiple-value variable?

Grafana v7.1.0 (8101355285)
vertamedia-clickhouse-datasource 2.0.2

**Comment by Slach** [comment]
simple workaround
use `${columns:csv}`
instead of `$unescape($columns)`
