### ISSUE TITLE
Wrong $timeFilter expansion

### ISSUE THREAD

**Issue by Perlovka** [Vertamedia/clickhouse-grafana#25]
When grafana time selector is set for example to 'Yesterday' (2017-11-18 00:00:00 to 2017-11-18 23:59:59), 'WHERE $timeFilter' is expanded to:

`WHERE event_date BETWEEN toDate(1510963200) AND toDate(1511049600) AND event_time BETWEEN toDateTime(1510963200) AND toDateTime(1511049600)`

so event_date will be from 18-11-2017 to 19-11-2017 and event_time will be from 18-11-2017 00:00:00 to 19-11-2017 00:00:00 inclusive.

The right part of the time expression should be either exclusive or value of timestamp decreased by 1 second.

**Comment by hagen1778** [comment]
Hi @Perlovka 
Pls see https://github.com/Vertamedia/clickhouse-grafana/releases/tag/1.2.2

**Comment by Perlovka** [comment]
In 1.2.2 some files are missing:
```
partials/query.editor.html
partials/query.options.html
```
Can't edit queries ;)

And time selection problem still persist. When time range is set as full period (e.g. now-10m/m - now-10m/m), time selector tooltip shows (2017-11-20 11:35:00 - 2017-11-20 11:35:59) but expanded time query is (2017-11-20 11:35:00 - 2017-11-20 11:36:00) inclusive

**Comment by hagen1778** [comment]
Indeed, I forgot to commit copied to src `query.editor.html`
`query.options.html` is dropped 

> And time selection problem still persist
I believe that it's just a bad release and cached files. Pls, try https://github.com/Vertamedia/clickhouse-grafana/releases/tag/1.2.3

**Comment by Perlovka** [comment]
Perfect! Thank you )
