### ISSUE TITLE
Several string->number casting issues

### ISSUE THREAD

**Issue by negbie** [Vertamedia/clickhouse-grafana#254]
1) https://github.com/grafana/grafana/issues/26606
2) String +4912345 will be shown in table panel as 4912345

**Comment by Slach** [comment]
@negbie thanks for reporting
did you try "2e11" in table plugin with other SQL datasource like a postgresql\mysql?

**Comment by Slach** [comment]
@negbie look like this is not clickhouse-grafana related issue, postgresql + table also interpret "2e1" as numeric
![image](https://user-images.githubusercontent.com/105560/88517587-7e917880-d008-11ea-8773-de7911a1a99b.png)

I think this is more global issue as we think

look like
JSON spec, interpret string "2e1" always as numeric
https://www.json.org/json-en.html

**Comment by negbie** [comment]
Hi @Slach thank you very much for looking into this that quickly. I opened it first in Grafana but then I wasn't 100% sure so I opened it here too. Yes I could reproduce both cases (32E11 and +123123) aswell for Postgresql datasource.
