### ISSUE TITLE
Querybuilder has a problem with strings which contain `$rate` and `From` in field names

### ISSUE THREAD

**Issue by negbie** [Vertamedia/clickhouse-grafana#256]
In Grafana I have a template variable $UserName and I put following statement into the Querybuilder

```
$rate(countIf(StatusCode='200') AS Success, countIf(StatusCode!='200') AS Fail) FROM $table
WHERE Direction in ($UserDirection)
$conditionalTest(AND (FromUser like '%$UserName%' or ToUser like '%$UserName%'),$UserName)
```

This produces following wrong query:
`SELECT t, Success/runningDifference(t/1000) SuccessRate, Fail/runningDifference(t/1000) FailRate FROM ( SELECT (intDiv(toUInt32(CallTime), 1) * 1) * 1000 AS t, countIf(StatusCode = '200') AS Success, countIf(StatusCode != '200') AS Fail FromUser like '%bob%' or ToUser like '%bob%')  WHERE CallTime BETWEEN toDateTime(1595870047) AND toDateTime(1595870349) GROUP BY t ORDER BY t)`

If I change the conditionalTest from:
`$conditionalTest(AND (FromUser like '%$UserName%' or ToUser like '%$UserName%'),$UserName)`
To something like:
`$conditionalTest(AND (ToUser like '%$UserName%' or ToUser like '%$UserName%'),$UserName)`

Querybuilder produces the right query:
`SELECT t, Success/runningDifference(t/1000) SuccessRate, Fail/runningDifference(t/1000) FailRate FROM ( SELECT (intDiv(toUInt32(CallTime), 1) * 1) * 1000 AS t, countIf(StatusCode = '200') AS Success, countIf(StatusCode != '200') AS Fail FROM cdrmon.call_log WHERE CallTime BETWEEN toDateTime(1595870018) AND toDateTime(1595870320) AND Direction in (['incoming'])  AND (ToUser like '%bob%' or ToUser like '%bob%')  GROUP BY t ORDER BY t)`

**Comment by negbie** [comment]
Just to make sure it's not because of the conditionalTest statement I've tried this statement:

```
$rate(countIf(StatusCode='200') AS Success, countIf(StatusCode!='200') AS Fail) FROM $table
WHERE FromUser='bob'
```
Which still produces following wrong query:
`SELECT t, Success/runningDifference(t/1000) SuccessRate, Fail/runningDifference(t/1000) FailRate FROM ( SELECT (intDiv(toUInt32(CallTime), 1) * 1) * 1000 AS t, countIf(StatusCode = '200') AS Success, countIf(StatusCode != '200') AS Fail FromUser='bob' WHERE CallTime BETWEEN toDateTime(1595870528) AND toDateTime(1595870830) GROUP BY t ORDER BY t)`

**Comment by negbie** [comment]
Did some more tests and it seems that this happens only in combination with the $rate funciton

**Comment by Slach** [comment]
@negbie  thanks a lot for reporting, i will fix it ASAP

**Comment by Slach** [comment]
@negbie 
could you check the latest `master` version?

**Comment by negbie** [comment]
Wow you are fast! Thanks a lot! I will test it just after lunch break and report back!

**Comment by negbie** [comment]
@Slach works, thank you very much!
