### ISSUE TITLE
multiple template variable contatenation

### ISSUE THREAD

**Issue by Dino1010** [Vertamedia/clickhouse-grafana#258]
Hi,
Using  clickhouse-grafana source 
I need concat multiple variable  like  concat (area,ip,'-')     area,ip both variable
I am trying to:
i find concat(arr[, separator]) function but it's fail!
 $columns(concat([area,ip,'-']) ,sum(inbandwidth)  as carton, ) FROM $table

**Comment by Slach** [comment]
@Dino1010 could you provide some details what happens?

**Comment by Slach** [comment]
@Dino1010 does this issue still relevant for you? or can I close it?

**Comment by Dino1010** [comment]
> @ Dino1010如果`area`和`ip`它是一个grafana模板变量
> 可能尝试以下查询：
> 
> ```
> $columns( ${area:csv}-${ip:csv}, sum(inbandwidth) AS carton) FROM $table
> ```
> 
> ？

**Comment by Slach** [comment]
@Dino1010 did you try the latest `master` version?

**Comment by Dino1010** [comment]
@Slach  i use 1.9.5 .if latest master version fix this Issues,I am very willing to try it.

**Comment by Slach** [comment]
@Dino1010 
```
$columns( "${area:csv}-${ip:csv}", sum(inbandwidth) AS carton) FROM $table
```
please check latest `master` version also it should works in 1.9.5
if not
please click GeneratedSQL and share in this issue

**Comment by Dino1010** [comment]
it is broken.
<img width="939" alt="Snipaste_2020-08-17_16-08-12" src="https://user-images.githubusercontent.com/48425373/90379552-72e81d80-e0ad-11ea-8bca-0b46f3481999.png">
<img width="809" alt="Snipaste_2020-08-17_16-24-30" src="https://user-images.githubusercontent.com/48425373/90379564-767ba480-e0ad-11ea-9382-3919d75bd203.png">
<img width="1694" alt="Snipaste_2020-08-17_17-13-56" src="https://user-images.githubusercontent.com/48425373/90379568-77acd180-e0ad-11ea-9d4d-90db90c2bd55.png">

**Comment by Slach** [comment]
@Dino1010 could you try 
```
$columns( concat( ${cndId}, '-', ${streamname}) AS key, sum(inbandwidth) AS carton) FROM $table
```
?
