### ISSUE TITLE
query with variable generate bad clickhouse sql

### ISSUE THREAD

**Issue by bigHave** [Vertamedia/clickhouse-grafana#259]
**grafana version: v6.7.4
clickhosue-grafana version: 2.0.2**

In my panel, I set a variable named type:
![image](https://user-images.githubusercontent.com/9249583/88669594-aa9b1f80-d116-11ea-8ace-dd66b8a7f86a.png)

then I add this variable to query like this:
![image](https://user-images.githubusercontent.com/9249583/88669821-f51c9c00-d116-11ea-9bcc-518233801565.png)

which generated sql like this:
![image](https://user-images.githubusercontent.com/9249583/88670127-46c52680-d117-11ea-9c40-9030a36bb2ab.png)

more specifically: "type in ([1,2,3,4])" ,and this caused a bad clickhouse query request:
![image](https://user-images.githubusercontent.com/9249583/88670337-855ae100-d117-11ea-826b-249ee4144fb3.png)

in my point of view, "type in ([1,2,3,4])" should be "type in (1,2,3,4)" , which does not contain "[]"

appreciated for any solutions!

**Comment by Slach** [comment]
duplicated with https://github.com/Vertamedia/clickhouse-grafana/issues/252
could you try to latest `master` version?
or subscribe https://github.com/grafana/grafana-plugin-repository/pull/690 and wait when 2.0.4 will release on Grafana plugin repository

**Comment by bigHave** [comment]
I'll give a try. thx for reply
