### ISSUE TITLE
Compatibility with Grafana 7.1.1 

### ISSUE THREAD

**Issue by alexorekhov** [Vertamedia/clickhouse-grafana#260]
After upgrading Grafana to ver. 7.1.1 plugin stop working and on datasource page, I see the following error:

![image](https://user-images.githubusercontent.com/44675562/88690936-e2996700-d104-11ea-9569-5282c18e785d.png)

Tried to reinstall the plugin, but it didn't help. Did I miss something or it's an issue that should be fixed?

Thanks in advance.

**Comment by Slach** [comment]
please read https://github.com/Vertamedia/clickhouse-grafana#grafana-7x-setup-notes
so, for properly setup you need change configuration option
```
[plugins]
allow_loading_unsigned_plugins=vertamedia-clickhouse-datasource
```
or setup environment variable
```
GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=vertamedia-clickhouse-datasource 
```
duplicated with 
https://github.com/Vertamedia/clickhouse-grafana/issues/243
https://github.com/Vertamedia/clickhouse-grafana/issues/235
https://github.com/Vertamedia/clickhouse-grafana/issues/188
