### ISSUE TITLE
update to grafana7.0 & clickouse-garfana 2.0.2 query error

### ISSUE THREAD

**Issue by jinlongwang** [Vertamedia/clickhouse-grafana#266]
## environment
grafana： 7.0
clickhouse plugin： 2.0.2

## issue
![image](https://user-images.githubusercontent.com/2275120/89278437-af148a80-d678-11ea-9694-225ba58b9bfc.png)
![image](https://user-images.githubusercontent.com/2275120/89278512-c8b5d200-d678-11ea-8070-2857eb6e832e.png)

## Other clues
when i use grafana6.3.4 and clickhouse plugin verison is 1.9.0 , Query no problem

The difference is that the parsed SQL is inconsistent
### right version parsed sql is:
![image](https://user-images.githubusercontent.com/2275120/89279025-74f7b880-d679-11ea-8964-e94bee7f6d07.png)

### error version parsed sql is:
![image](https://user-images.githubusercontent.com/2275120/89279105-90fb5a00-d679-11ea-9987-52a6824cd805.png)

Looks like a problem with ``

So, What should i do? 

Because I want to upgrade grafana version, but the lower version of the clickhouse plug-in does not adapt to grafana 7.0

**Comment by Slach** [comment]
Your screens
hmm, version 1.9.5 should works with grafana 7.0 and grafana 7.1 but contains some bugs, which fixed on 2.0.2 version 

@jinlongwang, could you share original query which you used in Query editor?
your screenshots look like you show generated query after parsing

**Comment by jinlongwang** [comment]
hi, @Slach, there is my  original query
```sql
SELECT
    $timeSeries as t,
    count() as sample_count,
    countIf((status = 0 or status is NULL) AND duration < 3000) / count() as success_3,
    countIf((status = 0 or status is NULL) AND duration < 5000) / count() as success_5,
    countIf((status = 0 or status is NULL) AND duration < 8000) / count() as success_8,
    countIf((status = 0 or status is NULL) AND duration < 10000) / count() as success_10,
    countIf((status = 0 or status is NULL)) / count() as success_20
FROM $table
WHERE
    $timeFilter
    AND(('1' = '$data_version' and data_version is NULL) or('1' <> '$data_version' and data_version = '$data_version'))
    AND cast(app_id as int) in ($app_id)
    AND cast(IF(server_app_id is NULL, '0', server_app_id) as int) in ($server_app_id)
    AND os in ($os)
    AND(('All' IN ($app_version)) OR(app_version IN ($app_version)))
    AND room_type = 0
    AND(role is null OR role IN ($role))
    AND('false' IN ('$use_room_id') OR concat(room_id, '_') IN ($room_id))
GROUP BY t
ORDER BY t
```
and today i found this problem is show on clickhouse plugin version 1.9 and higher

but clickhouse plugin verison 1.6.0 is fine.  

is there any change for parsed $timeSeries ？ 

Why are the quotes parsed on versions 1.9 and higher?

thx！

**Comment by Slach** [comment]
@jinlongwang I tried to reproduce your query on latest `master` version `clickhouse-grafana` plugin
could you suggest what exactly you choose as `table`, `database` and `Сolumn:DateTime` in your query when turn off query-editor?
![image](https://user-images.githubusercontent.com/105560/89417715-7fcd4e80-d748-11ea-85b4-81e12bba8a91.png)

Does it look like `ts/1000`?

and how do you group your data? do you use group by day?

cause on my $timeFilter converts correctly without any quoting
![image](https://user-images.githubusercontent.com/105560/89418490-8c9e7200-d749-11ea-853e-9ebae9b6ec05.png)

also, could you share your query options parameters?
![image](https://user-images.githubusercontent.com/105560/89418599-b6579900-d749-11ea-96fe-c913a6413462.png)

**Comment by Slach** [comment]
@jinlongwang which data type have `ts` field in your table?

**Comment by Slach** [comment]
@jinlongwang is this issue still actual for you? could you help me reproduce it and help you to resolve issue?
Could you please answer to questions above?

**Comment by jinlongwang** [comment]
hi, @Slach, thanks for you help 

## turn off query-editor
![image](https://user-images.githubusercontent.com/2275120/89531690-39005700-d823-11ea-8739-1eb6f99dde87.png)

## query options parameters
![image](https://user-images.githubusercontent.com/2275120/89531823-6baa4f80-d823-11ea-858d-138726c2599a.png)

and I have updated the plugin  version  to 2.0.6， but it's still have this problem
![image](https://user-images.githubusercontent.com/2275120/89532795-ef187080-d824-11ea-8f24-dfc768b69b62.png)

and by the way, why do you have the `alert` tab?
![image](https://user-images.githubusercontent.com/2275120/89532997-44548200-d825-11ea-92e4-9b2bcb54c788.png)

**Comment by jinlongwang** [comment]
@Slach i found a workaround
![image](https://user-images.githubusercontent.com/2275120/89534206-28ea7680-d827-11ea-9d33-3c289e368104.png)
![image](https://user-images.githubusercontent.com/2275120/89534398-6c44e500-d827-11ea-8398-d809b7cc8174.png)

**Comment by Slach** [comment]
@jinlongwang thanks a lot, a can reproduce your issue
I will fix it ASAP

**Comment by Slach** [comment]
@jinlongwang alerts became just for copy existing dashboard

your issue became from 1.9.0 as part of ConditionalTest functionality in https://github.com/Vertamedia/clickhouse-grafana/commit/c6dd0a564393e9fb9207031aaa3d3a5e464a0ab5
for https://github.com/Vertamedia/clickhouse-grafana/pull/122

I can fix it

**Comment by Slach** [comment]
@jinlongwang could you install and check the latest `master` version of plugin?

**Comment by jinlongwang** [comment]
@Slach 2.0.7 is ok! thank you!
