### ISSUE TITLE
Allow backend parsing timestamp as Date or DateTime type not only UInt64

### ISSUE THREAD

**Issue by negbie** [Vertamedia/clickhouse-grafana#268]
When using toStartOfHour() Grafana Alert query will throw this error:

error:"tsdb.HandleRequest() error rpc error: code = Unknown desc = unable to parse timestamp with alias=t value=2020-08-04 16:00:00 error=strconv.ParseInt: parsing "2020-08-04 16:00:00": invalid syntax"

**Comment by Slach** [comment]
Hello @negbie 
I tried to figure out with this issue

Unfortunately, only grafana `Graph` panel supports "alerts" tab, 
but this plugin requires the first column as JavaScript timestamp with seconds + milliseconds  (UInt64 in golang types, Unix timestamp * 1000)

So, even we allow parsing ClickHouse DateTime \ Date on golang side without convert toUInt64, we will fail on JavaScript side and have empty graph without data
so use $timeseries macros to directly convert `toUInt64( ... )` on SQL queries it's a best approach

**Comment by negbie** [comment]
Hi Slach, thank you very much for looking into this! Ok makes sense and I think it's not a big deal. I've just stumbled over this because I tried clickhouse for the first time and wasn't familiar with all available conversion funktions. toUInt64( ... ) * 1000 is totally fine for me.
