### ISSUE TITLE
Queries from single dashboard stopped running in parallel since 2.0.3

### ISSUE THREAD

**Issue by gloyka** [Vertamedia/clickhouse-grafana#272]
We have some dashboards with multiple clickhouse panels. Queries from dashboard use to be running in paralell.

They are executed consequentially now, since 2.0.3 version. One after another.
It seriously affects full dashboard loading time.

before 2.0.3:
![before_2 0 3](https://user-images.githubusercontent.com/9253469/89655814-4ffe8200-d8d3-11ea-9f4a-0534149ced00.png)

since 2.0.3:
![since_2 0 3](https://user-images.githubusercontent.com/9253469/89655818-512faf00-d8d3-11ea-8329-977c6e37722a.png)

**Comment by Slach** [comment]
@gloyka thanks a lot for reporting
I'm rollback some kind of changes in https://github.com/Vertamedia/clickhouse-grafana/commit/8e384d268644994983bf1bf42f2ee49f826e6e1b ASAP

**Comment by Slach** [comment]
@gloyka could you please check the latest `master` version?
![image](https://user-images.githubusercontent.com/105560/89673590-0ed09700-d900-11ea-9ded-76598dca2e84.png)

**Comment by gloyka** [comment]
@Slach it works well now. Thank you!
