### ISSUE TITLE
New versions in Grafana plugins

### ISSUE THREAD

**Issue by evgmoskalenko** [Vertamedia/clickhouse-grafana#278]
Hello, could you tell please, when will new versions appear in Grafana plugins - https://grafana.com/grafana/plugins/vertamedia-clickhouse-datasource

**Comment by Slach** [comment]
please subscribe to
https://github.com/grafana/grafana-plugin-repository/pull/690
and ask grafana team to merge this PR

**Comment by evgmoskalenko** [comment]
Thanks.. :-)
