### ISSUE TITLE
no generate select 2.1

### ISSUE THREAD

**Issue by igor9292** [Vertamedia/clickhouse-grafana#284]
systax error: failed at position 1(line 1, col) 
no generate select 

$columns(
  substring(concat(JobName as JobName,' # ' , Metrics.MetricName as Metric), 1, 50) as JobSource, 
  sum(Metrics.Value) as Kafka_lag_max) 
FROM $table
ARRAY JOIN Metrics

**Comment by Slach** [comment]
@igor9292 thanks for reporting, I confirm, ARRAY JOIN doesn't parse properly cause the parser to expect `ON|USING` keyword after `JOIN Metrics` ... 

could you suggest
do you have one `$table`
which contains `Metrics` field Nested structure?

**Comment by Slach** [comment]
@igor9292 could you check your query with the latest `master` version and share results and reopen this issue if still reproduce?

**Comment by igor9292** [comment]
it's work

**Comment by Slach** [comment]
nice to hear it ;)
