### ISSUE TITLE
adding datasource need to login but the clickhouse or grafana's username-password both failed

### ISSUE THREAD

**Issue by yishanchuan** [Vertamedia/clickhouse-grafana#287]
Hi, guys. I met a problem during adding clickhouse datasource .
When I click the "save and test", a confirm form appeared. 
Then I tried to using clickhouse profile to fill the username and password input. I get the following error warning:

![屏幕截图_20200904104816](https://user-images.githubusercontent.com/16149816/92194462-4bf75d00-ee9d-11ea-986f-05ac2ddb26e8.png)

It is the same as that I input grafana username and password. I search almost answer, but no solution. 
Thanks for any reply.

**Comment by Slach** [comment]
@yishanchuan could share more detail?
could you explain how exactly did you try to add `clickhouse` data source?
do you use Access: "Browser" or "Server"?
which `schema` (http, https), `host` and `port`  did you use?
![image](https://user-images.githubusercontent.com/105560/92197173-7390fa00-ee8a-11ea-91bd-ccc1f42968ac.png)
by default clickhouse support `http://` schema on `8123` port, and `https://` schema for 8443 port

also, how do you ensure that you try to use the right username and password?
by default clickhouse allow login with `default` username without password,  restricted only from `localhost` (grafana should install to the same server as clickhouse) or inside same docker network if you use docker installation)

**Comment by yishanchuan** [comment]
> @yishanchuan could share more detail?
> could you explain how exactly did you try to add `clickhouse` data source?
> do you use Access: "Browser" or "Server"?
> which `schema` (http, https), `host` and `port` did you use?
> ![image](https://user-images.githubusercontent.com/105560/92197173-7390fa00-ee8a-11ea-91bd-ccc1f42968ac.png)
> by default clickhouse support `http://` schema on `8123` port, and `https://` schema for 8443 port
> 
> also, how do you ensure that you try to use the right username and password?
> by default clickhouse allow login with `default` username without password, restricted only from `localhost` (grafana should install to the same server as clickhouse) or inside same docker network if you use docker installation)

yes, I use http://10.60.25.130:8123 and Server (default)

**Comment by yishanchuan** [comment]
I use tabix to connect clickhouse , the same username and password can access that.

**Comment by Slach** [comment]
@yishanchuan how do you install Grafana? is it the same server with the same IP where install clickhouse or is it the separate server with different IP? 

did you check Basic auth checkbox? 
![image](https://user-images.githubusercontent.com/105560/92199414-873f5f00-ee90-11ea-9a51-98007d2fac98.png)
or do you use Yandex Cloud authorization?
![image](https://user-images.githubusercontent.com/105560/92199455-a938e180-ee90-11ea-9058-909888a210cf.png)

**Comment by yishanchuan** [comment]
Thanks a lot! It's work!
