### ISSUE TITLE
how to show date or month count

### ISSUE THREAD

**Issue by Brucecarl** [Vertamedia/clickhouse-grafana#290]
Hi,I wanna count data group by date or month,but the graph time x-axis cannot show in date and month ,how to do that?

**Comment by Slach** [comment]
@Brucecarl could you share your current SQL query?
grafana expect for time series data UInt64 field which represent unix timestamp in ms
maybe you need try to use `toUInt64(toStartOfMonth(your_datetime_filed))*1000 AS month`

**Comment by Slach** [comment]
@Brucecarl issue is relevant for you? or suggestion with toUInt is enough?
