### ISSUE TITLE
DateTime64 Support

### ISSUE THREAD

**Issue by chr-istoph** [Vertamedia/clickhouse-grafana#292]
Thanks for this great plugin!

DateTime64 is the preferred Clickhouse data type for sub-second precision timestamps:
https://clickhouse.tech/docs/en/sql-reference/data-types/datetime64/

Is DateTime64 support on the horizon for this plugin? 

Namely
- Time range selection in the query builder (e.g. `WHERE Timestamp BETWEEN toDateTime64(1598007073,3) AND toDateTime64(1598028056,3)`)
- Display of sub-second precision return time series (e.g. sensor values logged at 10 Hz)

**Comment by Slach** [comment]
@chr-istoph 
according to https://github.com/grafana/grafana/issues/3035
grafana itself supports only milliseconds resolution right now

so, for quick workaround you can try to use something like that
`SELECT intDiv(toUInt64(datetime64_precision_3_field),$__interval_ms) AS t ...` and  
`WHERE t BETWEEN toDateTime64($__from,3) AND toDateTime64($__to,3))`
with grafana-clickhouse

**Comment by chr-istoph** [comment]
@Slach 
Thanks for the pointer 👍 
This works a treat:

- `intDiv(toFloat64(datetime64_field)*1000, $__interval_ms) * $__interval_ms) as t`

- `WHERE t BETWEEN toDateTime64($__from,3) AND toDateTime64($__to,3))`

**Comment by mikhno-s** [comment]
Hey, similar ussue.

I have changed timestamp column type to DateTime64 and found out that my dashboard stopped to work. 
Is it complex task to add DateTime64 as allowed column type to search?

it should be interpolated in row query into workaround as in upper messages.

Or if it is already done - how can I chose my DateTime64 field as a timestamp column?

**Comment by kakvablyat** [comment]
+1

**Comment by Slach** [comment]
@chr-istoph @kakvablyat @mikhno-s could you check latest `master` version?

**Comment by Slach** [comment]
@chr-istoph @kakvablyat @mikhno-s 
you should change datetime column type to Column:DateTime64 in your queries

![image](https://user-images.githubusercontent.com/105560/97983645-68f5d100-1df7-11eb-8425-4acc27e5c155.png)

**Comment by mikhno-s** [comment]
Cannot save that parameter. It returns to DateTime.

However, this does not work for me 
```SQL
...
intDiv(toFloat64(datetime64_field)*1000, $__interval_ms) * $__interval_ms) as t
...
WHERE t BETWEEN toDateTime64($__from,3) AND toDateTime64($__to,3))
...
```

The only way I made it work -
```SQL
WHERE $dateTimeCol BETWEEN toDateTime64($__from/1000, 3) AND toDateTime64($__to/1000,3)
```

**Comment by mikhno-s** [comment]
Also, possible solution for grafana > v7.1.2
```SQL
WHERE $dateTimeCol BETWEEN toDateTime64(${__from:date:seconds}, 3) AND toDateTime64(${__to:date:seconds},3)
```

**Comment by Slach** [comment]
@mikhno-s @chr-istoph @kakvablyat could you check latest `master` again?
I added support DateTime64 to $timeFilter and $timeSeries
please look to https://github.com/Vertamedia/clickhouse-grafana/blob/master/docker/grafana/dashboards/test_datetime64_support.json for dashboard example

**Comment by Slach** [comment]
@mikhno-s could please try to use latest `master` version
![image](https://user-images.githubusercontent.com/105560/98017536-3660ce00-1e21-11eb-95cd-d5388cf2bd21.png)
and look to https://github.com/ClickHouse/ClickHouse/issues/16655

**Comment by vbichov** [comment]
@Slach  doesn't work:
the generated sql for $timeFilter with min step of 60s is:
(intDiv(toFloat32(timestamp) * 1000, 60) * 60) as t

while it should be:
(intDiv(toFloat32(timestamp) * 1000, 600) * 600) as t

**Comment by Slach** [comment]
@vbichov which DateTime64 type do you use? `DateTime64(3)` or `DateTime64(6)` ?

**Comment by mikhno-s** [comment]
@Slach DateTime64(3)

**Comment by Slach** [comment]
@mikhno-s , @vbichov could you try latest `master` again?

**Comment by vbichov** [comment]
Works for me - thanks.
