### ISSUE TITLE
Poor performance when using JSON format

### ISSUE THREAD

**Issue by Serrous** [Vertamedia/clickhouse-grafana#293]
Hello, colleagues
At the moment we are trying to transfer our monitoring system to the Clickhouse + Grafana bundle and we are faced with poor performance.
The fact is that we have a large number of servers and metrics and we need to be able to visualize them for all servers in our cluster. We have uploaded test data to Clickhouse such as RAM, CPU, SysUtil, UserUtil and the like. When we make a selection from, for example, DBeaver, we get the result in 1.5 seconds (about 1.4 million rows, FORMAT == TabSeparatedWithNamesAndTypes). But when we render them in Grafana - the data on the Clickhouse side is requested in JSON format (which, as I understand it, is automatically substituted into the request by your plugin) and the processing takes about 20 seconds. This is very long considering that we only made 1 dashboard. Apparently - time is spent on generating and parsing JSON data.

Is there a way to request non-JSON data for rendering in Grafana?
Example of our request for Grafana (query.log from Clickhouse side):

`
SELECT
    (intDiv(toUInt32(UNIXTIME), 60) * 60) * 1000 as t,
    USRUTIL,
    SYSUTIL,
    IOWAIT
FROM ZBC_METRICS.TEST6
WHERE
    UNIXTIME BETWEEN toDateTime(1595797200) AND toDateTime(1598129999) AND isNotNull(USRUTIL)
ORDER BY t **FORMAT JSON**
`
With best regards.

**Comment by Slach** [comment]
@Serrous your SQL query from `query_log` looks weird 
1) why you need data for one month data (from 2020-07-26 to 2020-08-22), but grouped only for 60s interval?
2) why SQL query doesn't contains `GROUP BY t` clause?

could you share your original SQL query which you used inside grafana graph panel? 
do you use $timeSeries or other macros in your query?

1.4kk rows it's no good idea in any case

**Comment by Serrous** [comment]
@Slach 

Yes, you right, this is my stupid mistake - I was requesting the data I needed incorrectly. I rewrote the query where I only get 3000 lines of output for all servers and now it works about 40ms)
You can close and delete this post - it is not a problem for plugin.
