### ISSUE TITLE
Failed to Add Data Source: HTTP Error Bad Gateway

### ISSUE THREAD

**Issue by Hukuta** [Vertamedia/clickhouse-grafana#295]
![Selection_139](https://user-images.githubusercontent.com/3100053/95723938-667fdb80-0c7e-11eb-87b4-685fa8085b5c.png)

![Selection_140](https://user-images.githubusercontent.com/3100053/95723984-75ff2480-0c7e-11eb-9576-71c2deec0f47.png)
![Selection_141](https://user-images.githubusercontent.com/3100053/95724003-7c8d9c00-0c7e-11eb-92e9-eaa16bcb2cf1.png)

ClickHouse server version 20.9.3
Grafana v7.2.1

**Comment by Slach** [comment]
please use localhost:8123 instead of localhost:9000
plugin use http/https protocol for connection

**Comment by Hukuta** [comment]
I have the same Error message when using 8123 port

**Comment by Hukuta** [comment]
I'm not using CHProxy ( it marked as optional in readme )

**Comment by Slach** [comment]
do you have grafana and clickhouse on the same stateful server? or it's a separate docker containers or Linux machines?

could you run the following command on your grafana server and share the results?
```
wget --user=default --password=YOUR_PASSWORD_FOR_DEFAULT_USER_FOR_GRAFANA -S -O- "http://localhost:8123/?query=SELECT version()"
```

**Comment by Hukuta** [comment]
I realized that CH server crashes after start, sorry to bother. Closed

**Comment by HardRock4Life** [comment]
@Slach 
This is what happens when I run this command on a `clickhouse` docker container:
![image](https://user-images.githubusercontent.com/21273349/132677115-42ec06d2-ff7f-4882-9585-4ba7d9fd6f51.png)

However, this is what happens when I try to run the same command on a `grafana` container
![image](https://user-images.githubusercontent.com/21273349/132677953-af78278c-a29e-4f6c-97f5-c61e417b2883.png)

It feels like `wget` does not exist on it. The attempt to install it is also no good.
![image](https://user-images.githubusercontent.com/21273349/132678071-a6e067c7-ba55-4fec-b8ed-e66bede176d5.png)

**Comment by Slach** [comment]
@Hukuta look like on `grafana` container you have alpine based Linux distro

try to run `apk add --no-cache wget` and replace busybox wget version to full wget

**Comment by HardRock4Life** [comment]
@Slach 
![image](https://user-images.githubusercontent.com/21273349/132678945-16a7986b-a236-4de0-98fd-aab698af69bb.png)

Permission denied...

**Comment by Slach** [comment]
@HardRock4Life 
let's try to 
```
wget -S -O- "http://localhost:8123/?query=SELECT version()&user=YOUR_CLICKHOUSE_USER&password=YOUR_CLICKHOUSE_PASSWORD"
```

**Comment by HardRock4Life** [comment]
```
Connecting to localhost:8123 (127.0.0.1:8123)
wget: can't connect to remote host (127.0.0.1): Connection refused
```

I did this on a grafana container.

**Comment by Slach** [comment]
@HardRock4Life clickhouse container and grafana container have different loopback interfaces and `127.0.0.1` it's not the same IP
please use docker-compose or something else and try to link between containers and connect to IP containers

look to https://github.com/Vertamedia/clickhouse-grafana/blob/master/docker-compose.yaml for example

**Comment by HardRock4Life** [comment]
![image](https://user-images.githubusercontent.com/21273349/132885442-b9e7bd42-3f34-4270-9b9a-3ce000f49d66.png)

I cloned the repository from https://github.com/lmangani/docker-clickhouse-grafana and replaced the ```docker-composer.yaml``` file with the one from the link above. This is the error it outputs now.

**Comment by Slach** [comment]
@HardRock4Life 
look like you don't understand how exactly works docker-compose
sorry, I have no time to explain it deeply

try to
```
git clone  https://github.com/Vertamedia/clickhouse-grafana
cd clickhouse-grafana
docker-compose up -d clickhouse grafana
```

**Comment by UserMMT** [comment]
I met the same error i think you should just add an / at the end of your URL then if you're using access 
    -Server you should try to check if the clickhouse-server is reachable by the server where grafana is install 
    -Browser you should try to check if the clickhouse-server is reachable by your browser using the URL you insert
if so everything should be OK
