### ISSUE TITLE
How to get required template variable expansion?

### ISSUE THREAD

**Issue by ghuname** [Vertamedia/clickhouse-grafana#296]
While I was on plugin version 2.0.2 and clickhouse database version 19.15.4 revision 54426, I had a problem described on https://github.com/Vertamedia/clickhouse-grafana/issues/252.
After upgrading plugin to 2.1.0, one problem vanished, but another showed up.

```
SELECT
    $timeSeries as t,
    count()
FROM $table
WHERE cmts in ('${CMTS:singlequote}')
and fiberNode in ('${FNODE:singlequote}')
and txFreq in (${USChannel})
and bulkId in  ('${BULK_ID:singlequote}')
and resultSeverity in  ($SEVERITY) 
$conditionalTest(AND hasAny(corrGroup,$CORR_GROUP),$CORR_GROUP)
GROUP BY t
ORDER BY t
```

I had the problem with $SEVERITY variable that upgrade to 2.1.0 solved. Now I have a problem with $CORR_GROUP variable.
With 2.0.2 it used to work like this:

```
SELECT
    (intDiv(toUInt32(bulkId), 15) * 15) * 1000 as t,
    count()
FROM pre_eq.pre_eq
WHERE cmts in ('cmts')
and fiberNode in ('fiber_node_name')
and txFreq in (integer_freq)
and bulkId in  ('2020-10-16 09:00:00')
and resultSeverity in  (['highMonitoringFrequency','noActionRequired','immediateActionRequired']) 
 AND hasAny(corrGroup,['corr_group_1','corr_group_2]') 
GROUP BY t
ORDER BY t
```

and now array in hasAny(corrGroup,'corr_group_1','corr_group_2') has gone:

```
SELECT
    (intDiv(toUInt32(bulkId), 15) * 15) * 1000 as t,
    count()
FROM pre_eq.pre_eq
WHERE cmts in ('cmts')
and fiberNode in ('fiber_node_name')
and txFreq in (integer_freq)
and bulkId in  ('2020-10-16 09:00:00')
and resultSeverity in  ('highMonitoringFrequency','noActionRequired','immediateActionRequired') 
 AND hasAny(corrGroup,'corr_group_1','corr_group_2') 
GROUP BY t
ORDER BY t
```

Variable $CORR_GROUP is defined like this:

![image](https://user-images.githubusercontent.com/15207713/96229316-0008ff00-0f97-11eb-9f48-5d71b9ebeb08.png)

For example, one solution would be to change manually:
from `$conditionalTest(AND hasAny(corrGroup,$CORR_GROUP),$CORR_GROUP) `
to `$conditionalTest(AND hasAny(corrGroup,[$CORR_GROUP]),$CORR_GROUP)`

So, I should change this condition in all queries, but I am not sure whether this approach will work with older versions of clickhouse databases.

Please advice what should be the best solution for the problem described.

**Comment by Slach** [comment]
hasAny with [$CORR_GROUP] will work with old versions
```
SELECT version(),hasAny(['test1','test2'],['test1']);

┌─version()──┬─hasAny(['test1', 'test2'], ['test1'])─┐
│ 19.17.10.1 │                                     1 │
└────────────┴───────────────────────────────────────┘
┏━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ version()  ┃ hasAny(['test1', 'test2'], ['test1']) ┃
┡━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│ 19.11.14.1 │                                     1 │
└────────────┴───────────────────────────────────────┘
```

**Comment by ghuname** [comment]
Will this approach be a problem with newer version of clickhouse?

**Comment by Slach** [comment]
no, it should not a problem 
just use `$conditionalTest(AND hasAny(corrGroup,[$CORR_GROUP]),$CORR_GROUP)`
```
┏━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ version() ┃ hasAny(['test1', 'test2'], ['test1']) ┃
┡━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│ 20.8.2.3  │                                     1 │
└───────────┴───────────────────────────────────────┘
```

**Comment by ghuname** [comment]
Thanks
