### ISSUE TITLE
grafana timeout override

### ISSUE THREAD

**Issue by msvihra** [Vertamedia/clickhouse-grafana#297]
At first sorry if this question doesn't belong there.

We are using grafana to show data from clickhouse, which is forwarding queries into chproxy used as proxy in front of clickhouse.
Dashboards are working as intended - but only if i use range for only few days. If i need more data from wider range - two weeks or one month - i am facing timeouts after 60seconds.

I have digged what is causing these timeouts and it looks like that grafana have hardcoded timeout after 60 seconds for http queries.
If i try to select data from my local computer using curl straight to server with [chproxy](https://github.com/Vertamedia/chproxy) - it works. Also i can select data using http request straight into clickhouse server. 

I have find this FR in grafana repo -  https://github.com/grafana/grafana/issues/3168 .Problem is that this FR is still open after 5 years.
My question is, if you faced same problem and what was your solution? Should i use another tool to show statistics from clickhouse? Or can i somehow avoid this timeout? We are using clickhouse as datawarehouse and we sometimes need these wider selects to show more statistics. As i understand clickhouse have no options to optimize heavy selects.

Thanks

**Comment by Slach** [comment]
first of all, 60 seconds is too long for one month date range in ClickHouse

could you share SQL query, CREATE TABLE statements with ENGINE and ORDER BY  \ PARTITION BY ?

**Comment by msvihra** [comment]
Thanks for reply.

Yes it took a long time to finish, but this is not problem. We are performing selects with a lot of GROUP BY and joins to show right data in our graphs. My question was pointing maybe to te point how to modify this timeout inside grafana or plugin itself. I saw in debug logs that grafana is sending **connection close** after 60 seconds, so timeout in chproxy is pretty much useless. We did not observe timeouts when we perform select using curl directly into Chproxy and/or clickhouse http port

**Comment by Slach** [comment]
@msvihra sorry, we can't override grafana default timeout, cause plugin make http request not directly and use grafana backendSrv interface for it 

i spent some time to try to figure out how timeout setup in grafana sources, but without success

so, if you use JOINS and GROUP BY
maybe you query can be improved via dictionaries and dictGet* functions?

**Comment by msvihra** [comment]
@Slach Thanks for reply and follow up.
In this case we should come with another solution

THanks you very much
