### ISSUE TITLE
alert error :"tsdb.HandleRequest() error Could not find executor for data source type: vertamedia-clickhouse-datasource"

### ISSUE THREAD

**Issue by fishdemon** [Vertamedia/clickhouse-grafana#299]
grafana 7.2.2 + clickhouse
For graphs the datasourse is working normally . such as query A can run normally , but alert  for query A is error

```
alert error :"tsdb.HandleRequest() error Could not find executor for data source type: vertamedia-clickhouse-datasource"
```

**Comment by shizhenchina** [comment]
`error:"tsdb.HandleRequest() error rpc error: code = Unknown desc = Get "http://XXXX?query=SELECT%0A++++%28intDiv%28toUInt32%28event_time%29%2C+1%29+%2A+1%29+%2A+1000+as+t%2C%0A++++count%28%29%0AFROM+system.query_log%0A%0AWHERE+event_time+%3E%3D+toDateTime%281604476897%29%0A%0AGROUP+BY+t%0A%0AORDER+BY+t+FORMAT+JSON": net/http: invalid header field name """`
I also reported an error when I used Clickhouse 2.1.0 for alerts

**Comment by Slach** [comment]
@fishdemon @shizhenchina could you share CREATE TABLE statement and dashboard JSON with alerts to help me reproduce issue?

**Comment by shizhenchina** [comment]
> @fishdemon @shizhenchina could you share CREATE TABLE statement and dashboard JSON with alerts to help me reproduce issue?

This is my configuration problem, and I've solved it.

**Comment by Slach** [comment]
@fishdemon could you share CREATE TABLE statements and grafana dashboard JSON to help me reproduce your issue?

**Comment by Slach** [comment]
@fishdemon any news about this issue? It still reproduce for you?

**Comment by Slach** [comment]
@fishdemon feel free to make a comment if you have any news 
if this issue still reproduce for you, I will reopen issue

**Comment by xieziqiang** [comment]
@shizhenchina I have the same problem. Can you tell me how to solve it ? thanks

**Comment by xieziqiang** [comment]
@fishdemon  @shizhenchina I have the same problem. Can you tell me how to solve it ? thanks
