### ISSUE TITLE
ALIAS BY support similar to InfluxDB in Grafana

### ISSUE THREAD

**Issue by koallen** [Vertamedia/clickhouse-grafana#301]
For the InfluxDB queries, there's an ALIAS BY option that allows customizing the alias for each series in the graph (not ALIAS in the query but the ALIAS BY in the query editor). Can similar feature be added to the ClickHouse plugin as well?

**Comment by Slach** [comment]
@koallen could you get more examples or link to documentation references?

**Comment by Slach** [comment]
@koallen maybe `$columns` macro is enough for you?

**Comment by koallen** [comment]
Hi, I'm able to solve my issue with `$columns` together with `concat` (which is a CH function). In case anyone is having the same question, an example query would be

```
$columns(concat("Datacenter: ", dc) AS datacenter, value AS result)
FROM $table
WHERE $timeFilter
```
