### ISSUE TITLE
[Feature Request] Annotation Region Support

### ISSUE THREAD

**Issue by mohnishkodnani** [Vertamedia/clickhouse-grafana#303]
I wanted to add a feature request to add support for annotation regions from clickhouse plugin.
More details are here
[Annotation Regions](https://github.com/grafana/grafana/issues/10589)
It would be great to see deployment job start and end as a region along with the metrics rather than individual events.

**Comment by Slach** [comment]
@mohnishkodnani could you check latest `master` version? feel free reopen issue if you find any bugs
