### ISSUE TITLE
Incorrect time range when choose "last 1hour" in grafana

### ISSUE THREAD

**Issue by DefauIt** [Vertamedia/clickhouse-grafana#304]
Incorrect time range

Local browser TIMEZONE is GMT+3 (2020-11-13 02:45:41)

When time range picked from calendar in grafana using "from day to day", pickups correct date/timestamp

Grafana v7.1.3 (5723d951af)

![screenshot](https://user-images.githubusercontent.com/923816/99010889-ed64f400-255b-11eb-9195-df4c66238b5b.png)

```sql
SELECT toDateTime(1604177999) AS first_date

Query id: aba7fda3-8bd4-44b3-b3d4-019ff2ecfb77

┌──────────first_date─┐
│ 2020-10-31 20:59:59 │
└─────────────────────┘

1 rows in set. Elapsed: 0.002 sec. 
```

```sql
SELECT toDateTime(1604350800) AS second_date

Query id: f514acaa-62e7-4d76-9b99-4b5b602c149b

┌─────────second_date─┐
│ 2020-11-02 21:00:00 │
└─────────────────────┘

1 rows in set. Elapsed: 0.002 sec. 
```

**Comment by Slach** [comment]
@DefauIt could you answer, which time zone you have on your clickhouse server?
also, please disable the `Extrapolate` checkbox in your query editor to skip default extrapolation behavior, maybe it will solve your issue, cause plugin always pass time range as unix timestamp uint32 value

**Comment by DefauIt** [comment]
Disabling the `Extrapolate` checkbox in query editor didn't solved.

clickhouse-server timezone:
```
$ ls -l /etc/localtime 
lrwxrwxrwx 1 root root 33 Jan 12  2020 /etc/localtime -> /usr/share/zoneinfo/Europe/Moscow
```

**Comment by Slach** [comment]
@DefauIt I can't reproduce this behavior on my local environment
let's try to describe steps to reproduce?
could you share CREATE TABLE statement for your table and smile dashboard JSON from your environment?

**Comment by DefauIt** [comment]
with interpolation disabled, the query works correctly, thanks.
