### ISSUE TITLE
alert :the query was executed at an incorrect time

### ISSUE THREAD

**Issue by shizhenchina** [Vertamedia/clickhouse-grafana#305]
` WHERE $timeFilter AND $to -$from<3601`
This is my query.When I use Alert, I test that the values from and to are correct.But the rawQuery value is problematic.

logs[0].data : 
`from:1605667726607`
`to:1605667846607`
`WHERE  timestamp >= toDateTime(1605667340) AND 1605667640 -1605667340<3601`
You can see that the values from and to are not used. I think the value of from and to is correct.But rawQuery USES window time

My alert :
condition:  query(A, 2m, now)

ps:
At first I used it directly, but a few days later I noticed that there were some slow queries in the SQL, and the time seemed to be used instead of the alert execution time.

**Comment by shizhenchina** [comment]
I activated the alarm again, I find that the execution time is the previous time.the time is 
`WHERE timestamp >= toDateTime(1605168658) AND 1605168958 -1605168658<3601`,this date is '2020-11-12',but today is '2020-11-18'

**Comment by negbie** [comment]
Just use something like this and you should be good to go
WHERE timestamp >= NOW() - INTERVAL ($to-$from)
Save the dashboard with your desired timeinterval.

**Comment by negbie** [comment]
Just make sure that the alert uses the new condition. Sometimes you need to hit the refresh button otherwise it won't be updated.

**Comment by Slach** [comment]
@negbie thanks a lot for the workaround
@shizhenchina could you confirm this solution is working for you?

**Comment by shizhenchina** [comment]
@negbie @Slach thank you, I'm going to test this method, and I'm going to synchronize the results

**Comment by shizhenchina** [comment]
@Slach It is ok to use this method.But there must be some limitations.

**Comment by shizhenchina** [comment]
![image](https://user-images.githubusercontent.com/34642989/100079908-3122fc00-2e80-11eb-8c87-b0765e12323f.png)
![image](https://user-images.githubusercontent.com/34642989/100080018-4e57ca80-2e80-11eb-93a9-942360960c09.png)
![image](https://user-images.githubusercontent.com/34642989/100080548-ec4b9500-2e80-11eb-98a6-a97db021337a.png)
This is a specific situation, if you can fix it, it should be better than the way to use the technique.

**Comment by Slach** [comment]
@shizhenchina 

maybe alert features in grafana is not enough flexible for your use case
maybe https://github.com/balerter/balerter will enough for your requirements for flexibility?

**Comment by Slach** [comment]
also, @shizhenchina look like this issue related to https://github.com/Vertamedia/clickhouse-grafana/issues/237, so I close issue, cause currently, I don't see good solution

**Comment by xieziqiang** [comment]
@shizhenchina Hello, I have the same problem.What's the reason? And what do you mean by some limitations?
