### ISSUE TITLE
Grafana Alerts return: `rpc error: code = Unknown desc = invalid status code`

### ISSUE THREAD

**Issue by lmangani** [Vertamedia/clickhouse-grafana#306]
Hello Team,

Thank you so much the continued work on this amazing, vital plugin for Grafana.

While trying the Alerting support on Grafana v7.3.3 (2489dc4d3a) I'm always receiving the following error.
Mind the timeseries are correctly returned and displayed. Any suggestion?

clickhouse-grafana query:
```
$columns(ruri_user, avg(mos) c ) FROM $table WHERE mos > 0
```

clickhouse-grafana error:
```
{
  "firing": true,
  "state": "pending",
  "conditionEvals": " = true",
  "timeMs": "6.302ms",
  "error": "tsdb.HandleRequest() error rpc error: code = Unknown desc = invalid status code. status: 500 Internal Server Error",
  "logs": [
    {
      "message": "Condition[0]: Query",
      "data": {
        "from": 1605875259316,
        "queries": [
          {
            "refId": "A",
            "model": {
              "database": "hepic_data",
              "dateColDataType": "",
              "dateLoading": false,
              "dateTimeColDataType": "record_datetime",
              "dateTimeType": "DATETIME",
              "datetimeLoading": false,
              "extrapolate": true,
              "format": "time_series",
              "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
              "intervalFactor": 1,
              "query": "$columns(ruri_user, avg(mos) c ) FROM $table WHERE mos > 0",
              "rawQuery": "SELECT t, groupArray((ruri_user, c)) AS groupArr FROM ( SELECT (intDiv(toUInt32(record_datetime), 20) * 20) * 1000 AS t, ruri_user, avg(mos) c FROM hepic_data.sip_transaction_call WHERE record_datetime >= toDateTime(1605776207) AND mos > 0 GROUP BY t, ruri_user ORDER BY t, ruri_user) GROUP BY t ORDER BY t",
              "refId": "A",
              "round": "0s",
              "skip_comments": true,
              "table": "sip_transaction_call",
              "tableLoading": false
            },
            "datasource": {
              "id": 5,
              "name": "ClickHouse"
            },
            "maxDataPoints": 0,
            "intervalMs": 0
          }
        ],
        "to": 1605875559316
      }
    }
  ]
}
```

**Comment by lmangani** [comment]
Note: I realize the errors is actually from Grafana, I am just wondering if anyone has encountered a similar scenario - thanks!

**Comment by lmangani** [comment]
I suspect this might be related:
```
t=2020-11-22T17:31:26+0100 lvl=warn msg="Plugin uses a deprecated version of Grafana's backend plugin system which will be removed in a future release. Consider upgrading to a newer plugin version or reach out to the plugin repository/developer and request an upgrade." logger=plugins.backend pluginId=vertamedia-clickhouse-datasource
```

**Comment by Slach** [comment]
Hello @lmangani sorry for late response, could you share your grafana dashboard to help me reproduce
i will try fix it later
also we plan to switch no new Grafana golang sdk, but no have time yet

**Comment by lmangani** [comment]
Thanks @Slach - what can i provide to troubleshoot best?

**Comment by lmangani** [comment]
btw @Slach we have golang devs in our team working on cloki-go, if you want we we can help or team up - ping @adubovikov

**Comment by lmangani** [comment]
Just to be sure, I've tried with multiple types of clickhouse queries without macros or variables but the failure is exactly the same - Grafana logs are completely useless and really point nowhere. Is there an example for a working alert around?

**Comment by Slach** [comment]
@lmangani I can't reproduce your issue with grafana 7.3
![image](https://user-images.githubusercontent.com/105560/100086221-f06eb700-2e6e-11eb-886b-17792ea4e65e.png)
![image](https://user-images.githubusercontent.com/105560/100086687-928e9f00-2e6f-11eb-8c0a-b31011e63aaa.png)
![image](https://user-images.githubusercontent.com/105560/100086795-b5b94e80-2e6f-11eb-8cab-5c06aab6a8d9.png)

steps to reproduce my screenshots
```
git clone https://github.com/Vertamedia/clickhouse-grafana.git
cd clickhouse-grafana
docker-compose up -d --no-deps clickhouse grafana
```
open
http://localhost:3000/d/Rln7U1GGk/test-alerts-dashboard?orgId=1&refresh=5s

could you share your dashboard.json via "Share dashboard" -> "export"->"export for sharing externally"?
![image](https://user-images.githubusercontent.com/105560/100086507-552a1180-2e6f-11eb-8c75-d2670d69f5ef.png)

**Comment by lmangani** [comment]
Thank you so much @Slach for giving this a try and sorry for the complexity here.  

I'm using a simple count, but also tried $columns w/o differences.

![image](https://user-images.githubusercontent.com/1423657/100087390-eb9a0b00-2e4e-11eb-9b92-1b35833ab3ad.png)

and pretty much the identical alert setup

![image](https://user-images.githubusercontent.com/1423657/100087410-f48adc80-2e4e-11eb-88ab-aad1d8061be6.png)

and no matter what, this is instantly the result from the Grafana logs:

![image](https://user-images.githubusercontent.com/1423657/100087748-7418ab80-2e4f-11eb-9e23-6f0812cf9636.png)

Tried on a few different setups and all query types, same issue even just with count().  Grafana is 7.3.3 and plugin is the latest also. I sent a gtalk invitation, feel free to ping me or @adubovikov to ease the pain, if you are interested in seeing it, we can just get you we access to the one of the test setups where it happens.

**Comment by Slach** [comment]
on my side, I got correct answer when "test alert", 
ok 500 status code means clickhouse server can't process query from golang backend plugin as I think 
could you check connection between your grafana server and your clickhouse server?
also, which settings do you use in grafana clickhouse datasource to authorization?
```
{
  "firing": true,
  "state": "pending",
  "conditionEvals": "true = true",
  "timeMs": "8.690ms",
  "matches": [
    {
      "metric": "test2",
      "value": 8024041457
    }
  ],
  "logs": [
    {
      "message": "Condition[0]: Query",
      "data": {
        "from": 1606221661616,
        "queries": [
          {
            "refId": "A",
            "model": {
              "database": "default",
              "dateColDataType": "EventDate",
              "dateLoading": false,
              "dateTimeColDataType": "EventTime",
              "dateTimeType": "DATETIME",
              "datetimeLoading": false,
              "extrapolate": true,
              "format": "time_series",
              "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
              "interval": "5m",
              "intervalFactor": 1,
              "query": "$columns(Name, sum(Value) c) FROM $table",
              "rawQuery": "SELECT t, groupArray((Name, c)) AS groupArr FROM ( SELECT (intDiv(toUInt32(EventTime), 300) * 300) * 1000 AS t, Name, sum(Value) c FROM default.test_alerts WHERE EventDate >= toDate(1594707193) AND EventTime >= toDateTime(1594707193) GROUP BY t, Name ORDER BY t, Name) GROUP BY t ORDER BY t",
              "refId": "A",
              "round": "0s",
              "table": "test_alerts",
              "tableLoading": false
            },
            "datasource": {
              "id": 1,
              "name": "clickhouse"
            },
            "maxDataPoints": 0,
            "intervalMs": 0
          }
        ],
        "to": 1606221961616
      }
    },
    {
      "message": "Condition[0]: Query Result",
      "data": {
        "meta": [
          {
            "Name": "t",
            "Type": "UInt64"
          },
          {
            "Name": "groupArr",
            "Type": "Array(Tuple(String, UInt64))"
          }
        ],
        "series": [
          {
            "name": "test2",
            "points": [
              [
                8024041457,
                1606221900000
              ]
            ]
          }
        ]
      }
    },
    {
      "message": "Condition[0]: Eval: true, Metric: test2, Value: 8024041457.000",
      "data": null
    }
  ]
}
```

**Comment by Slach** [comment]
@lmangani also could you check tablbe `system.query_log` or `/var/log/clickhouse-server.log` on your clickhouse installation and check queries which come from grafana server?

**Comment by lmangani** [comment]
Good point and.. indeed! I completely missed this in the gazillion loglines. This seems to only affect the Alert, while normal queries are also authenticated and doing fine. I only use basic auth w/ username:password and no headers. 
```
2020.11.24 15:32:53.620576 [ 12966 ] {} <Trace> HTTPHandler-factory: HTTP Request for HTTPHandler-factory. Method: POST, Address: 127.0.0.1:42666, User-Agent: Go-http-client/1.1, Length: 316, Content Type: , Transfer Encoding: identity
2020.11.24 15:32:53.620981 [ 12966 ] {} <Error> DynamicQueryHandler: Code: 516, e.displayText() = DB::Exception: default: Authentication failed: password is incorrect or there is no user with such name,

**Comment by Slach** [comment]
Please change basic auth type to Yandex.Cloud authorization
closed cause duplicate https://github.com/Vertamedia/clickhouse-grafana/issues/267

**Comment by lmangani** [comment]
Super super super thanks @Slach and sorry if it was a duplicate! Header authentication is not working for me (2.8.3.18) 
I can't find a setting to convince clickhouse to accept those headers, do you perhaps know which server setting this referts to?

**Comment by lmangani** [comment]
After a little back and forth with Grafana failing auth, it works! Thank you so much and again apologies for the duplicate
