### ISSUE TITLE
Enable gzip for json response from clickhouse db.

### ISSUE THREAD

**Issue by yangliuyu** [Vertamedia/clickhouse-grafana#312]
When I launch a big query, which get 70MB data from clickhouse db, the http response body do not encoding content with gzip i.e. missing `Content-Encoding: gzip`, even though I enabled the `enable_gzip = true` in /etc/grafana/grafana.ini
<img width="1453" alt="reqres" src="https://user-images.githubusercontent.com/1361821/102846210-5b011b80-444a-11eb-8a90-fa827eb52f3d.png"> Is plugin or grafana itself responsible for compressing the result to client?

**Comment by Slach** [comment]
@yangliuyu thanks a lot for the good feature request,

currently, the plugin doesn't pass a query parameter `enable_http_compression=1`
https://clickhouse.tech/docs/en/interfaces/http/


you could enable HTTP Compression on ClickHouse Server as a workaround
https://clickhouse.tech/docs/en/operations/settings/settings/#settings-enable_http_compression
you can create `/etc/clickhouse-server/users.d/http_compression.xml` with following content:
```
<yandex>
  <profiles><default><enable_http_compression>1</enable_http_compression></default></profiles>
</yandex>
```

**Comment by yangliuyu** [comment]
@Slach it works now and I got `content-encoding: br` . The response is quite faster now. Thanks a lot:)

**Comment by frank-lam** [comment]
it works for me.
