### ISSUE TITLE
[Feature Request] select DateTime64 as $timeSeries 

### ISSUE THREAD

**Issue by BigFatDog** [Vertamedia/clickhouse-grafana#313]
when creating a dashboard, adding a `Column: DateTime64` option would enable visualizations in milliseconds.

[Clickhouse Link](https://clickhouse.tech/docs/en/sql-reference/data-types/datetime64/)

Please see attached screenshot.
<img width="278" alt="截屏2020-12-28 上午10 24 19" src="https://user-images.githubusercontent.com/5818886/103225105-364bee80-48f7-11eb-8630-8e091326fb7b.png">

**Comment by Slach** [comment]
@BigFatDog latest version of plugin already supports DateTime64
please look to https://github.com/Vertamedia/clickhouse-grafana/issues/292
and subscribe https://github.com/grafana/grafana-plugin-repository/pull/803

**Comment by BigFatDog** [comment]
Thank you !
