### ISSUE TITLE
How to Log view with ClickHouse datasource plugin

### ISSUE THREAD

**Issue by asafcombo** [Vertamedia/clickhouse-grafana#315]
Hi, I was wondering if I could use this plugin with grafana to enable a log view on a specific table.

I want something similar to the kibana experience. Is that possible ?

**Comment by Slach** [comment]
@asafcombo what exactly do you mean?
you can use template variables as search string 
https://grafana.com/docs/grafana/latest/variables/
and table plugin for visualization
https://grafana.com/docs/grafana/latest/panels/visualizations/table/

and use SQL queries with ```field LIKE '%${template_variable_name}%'```

and for speedup on clickhouse side you can try to data skip indexes with type `ngrambf_v1`
https://clickhouse.tech/docs/en/engines/table-engines/mergetree-family/mergetree/#table_engine-mergetree-data_skipping-indexes

or try to use https://github.com/qxip/cloki-go with clickhouse with grafana Loki datasource plugin https://grafana.com/docs/grafana/latest/datasources/loki/

**Comment by asafcombo** [comment]
Thanks, Not a grafana expert.  Your suggestions did help me achieve some of what I had in mind. 

Still have some missing features, but I guess I just need to look how to do it. 

Initially I tried to achieve that with the explorer panel :/
