### ISSUE TITLE
enable table filtering for adhoc varaible

### ISSUE THREAD

**Issue by asafcombo** [Vertamedia/clickhouse-grafana#316]
For large databases it would be beneficial to limit somehow the user's ability to filter adhoc returned fields. ( I know that it can be further scoped down with the text input box ).

Unless there is an easier method, I was looking at:
https://github.com/Vertamedia/clickhouse-grafana/blob/79577010137b8401a263af3927546c21e9b22ef2/src/adhoc.ts#L1

which could be replaced to:

`const queryFilter = "database != 'system' and table = {table}";`

As a quick hack I thought about grabbing the `label` input

![image](https://user-images.githubusercontent.com/12124039/103903019-00331980-5104-11eb-8c54-5d0fdf484c2a.png)

and replace it instead of `{table}`

1. How can I grab the label field and insert into the above code ? 
2. easier native way ?

**Comment by Slach** [comment]
@asafcombo sorry for late reply
I just didn't firuge out how achieve your goal and didn't answer

**Comment by Slach** [comment]
we can reopen the issue if it still actual?
maybe label it's the best solution
