### ISSUE TITLE
variable search

### ISSUE THREAD

**Issue by alteeho** [Vertamedia/clickhouse-grafana#320]
Hi.
Using grafana-clickhouse variable query, Search does not work.
![image](https://user-images.githubusercontent.com/78098435/106023025-77424900-60d7-11eb-956b-5c1df02e778d.png)

**Comment by Slach** [comment]
@alteeho sorry for late reply 
on latest version of grafana this behavior not reproduce 

![image](https://user-images.githubusercontent.com/105560/146956376-1315bf45-33fd-4c1a-9c75-70db4dd90a38.png)
![image](https://user-images.githubusercontent.com/105560/146956484-34827227-41dd-4f57-b4f7-28dcb8440308.png)

Maybe root reason is `MOO` is not like `M0OS`?
