### ISSUE TITLE
RawQuery cause time condition using from / to useless

### ISSUE THREAD

**Issue by azsane** [Vertamedia/clickhouse-grafana#327]
When using alert with clickhouse-grafana , time was immutable when using from / to  as #305 metioned

After digging into source code for both grafana & clickhouse-grafana
I found it was a problem with rawQuery 

Everytime you edit the panel query then save, a rawQuery field in panel.targets **and also in alertRuleTags.query** was generated
rawQuery was transformed in sql_query.ts, the logic replaced all paramters to determine value
So rawQuery will hold the variable value when dashboard was saved

It's no problem when viewing dashboard in browser,but in alerting,things changed
Alerting loads rule from database,then sends to clickhouse-grafana plugin
the transform logic has no change to trigger,Then cause the from / to unchanged problem

Suggest move the logic from sql_query.ts to datasource.go,and use formattedQuery as query template

**Comment by Slach** [comment]
@azsane thanks a lot for the suggestions it really helpful
