### ISSUE TITLE
Grafana 7.4.2 Variables query using clickhouse groupArray() dosn't working

### ISSUE THREAD

**Issue by it1804** [Vertamedia/clickhouse-grafana#328]
Duplicate issue from https://github.com/grafana/grafana/issues/31445
In grafana variables 7.4.x, an error occurs when using the groupArray () function in a request. 
In versions 7.3.x everything works fine.

**Comment by Slach** [comment]
on latest master `groupArray` doesn't pass validation on the grafana side with "invalid data format" message, so, look like grafana team allow only scalar types in variables now
![image](https://user-images.githubusercontent.com/105560/112128695-7e259d80-8be8-11eb-8498-5c67ced37da1.png)
