### ISSUE TITLE
$columns support multiple columns

### ISSUE THREAD

**Issue by MarloweW** [Vertamedia/clickhouse-grafana#33]
The doc has shown an example of $columns:

```
$columns(OSName, count(*) c) FROM requests
```

Sometimes, I need to group multi columns to find out differences, such as OS platform and version, I 'm wondering if this usage could be supported:

`$columns(key_1, key_2, value)` or `$columns((key_1, key_2), value) `

which query values as array of [key, value], where key will be used as label, and key is a combination of key_1 key_2.

**Comment by hagen1778** [comment]
Hi @MarloweW 
Currently, plugin doesn't support multiple labels or any mechanism to choose between them like it's done in Prometheus datasource.
But you can do it in different way:
`
$columns(
    concat(toString(Environment), '-', OSName) l,
    count(*) c)
FROM $table
ANY INNER JOIN oses USING  OS
`
So, in the query above you asking ClickHouse to combine your labels and you can choose any combination form you want.

**Comment by MarloweW** [comment]
The concat way do solve the problem. Thanks.
