### ISSUE TITLE
golang part of plugin incorrect handle empty (rows=0) results from Clickhouse

### ISSUE THREAD

**Issue by Slach** [Vertamedia/clickhouse-grafana#335]
need to research howto return "NODATA" instead of "ERROR" when we got empty result from ClickHouse

**Comment by Slach** [comment]
@bmanth60 JFYI

**Comment by bmanth60** [comment]
@Slach I read the PR, but I don't quite understand the fix, is it that there is a nullable and low cardinality type?

**Comment by Slach** [comment]
the main goal of fix
for most corner cases shall return multiple data frames instead of just one data.Frame

each `data.Frame` for each exists time series with two fields `(time, value)` 
`String` fields and complex type fields used as labels

`Array(Tuple(` which return after apply $macro converts to multiple data.Frames use first field as label, second field as value

also, SQL queries can return nullable values and DateTime64, so I add support for this corner cases

LowCardinality also supported for properly parsing label values

Also, if we return SQL result without a timestamp field
We just return one data.Frame which contains all fields

**Comment by bmanth60** [comment]
Interesting, thanks!
