### ISSUE TITLE
ahoc filters inside table view

### ISSUE THREAD

**Issue by asafcombo** [Vertamedia/clickhouse-grafana#336]
I cannot see the below option available,  I assume it is a plugin specific implementation ? 

![image](https://user-images.githubusercontent.com/12124039/115533921-e7f49e00-a29f-11eb-8a67-dd53041ed70a.png)

For reference https://github.com/grafana/grafana/issues/25072  talks about  this feature with elasticsearch plugin

**Comment by Slach** [comment]
@asafcombo sorry for the late reply

latest version Grafana 8.x currently successfull support Column Filter for new Table plugin
and it works fine with vertamedia-clickhouse-datasource

![image](https://user-images.githubusercontent.com/105560/146948786-60a522c0-382e-4feb-b3fc-b39764261ad8.png)
