### ISSUE TITLE
Error invalid username or password for user "default" in Alerts

### ISSUE THREAD

**Issue by tmanh17** [Vertamedia/clickhouse-grafana#342]
**What happened**:

Get error ```invalid username or password for user "default";``` although don't use ```default``` user in configuration.

**What you expected to happen**:

It works for all normal users.

**How to reproduce it (as minimally and precisely as possible)**:

1. Install vertamedia-clickhouse-datasource plugin v2.3.1, by following https://github.com/Vertamedia/clickhouse-grafana/issues/341#issuecomment-830168467
2. create a dashboard and panel that use ClickHouse Datasource with basic authentication using an particular user except ```default``` user then create an alert for this.
<img width="450" alt="portfolio_view" src="https://user-images.githubusercontent.com/29015535/116731828-6aa1f980-aa14-11eb-9c41-fe452f518ec2.png">
3. click Test rule

<img width="450" alt="portfolio_view" src="https://user-images.githubusercontent.com/29015535/116731248-a8525280-aa13-11eb-98be-0f01800ac169.png">

**Anything else we need to know?**:

Don't get this error if we use default user 

**Environment**:
- Grafana version: v7.4.2
- Plugin version: v2.3.1
- OS Grafana is installed on: Debian 8.5
- User OS & Browser: Ubuntu 20.04 & Chrome
- Others:

**Comment by Slach** [comment]
thanks a lot for reporting i will try to fix it ASAP
