### ISSUE TITLE
$timeFilterByColumn not working with DateTime64

### ISSUE THREAD

**Issue by oplehto** [Vertamedia/clickhouse-grafana#343]
I have a timeseries where I'm using nanosecond-level timestamps and am trying to use it with $timeFilterByColumn to populate a template variable. However just using this fails:
```
$timeFilterByColumn(_time)
```

I'm working around it with this:
```
WHERE _time > toDateTime64($from,9) AND _time < toDateTime64($to,9)
```

**Comment by Slach** [comment]
unfortunatelly, macros doesn't have information about filed type
if think we can implements $timeFilter64ByColumn to allow this option

**Comment by Slach** [comment]
thanks a lot for reporting

**Comment by oplehto** [comment]
> unfortunatelly, macros doesn't have information about filed type
> if think we can implements $timeFilter64ByColumn to allow this option

Understood. I agree that having a dedicated macro is probably the most reasonable option.

**Comment by silashansen** [comment]
We're using this more generic variant:

```
WHERE $dateTimeCol BETWEEN toDateTime64($from, 3) AND toDateTime64($to, 3)
```

Still a little annoying.

**Comment by Slach** [comment]
@oplehto could you clarify, how do you select time range in `grafana` with `nanoseconds`?
As I see, currently Grafana itself operates with time ranges in `ms`

**Comment by oplehto** [comment]
Yeah, Grafana internally uses milliseconds so the timerange selection would be rounded to that granularity. This behavior would be similar to InfluxDB which also has nanosecond timestamps. The motivation is to be able to handle high resolution timestamps with similar semantics as normal DateTime timestamps.

**Comment by Slach** [comment]
@silashansen 
you also try to use `WHERE $dateTimeCol BETWEEN toDateTime64($__from/1000, 3) AND toDateTime64($__to/1000, 3)` as more precised workaround
