### ISSUE TITLE
Alert doesn't work correctly

### ISSUE THREAD

**Issue by tmanh17** [Vertamedia/clickhouse-grafana#345]
**What happened**:

Alert doesn't work correctly. It always send No Data alert

**What you expected to happen**:

It notify alert if it happens actually

**How to reproduce it (as minimally and precisely as possible)**:

1. Install vertamedia-clickhouse-datasource plugin v2.3.1
1.1. Download the plugin  https://github.com/Vertamedia/clickhouse-grafana/releases/tag/v2.3.1
1.2. Unzip to /var/lib/grafana/plugins/
1.3. restart grafana-server
2. create a dashboard and panel that use ClickHouse Datasource then create an alert for this.
<img width="450" alt="portfolio_view" src="https://user-images.githubusercontent.com/29015535/117473141-d68be100-af83-11eb-9d7d-d425c9a89f8b.png">

3. click Test rule or add a channel email for this alert

Case 1 get No Data alert although it doesn't exist
<img width="450" alt="portfolio_view" src="https://user-images.githubusercontent.com/29015535/117473364-1652c880-af84-11eb-8f1a-14c0683950d2.png">
Case 2 Should be an alert for high value instead of No Data notification
<img width="450" alt="portfolio_view" src="https://user-images.githubusercontent.com/29015535/117473488-3da99580-af84-11eb-8490-28637f3307e7.png">

**Environment**:
- Grafana version: v7.4.2
- Plugin version: v2.3.1
- OS Grafana is installed on: Debian 8.5
- User OS & Browser: Ubuntu 20.04 & Chrome
- Others:

**Comment by Slach** [comment]
Thanks for reporting, could you share alert tab screenshot in your panel or just share full panel JSON?

**Comment by Slach** [comment]
@tmanh17 did you try to SAVE whole dashboard after change in "alerts"?

**Comment by winofi** [comment]
Are you using GET and your server does not support POST?

**Comment by SachChen** [comment]
I have met a same problem, from the grafana's log , i found the vertamedia-clickhouse-datasourc plugin has been restarted ,  it seems like that the plugin has dumped when the response of   clickhouse's data is too much，just in version v2.3.1 but not only!
