### ISSUE TITLE
Is this the correct way to use it via grafana?

### ISSUE THREAD

**Issue by orbwalker** [Vertamedia/clickhouse-grafana#347]
┌─name──────────┬─type──────────┬
│ FieldUUID     │ UUID          │
│ EventDate     │ Date          │
│ EventDateTime │ DateTime      │
│ Metric        │ String        │
│ LabelNames    │ Array(String) │
│ LabelValues   │ Array(String) │
│ Value         │ Float64       │
└───────────────┴───────────────┴
```sql
select
	*
from
	metrics.shell s
where
	EventDateTime = (
	select
		EventDateTime
	from
		metrics.shell s2
	where
		Metric = 'cluster_cm_agent_physical_memory_used'
	order by
		EventDateTime
	limit 1)
	AND Metric = 'cluster_cm_agent_physical_memory_used'
```
**question:** Is this the correct way to use it via grafana?
name{label1=' ', label2=' '} value

**Comment by Slach** [comment]
lets discuss in https://stackoverflow.com/questions/67584369/is-this-the-correct-way-to-use-it-via-grafana/
