### ISSUE TITLE
clickhouse-grafana falls back to POST for alert queries

### ISSUE THREAD

**Issue by winofi** [Vertamedia/clickhouse-grafana#353]
Database queries for grafana alerts seem to be send using HTTP POST even when usePost is set to false for the datasource. Symptoms are that the plots show data but alerts always fail. 

Might be connected to to the hardcoded POST here: https://github.com/Vertamedia/clickhouse-grafana/blob/2f2d2e164848ac0c54d745ab8d7ec301dc2c948a/src/datasource.ts#L201 but I am not familiar with grafana internals. 

Might also be the cause for https://github.com/Vertamedia/clickhouse-grafana/issues/345 when GET is used and the server does not support POST. 

Grafana: 8.0.2
Clickhouse-Grafana: 2.3.1

**Comment by Slach** [comment]
@winofi do you make SQL queries not directly to clickhouse-server?
Which proxy server do you use?

**Comment by winofi** [comment]
Sorry forgot to mention: there is an nginx proxy in front of the clickhouse server, which might block POST to enforce readonly access.
