### ISSUE TITLE
id：13606 CK UP Time display N/A

### ISSUE THREAD

**Issue by zhanghaicheng1** [Vertamedia/clickhouse-grafana#355]
grafana version：8.0.3
clickhouse version：20.8.3.18

![image](https://user-images.githubusercontent.com/46189785/125407796-ce6d7900-e3ec-11eb-9f83-6883acf1f51f.png)

**Comment by Slach** [comment]
could you change format to "Table"
and change Field -> Unit on right panel

![image](https://user-images.githubusercontent.com/105560/125410706-9e1ae000-e3d6-11eb-8a68-777e9b5820b1.png)
