### ISSUE TITLE
Clickhouse Alert Throwing Error - request handler error: plugin unavailable

### ISSUE THREAD

**Issue by gsingh14** [Vertamedia/clickhouse-grafana#356]
Setup 
Grafana : Grafana v8.1.0-pre (unknown-dev)
Clickhouse plugin : 2.3.1

Steps 
1. Using Docker to build grafana image
2. In Dockerfile add command to copy vertamedia-clickhouse-datasource folder to var/lib/grafana/plugins
3. Build Docker image
4. Start Docker Container 
5. Setup email alert config 
6. Create a sample dashboard connecting to clickhouse instance
7. Use the following sample query in dashboard query section
```
SELECT
    $timeSeries as t,
    count()
FROM $table

WHERE $timeFilter

GROUP BY t

ORDER BY t
```
8. Update the Alert Tab with sample values to fire an alert 
![image](https://user-images.githubusercontent.com/128828/125510634-42d2e4e8-12ef-40aa-9d0d-c1a518c1ada3.png)
9. Click on Test Rule and the following error pop up 
![image](https://user-images.githubusercontent.com/128828/125510712-56919526-2ed7-4999-a092-21b143b29460.png)

Can someone help with this issue?

**Comment by Slach** [comment]
could you open "plugins" in UI and check clickhouse plugin is "signed"?

![image](https://user-images.githubusercontent.com/105560/125554930-6bb6985c-1ef3-4903-ab38-2b4ab11f1ec5.png)
![image](https://user-images.githubusercontent.com/105560/125554965-e641a1ca-ad7a-4220-9cb2-c49d0d0793fa.png)

**Comment by gsingh14** [comment]
Hi @Slach . Thanks for your reply. The plugin is signed per the following screenshot 

![image](https://user-images.githubusercontent.com/128828/125555688-98f1de24-1748-4f66-a8c9-6b8f29d7cd1d.png)

**Comment by Slach** [comment]
could you add to your Dockerfile `ENV GF_LOG_LEVEL=debug`
and share logs of your custom grafana container?

**Comment by gsingh14** [comment]
Following is the debug log when i create an alert and click on Test Rule. 

```
t=2021-07-14T17:06:43+0000 lvl=dbug msg="Scheduling update" logger=alerting.scheduler ruleCount=0
t=2021-07-14T17:06:44+0000 lvl=dbug msg="Querying for data source via SQL store" logger=datasources id=1 orgId=1
t=2021-07-14T17:06:44+0000 lvl=dbug msg="Applying default URL parsing for this data source type" logger=datasource type=vertamedia-clickhouse-datasource url=https://CH_URL:9443
t=2021-07-14T17:06:53+0000 lvl=dbug msg="Scheduling update" logger=alerting.scheduler ruleCount=0
t=2021-07-14T17:06:55+0000 lvl=dbug msg="Extracted alerts from dashboard" logger=alerting.extractor alertCount=1
t=2021-07-14T17:06:55+0000 lvl=eror msg="Alert Rule Result Error" logger=alerting.evalContext ruleId=0 name="Panel Title alert" error="request handler error: plugin unavailable" changing state to=alerting
t=2021-07-14T17:07:03+0000 lvl=dbug msg="Scheduling update" logger=alerting.scheduler ruleCount=0
t=2021-07-14T17:07:13+0000 lvl=dbug msg="Scheduling update" logger=alerting.scheduler ruleCount=0
```

Note : I have replaced my internal CH instance url with CH_URL here for security purposes.

**Comment by Slach** [comment]
@gsingh14 thanks a lot for reporting I will try to reproduce, and tix it ASAP

**Comment by Slach** [comment]
Unfortunately, currently it's not easy to provide custom certificate authority in SSL certs inside grafana, both on frontend and on backend side.
