### ISSUE TITLE
Is there some compatibility issue between Grafana6.x and Grafana7.x to clickhouse 21.1?

### ISSUE THREAD

**Issue by praisethejack** [Vertamedia/clickhouse-grafana#359]
I have used Grafana6.5.2 and Grafana7.5.10 to query the same data source clickhouse21.1.3.32
In G6, it work well.
However, in G7, it return this
```
Code: 60, e.displayText() = DB::Exception: Table default.undefined doesn't exist (version 21.1.3.32 (official build))
```

Beside, I found that if there are a column name `value` in the table, G7 will return error like this
```
Code: 43, e.displayText() = DB::Exception: Illegal types of arguments (Float32, Date) of function greaterOrEquals: While processing (value >= toDate(1627271141)) AND (value <= toDate(1627271441)) (version 21.1.3.32 (official build))
```

Is there some compatibility issue between Grafana7.x to clickhouse 21.1?

**Comment by Slach** [comment]
do you install the same version of clickhouse-grafana plugin?
look to "Plugins" and check version
![image](https://user-images.githubusercontent.com/105560/126951588-0fedb4f3-4e47-4996-a501-41b11b9a3c6a.png)
![image](https://user-images.githubusercontent.com/105560/126951675-810d3271-167e-4394-85a9-1f404c257d3b.png)

after it look to "generated SQL" on grafana SQL
and try find the differences between your grafana 7.x version and grafana 6.x version

**Comment by praisethejack** [comment]
@Slach Sure both are 2.3.1. I follow https://grafana.com/grafana/plugins/vertamedia-clickhouse-datasource/?tab=installation

**Comment by praisethejack** [comment]
I just re-verified it at G7, it work, no error! Maybe I did the wrong operation this morning
Please close this issus.
