### ISSUE TITLE
Can't find Raw SQL Editor

### ISSUE THREAD

**Issue by zjhcqbywd** [Vertamedia/clickhouse-grafana#361]
I am in grafana7.5.7。
![image](https://user-images.githubusercontent.com/41995590/127801143-c5ab519d-7057-4061-a002-ee459a85d872.png)
I can't find Raw SQL Editor...
I don't know why

**Comment by Slach** [comment]
which plugin version do you use?
did you select database and table before click "go to query"?
![image](https://user-images.githubusercontent.com/105560/127837772-4c7f5163-63fe-4a6d-ad06-b70f460d6e5e.png)

**Comment by oliverdding** [comment]
I've encountered this issue too, you can try to switch to time series instead of graph(old), then save the dashboard and reload.

**Comment by zjhcqbywd** [comment]
Thanks
Now I've choosen grafana8.0.5 to slove this problem.
