### ISSUE TITLE
Grafana 8.0.4 alerts does not correctly work (multiple alerts per graph)

### ISSUE THREAD

**Issue by IvanTheFirst** [Vertamedia/clickhouse-grafana#362]
Hello!
I have grafana 8.0.4 with new alerts and plugin version 2.3.1.
And there are two problems:
1. I can create alert only from dashboard graph. When I try to create alert from "Alerting" menu i get this error - 

> Failed to evaluate queries and expressions: failed to execute conditions: failed to query data: Failed to query data: rpc error: code = Unknown desc = unable to parse json {"dateTimeType":"DATETIME","extrapolate":true,"format":"time_series","formattedQuery":"SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t","hide":false,"intervalFactor":1,"intervalMs":1000,"maxDataPoints":43200,"query":"SELECT 1\n","rawQuery":true,"refId":"A","round":"0s","skip_comments":true}. Error: json: cannot unmarshal bool into Go struct field Query.rawQuery of type string

2. Alert does not contain "labels" and I can't create multiple alerts from one graph like this https://github.com/grafana/grafana/issues/7832#issuecomment-856725093

3. sometimes doubling metrics names in alerts

sample request
`
SELECT
Time,
groupArray((instance,value)) as arr
FROM
(SELECT toDateTime(now() - INTERVAL 60 SECOND) as Time,'cpu1_host1'as instance,20 as value
UNION ALL 
SELECT toDateTime(now() - INTERVAL 120 SECOND) as Time ,'cpu1_host1'as instance,30 as value
UNION ALL 
SELECT toDateTime(now() - INTERVAL 60 SECOND) as Time ,'cpu1_host2'as instance,50 as value
UNION ALL 
SELECT toDateTime(now() - INTERVAL 120 SECOND) as Time ,'cpu1_host2'as instance,40 as value
)
GROUP BY Time,instance
ORDER BY Time
`

Is there any way to fix this?
Thank you.

**Comment by Slach** [comment]
thanks a lot for reporting
unfortunately I don't have resources to fix it asap, so feel free to create PR

**Comment by IvanTheFirst** [comment]
Eugene, I will try :)

**Comment by Slach** [comment]
I found the root reason, but unfortunatelly it's not easy to fix. New grafana unified alerts need to implements full sql parser on golang part
please subsribe here to follow progress
https://github.com/Vertamedia/clickhouse-grafana/issues/380#issuecomment-971598622

@derN3rd you can set up `grafana` alerts in old way
just set the following environment variables
```
GF_UNIFIED_ALERTING_ENABLED=false
GF_ALERTING_ENABLED=true
```
