### ISSUE TITLE
Generate bad time condition 

### ISSUE THREAD

**Issue by antipooh** [Vertamedia/clickhouse-grafana#363]
grafana 8.0.6, vertamedia-clickhouse-datasource 2.3.1, clickhouse 21.5.5.12
![Selection_002](https://user-images.githubusercontent.com/1614229/128965966-7de61a75-a0db-4824-aa38-610b6aa40df0.png)
generated SQL:
```sql
SELECT t, groupArray((response_status, c)) AS groupArr
  FROM (SELECT (intDiv(toUInt32(timestamp), 15) * 15) * 1000 AS t, response_status, count(*) AS c
          FROM logs.nginx
         WHERE timestamp >= toDate(1628648711)
           AND timestamp <= toDate(1628652311)
           AND timestamp >= toDateTime(1628648711)
           AND timestamp <= toDateTime(1628652311)
         GROUP BY t, response_status
         ORDER BY t, response_status)
 GROUP BY t
 ORDER BY t
```

here toDate(1628648711) and toDate(1628652311) a both convert to 2021-08-11 and conditons `timestamp >= toDate(1628648711)
AND timestamp <= toDate(1628652311)` always FALSE for this day

**Comment by Slach** [comment]
could you select only "dateTime" field in query editor window before press "go to query" button?
![image](https://user-images.githubusercontent.com/105560/128989174-c7ecdccf-4ad7-4599-b47f-5292e5d1d34c.png)
![image](https://user-images.githubusercontent.com/105560/128990532-62181f6b-fe56-4b35-9b20-d20363f20d1d.png)

**Comment by antipooh** [comment]
I couldn't make it via UI, but change direct in dashboard JSON `"dateColDataType": null`. And now all working good. Thanks! Sorry for the erroneous issue.

**Comment by Slach** [comment]
hm, just try press `backspace` in `dropdown` it should works
