### ISSUE TITLE
question on aggregated and fresh data 

### ISSUE THREAD

**Issue by arnitolog** [Vertamedia/clickhouse-grafana#364]
Hello,

I'm wondering what is the proper way to show aggregated and fresh data on the same graph?
For example, we have a table with LoadBalancer's logs. Here we have 5 mins datasets
And we have another Aggregated table with data aggregated to 1-hour datasets. 
Is it possible to create a panel that will show 5-min data on intervals from now to now-1d and 1-hour data for any older periods?

**Comment by Slach** [comment]
yes it possible

![image](https://user-images.githubusercontent.com/105560/129733979-31c79b83-fc3c-4b60-8dea-64371aaa6c65.png)
