### ISSUE TITLE
Problem with alert, Error: request handler error

### ISSUE THREAD

**Issue by Lucgarg** [Vertamedia/clickhouse-grafana#368]
hello i'm using the version 8.1.4 of grafana, and the 2.3.1 of clickhouse source.

**I'm using the next query** 

SELECT COUNT(*) FROM test.test1 Column: datatime64  date 

**if i click in get query:** 

SELECT
    $timeSeries as t,
    count()
FROM $table

WHERE $timeFilter

GROUP BY t

**The query generated is:** 

SELECT
    (intDiv(toFloat64(fecha) * 1000, (15 * 1000)) * (15 * 1000)) as t,
    count()
FROM prueba.con1

WHERE toDateTime64(fecha, 3) >= toDateTime64(1632113349, 3) AND toDateTime64(fecha, 3) <= toDateTime64(1632134949, 3)

GROUP BY t

**The alert configuration is:** 

evaluate every 5s For 10s

where count() OF query(SELECT COUNT(*), 1m, now) IS ABOVE 200000

in No data and error handling i put : 
If no data or all values are null: set state No Data
If execution error or timeout:  set State to alerting

**When i load data to clickhouse, and grafana get the data i get the next error:** 

Error: request handler error: failed to query data: Failed to query data: rpc error: code = Unavailable desc = connection error: desc = "transport: error while dialing: dial unix /tmp/plugin267514296: connect: connection refused"

I tried to change  the time range on _where count() OF query(SELECT COUNT(*), 1m, now) IS ABOVE 200000_ from 5m to 1s, if a put 1s then the error dont appear but also, it does not launch the alert when the conditions are met. 

Any idea what the cause may be?

**Comment by juliito19** [comment]
please check your version,Lucas .

**Comment by Slach** [comment]
```
Error: request handler error: failed to query data: Failed to query data: rpc error: code = Unavailable desc = connection error: desc = "transport: error while dialing: dial unix /tmp/plugin267514296: connect: connection refused"
```
Look like connection refused between grafana-server and plugin

Could you provide debug logs from your grafana server?

for example setup `GF_LOG_LEVEL=debug` on grafana-server 
or define 

```ini
[log]
level=debug
```

in your grafana.ini ?

**Comment by Lucgarg** [comment]
Hello, thanks for the reply. The logs are these, but as you can see they don't say much.



If I see something that catches my attention and it is this line panic: interface conversion: main.Value is int64, not time.Time "

If I do not misunderstand, first it have difficulties to find the plugin (I have looked and it is in the signed state and when I do the connection test it works). Then the error that I point out above occurs and later it throws the request handler error exception


Sometimes the alert occurs even before the request handler error is launched, throwing the following message: Error: request handler error: plugin unavailable

**Logs**

t=2021-09-21T12:20:21+0200 lvl=dbug msg="\t/home/runner/go/pkg/mod/google.golang.org/grpc@v1.36.1/server.go:878 +0xa5" logger=plugins.backend pluginId=vertamedia-clickhouse-datasource
t=2021-09-21T12:20:21+0200 lvl=dbug msg="created by google.golang.org/grpc.(*Server).serveStreams.func1" logger=plugins.backend pluginId=vertamedia-clickhouse-datasource
t=2021-09-21T12:20:21+0200 lvl=dbug msg="\t/home/runner/go/pkg/mod/google.golang.org/grpc@v1.36.1/server.go:876 +0x1fd" logger=plugins.backend pluginId=vertamedia-clickhouse-datasource
t=2021-09-21T12:20:21+0200 lvl=dbug msg="plugin process exited" logger=plugins.backend pluginId=vertamedia-clickhouse-datasource path=/var/lib/grafana/plugins/vertamedia-clickhouse-datasource/vertamedia-clickhouse-plugin_linux_amd64 pid=9177 error="exit status 2"
t=2021-09-21T12:20:21+0200 lvl=dbug msg="Job Execution attempt triggered retry" logger=alerting.engine timeMs=217.644 alertId=1 name="Panel Title alert" firing=true attemptID=1
t=2021-09-21T12:20:21+0200 lvl=dbug msg="Job Execution attempt triggered retry" logger=alerting.engine timeMs=1.695 alertId=1 name="Panel Title alert" firing=true attemptID=2
t=2021-09-21T12:20:21+0200 lvl=eror msg="Alert Rule Result Error" logger=alerting.evalContext ruleId=1 name="Panel Title alert" error=**"request handler error: plugin unavailable**" changing state to=alerting
t=2021-09-21T12:20:21+0200 lvl=info msg="New state change" logger=alerting.resultHandler ruleId=1 newState=pending prev state=no_data


t=2021-09-21T12:20:24+0200 lvl=dbug msg="Applying default URL parsing for this data source type" logger=datasource type=vertamedia-clickhouse-datasource url=http://192.168.56.105:8123
t=2021-09-21T12:20:25+0200 lvl=dbug msg="Scheduler: Putting job on to exec queue" logger=alerting.scheduler name="Panel Title alert" id=2
**t=2021-09-21T12:20:25+0200 lvl=dbug msg="panic: interface conversion: main.Value is int64, not time.Time" logger=plugins.backend pluginId=vertamedia-clickhouse-datasource**
t=2021-09-21T12:20:25+0200 lvl=dbug msg= logger=plugins.backend pluginId=vertamedia-clickhouse-datasource
t=2021-09-21T12:20:25+0200 lvl=dbug msg="goroutine 34 [running]:" logger=plugins.backend pluginId=vertamedia-clickhouse-datasource


t=2021-09-21T12:20:31+0200 lvl=dbug msg="\t/home/runner/go/pkg/mod/google.golang.org/grpc@v1.36.1/server.go:878 +0xa5" logger=plugins.backend pluginId=vertamedia-clickhouse-datasource
t=2021-09-21T12:20:31+0200 lvl=dbug msg="created by google.golang.org/grpc.(*Server).serveStreams.func1" logger=plugins.backend pluginId=vertamedia-clickhouse-datasource
t=2021-09-21T12:20:31+0200 lvl=dbug msg="\t/home/runner/go/pkg/mod/google.golang.org/grpc@v1.36.1/server.go:876 +0x1fd" logger=plugins.backend pluginId=vertamedia-clickhouse-datasource
t=2021-09-21T12:20:31+0200 lvl=dbug msg="Job Execution attempt triggered retry" logger=alerting.engine timeMs=269.854 alertId=1 name="Panel Title alert" firing=true attemptID=1
t=2021-09-21T12:20:31+0200 lvl=dbug msg="Job Execution attempt triggered retry" logger=alerting.engine timeMs=0.423 alertId=1 name="Panel Title alert" firing=true attemptID=2
**t=2021-09-21T12:20:31+0200 lvl=eror msg="Alert Rule Result Error" logger=alerting.evalContext ruleId=1 name="Panel Title alert" error="request handler error: failed to query data: Failed to query data: rpc error: code = Unavailable desc = connection error: desc = \"transport: error while dialing: dial unix /tmp/plugin177413901: connect: connection refused\"" changing state to=alerting**
t=2021-09-21T12:20:31+0200 lvl=info msg="New state change" logger=alerting.resultHandler ruleId=1 newState=alerting prev state=pending

**Comment by Slach** [comment]
ok. look like you need to change query
if you just setup
```
SELECT COUNT(*) FROM test.test1
```
in query editor
it will return not time-series compatible data
plugin backend expect only time series format with `t` column in resultset which represents as time series

**Comment by Lucgarg** [comment]
thanks for the reply. 

Try to leave alone  

SELECT
    $timeSeries as t
FROM $table


GROUP BY t

ORDER BY t

But dont appear data in the dashboard. 
But if I see the json i get 
response:Object
meta:Array[1]
0:Object
name:"t"
type:"UInt64"
data:Array[108]
0:Object
t:149623200000
1:Object
t:149623500000
2:Object
t:149623800000
3:Object
t:149624100000
4:Object
t:149624400000
5:Object
t:149624700000

I see the logs but only show the query.


On the other hand, is it not possible to select other values? for example: if a user connects so many times in a given time, an alert is triggered?
 
example:

SELECT
time,
count (users) FROM test.test1

group by users;

and then in alert:

when count () above {units}

**Comment by carlanton** [comment]
This sounds a lot like #350! Alerting doesn’t work with DateTime64. It’s fixed in master but not released yet. :)

**Comment by Slach** [comment]
@carlanton thanks a lot for your effort
yes, look like we have one more issue for new release
