### ISSUE TITLE
Allow to use variables as column names

### ISSUE THREAD

**Issue by Akint** [Vertamedia/clickhouse-grafana#37]
Hello,

I have a table with number of columns of similar meaning (for example, count of errors by types, where each column represent certain error type).
Example:
```
┌───────date─┬────────────datetime─┬────metric1─┬────metric2─┬────metric3─┐
│ 2018-03-06 │ 2018-03-06 10:20:11 │ 3731493556 │ 3731493556 │ 3731493556 │
│ 2018-03-06 │ 2018-03-06 10:20:12 │  273977558 │  273977558 │  273977558 │
│ 2018-03-06 │ 2018-03-06 10:20:13 │ 4026407843 │ 4026407843 │ 4026407843 │
└────────────┴─────────────────────┴────────────┴────────────┴────────────┘
```
I want to place graphs based on data from all of these columns on single dashboard without hard-coding column names. As a result, if any column is added or removed, dashboard is rebuild automatically.
By default, datasource (or grafana itself, I don't remember exactly whose behavior it is) adds quotes to variable value if 'Multi-value' or 'Include All option' is used, so you cannot do something like `SELECT $metric FROM table_name` since `SELECT 'metric1' FROM table_name` will actually be executed.

For datasource v0.1 I hackishly implemented my own function `$getColumnNameFromString`, which simply removed all quotes from given variable, and used it like this:
`select $timeSeries, $getColumnNameFromString($metric) from stats_table where $timeFilter` for graphs repeated by `$metric`.

I would greatly appreciate if you could provide similar functionality (hopefully, in more convenient way than I have described).

**Comment by hagen1778** [comment]
Hi @Akint 
Indeed, plugin add quotes to variables with `multi-value` or `include-all` options. 
Are you trying to build a panel with multiple columns or dashboard? 
If second, you might try to use repeated panels/rows (http://docs.grafana.org/reference/templating/#repeating-panels)

**Comment by Akint** [comment]
I tried to use repeated panels and rows and it did't work out of the box since it tried to select string instead of column:
```
SELECT     (intDiv(toUInt32(datetime), 1) * 1) * 1000 as t,     'metric1' FROM default.stats WHERE date BETWEEN toDate(1520396817) AND toDate(1520396831) AND datetime BETWEEN toDateTime(1520396817) AND toDateTime(1520396831) GROUP BY t ORDER BY t
```
That's why I had to write the function I mentioned before.
Or have I got your suggestiong wrong?
![repeated4column](https://user-images.githubusercontent.com/2721104/37074101-8d929c1c-21fd-11e8-943a-8b20c7529085.png)
![repeated4column2](https://user-images.githubusercontent.com/2721104/37074102-8dc02e66-21fd-11e8-9a33-b0e6ea7de9fd.png)

**Comment by hagen1778** [comment]
No, you are totally right. It seems like adding a new macros like `unescape` is the best solution, because we can't change variables create form(add some new checkbox etc). If you have time and desire, I'll be glad to accept a pr. Otherwise you will have to wait till the end of week for this macros

**Comment by Akint** [comment]
@hagen1778, sorry, I am not skilled enough to implement it right, so I'll wait.

**Comment by hagen1778** [comment]
Hi @Akint 
Plz check branch https://github.com/Vertamedia/clickhouse-grafana/tree/unescape for new macros `unescape`. Documentation and richeditor autocompletion updated with info about new macros.

How to test it:
* download source code from branch
* put it into Grafana's plugin directory
* restart Grafana
* test it

> Do not forget to remove application cache for Grafana in your browser or simply use browser's `incognito` mode

**Comment by Akint** [comment]
@hagen1778, it works like a charm, thank you! I have even managed to create a graph contained of all metrics:
```
SELECT
    t,
    arrayMap(lambda((x, y), (x, y)), [$metric], metric)
FROM
(
    SELECT
        $timeSeries as t,
        sumForEach([$unescape($metric)]) as metric
    FROM $table
    WHERE $timeFilter
    GROUP BY t
)
ORDER BY t
```
![single_graph](https://user-images.githubusercontent.com/2721104/37267170-22b8ebc4-25f1-11e8-8e58-41db5225da6b.png)

By the way, the plugin breaks `->` operator (lambda function): from query `x, y -> (x,y)` it generates query `x, y - >(x, y)`. So I had to use uglier version `lambda((x, y), (x, y))`. Should I submit another issue here? Or should it go to tabix issue tracker instead?

**Comment by hagen1778** [comment]
> x, y - >(x, y)

yes, submit the issue plz

> I haven't found docs for unescape

I meant the autocompletion help - when you typing the name of the func/macros `richeditor` should give some additional info about it.

**Comment by hagen1778** [comment]
Hi @Akint 
Lambda issue was solved at https://github.com/Vertamedia/clickhouse-grafana/releases/tag/1.4.1
