### ISSUE TITLE
Alerts break authentication to Clickhouse

### ISSUE THREAD

**Issue by ertong** [Vertamedia/clickhouse-grafana#376]
For some reason, the quering code for graphs and for alerts are different. 
It is not a bug itself, but, as a result, it produces a lot of issues.

Sniffed headers from graphs requests:
```
[accept application/json, text/plain, */*]
[x-real-ip *****]
[accept-encoding gzip, deflate, br]
[host *****:8124]
[x-grafana-org-id 1]
[sec-fetch-dest empty]
[sec-fetch-mode cors]
[x-forwarded-for *****]
[authorization Basic ZGVmYXVsdDo=]
[sec-fetch-site same-origin]
[user-agent Grafana/8.2.1]
```

Sniffed headers from alerts requests:
```
[x-clickhouse-user default]
[content-length 869]
[accept-encoding gzip]
[x-clickhouse-key ]
[user-agent Go-http-client/1.1]
```

Here, we have clickhouse with default user without password.
Graphs work, alerts - not (http 400 from clickhouse ... I think it relates to empty password)

If we disable "Basic auth" in plugin configuration, alerts work, graphs - not. They does not work due to default grafana authentication header with Bearer token, which clickhouse does not understand and returns 403.

If we enable "Basic auth" with default user and empty password, graphs work, alerts - not. Alerts receive http 400 from clickhouse server (maybe due to empty password header).

Current working workaround: disable Basic auth and set custom http header "Authorization: Basic ZGVmYXVsdDo=" (for default empty password). It replaces Bearer token for graphs, and does not trigger x-clickhouse-* headers for alerts.

**Comment by Slach** [comment]
@ertong thanks a lot for reporting, issue related with wrong Basic Auth fix
https://github.com/Vertamedia/clickhouse-grafana/pull/349#issuecomment-856978186
