### ISSUE TITLE
Alerts use wrong timestamps for queries

### ISSUE THREAD

**Issue by ertong** [Vertamedia/clickhouse-grafana#378]
Currenty, it is hard to explain why it is happening, but ...

For graphs, we need to use `ORDER BY t ASC` in queries, otherwise legend shows wrong values (first (or random?) insted on last).

For alerts, we need to use `ORDER BY t DESC` in queries, otherwise, for some reason, alert with `query (A, 1m, now)` queries wrong time range (at least while pressing "Test rule" button)

Current workaround: prepare different queries for graph and for alerts.

**Comment by Slach** [comment]
@ertong Could you provide a bit more context?

Why do you need `ORDER BY t DESC` for alerts?
query(A, 1m, now)
just call A query with $from=now-1m and $to=now

could you share screenshot with your alerts expressions?

**Comment by ertong** [comment]
Hm ... It looks like I cannot reproduce this issue.
Maybe I misinterpreted some previous setup.
The point was that query time range was somewhat unexpectedly like 22 days ago. And at that time ASC<->DESC helped.

Sorry for disturbance. I think, we can close this issue for now. I'll reopen if I find more evidence.
