### ISSUE TITLE
When using $columns with JOIN getting Code: 62, e.displayText() = DB::Exception: Syntax error

### ISSUE THREAD

**Issue by simPod** [Vertamedia/clickhouse-grafana#38]
I have tried the query from https://github.com/Vertamedia/clickhouse-grafana/issues/33#issuecomment-360710880

```sql
$columns(
    concat(toString(myid), '-','x') l,
    count(*) c)
FROM $table
ANY INNER JOIN mysecondtable USING myid
```

However I'm getting error 

> Code: 62, e.displayText() = DB::Exception: Syntax error: failed at position 1: $columns(     concat(toString(myid), '-', 'test') l,     count(*) c) FROM mytable ANY INNER JOIN mysecondtable USING myid FORMAT JSON. Unrecognized token, e.what() = DB::Exception

It seems like the plugin didn't transform it into query for some reason. Using v1.3.1. Thanks for help!

When I do this, it works

```sql
$columns(
    concat(toString(myid), '-','x') l,
    count(*) c)
FROM $table
```

**Comment by hagen1778** [comment]
Hi @simPod 
I've just tested your query in `master` branch and it works well. Generated query is:
```
SELECT t, groupArray((l, c)) as groupArr FROM ( SELECT (intDiv(toUInt32(undefined), 30) * 30) * 1000 as t, concat(toString(myid), '-', 'x') l, count(*) c FROM undefined.undefined ANY INNER JOIN mysecondtable USING myid WHERE undefined >= toDate(1520474540) AND undefined >= toDateTime(1520474540) GROUP BY t, l  ORDER BY t, l) GROUP BY t ORDER BY t
```

If in `generated query` you are seeing query with macroses it means that plugin failed trying to build AST. In that case try to check 'console' in developer tools for error message

**Comment by simPod** [comment]
I'm trying to install latest v so I can see the problem persists. How do you install it? I replaced the files in plugins dir, `yarn build`, restarted Grafana however it still loads old files. Do you have any trick for that? The weird thing is I can see v 1.4.0 in my _installed plugins_ list 🤔 

You were right, I'm getting `AST parser error:  undefined` on `sql_query.ts:43` `console.log('AST parser error: ', err.message)`

**Comment by simPod** [comment]
Probably some browser cache thingy. In private mode it serves new file. Still getting the error at https://github.com/Vertamedia/clickhouse-grafana/blob/master/src/sql_query.ts#L70 Wonder why it is working for you... Will try to put some console.log()s

**Comment by hagen1778** [comment]
Hm, maybe there some other conditions triggering this error. Can you try to create new dashboard, new panel with CH datasource and insert your query there (even without query settings like `table` etc.)?

**Comment by simPod** [comment]
Not helping. But can you verify it works when specifying database?

**Comment by simPod** [comment]
_I mean schema_

**Comment by hagen1778** [comment]
It works for me in both cases. Could you plz make a dashboard with non-sensitive data, reproduce the error, export dashboard as json and send it to hagen1778@gmail.com ?

**Comment by simPod** [comment]
We have grafana behind VPN. Talked with sysadmins but they do not like it very much :/

**Comment by hagen1778** [comment]
I'm closing it for lack of activity
