### ISSUE TITLE
the SQL highlighted is not supported for Grafana 7.x

### ISSUE THREAD

**Issue by frank-lam** [Vertamedia/clickhouse-grafana#381]
like this, lack of syntax highlighting affects the experience. Hope to fix this BUG as soon as possible

![](https://clickhouse.com/learn/lessons/covidtutorial-grafana/images/dashboard6.png)

But I did support syntax highlighting when I used Grafana 5.x

**Comment by Slach** [comment]
old bug which not related with grafana version, duplicate with
https://github.com/Vertamedia/clickhouse-grafana/issues/174

just reload page

**Comment by frank-lam** [comment]
@Slach 
reload the page doesn't work either. will this be fixed in the next version?

**Comment by Slach** [comment]
@frank-lam I can't find root cause, 

https://github.com/Vertamedia/clickhouse-grafana/blob/master/src/query_ctrl.ts#L9
should always try to import mode-clickhouse.js as part of dist/module.js after compilation

if you can help, please feel free to make pull request
