### ISSUE TITLE
Publish version 1.4.0 on Grafana plugins site

### ISSUE THREAD

**Issue by mattbostock** [Vertamedia/clickhouse-grafana#39]
Please publish version 1.4.0 to the Grafana plugin site:
https://grafana.com/plugins/vertamedia-clickhouse-datasource

**Comment by hagen1778** [comment]
will do)

**Comment by hagen1778** [comment]
opened pr https://github.com/grafana/grafana-plugin-repository/pull/244

**Comment by mattbostock** [comment]
Thanks!
