### ISSUE TITLE
value formatting in table view should respect database type

### ISSUE THREAD

**Issue by vbichov** [Vertamedia/clickhouse-grafana#393]
long numeric values that that are saved as strings are displayed as numbers 

reproducer:
1. create table ` CREATE  TABLE num_strings (x  String) ENGINE = Memory;`
2. insert some data `insert into num_strings (*)  values ('12345678901234567.1234567890');`
3. open grafna and create a new table panel displaying the data
query:
```
select * from num_strings
```
4. make sure the default units type is string
<img width="404" alt="Screen Shot 2021-12-15 at 15 06 22" src="https://user-images.githubusercontent.com/4352719/146191858-cc6c80f9-178b-4c84-9a97-8642bd9df2bc.png">
5. notice that the expected result should be the same as a raw selection:
<img width="390" alt="Screen Shot 2021-12-15 at 15 07 41" src="https://user-images.githubusercontent.com/4352719/146192221-92a541eb-d4f0-46d0-8300-2534ed719c26.png">
when it is in fact a js number
<img width="406" alt="Screen Shot 2021-12-15 at 15 08 35" src="https://user-images.githubusercontent.com/4352719/146192249-7c845534-f414-4d5e-8b24-61220215597f.png">

plugin version: 2.4.0
grafana version: 8.3.1

some context: we're using long uniq numerical values as uuid and we keep them as part of the logs - this bug prevents us from displaying real uuid values

after some digging in the code the culprit seems to be [this line](https://github.com/Vertamedia/clickhouse-grafana/blob/035f6ed57eed518cf9594d9e392583a4ec2345cb/src/sql_series.ts#L36
)

I'm not sure why the type returned [here](https://github.com/Vertamedia/clickhouse-grafana/blob/035f6ed57eed518cf9594d9e392583a4ec2345cb/src/sql_series.ts#L29) is not honored

**Comment by Slach** [comment]
@vbichov could you share Query Inspector results?

**Comment by mikhno-s** [comment]
@Slach 
![image](https://user-images.githubusercontent.com/13031076/146199240-d2c1c55b-4621-412c-94bc-a18ce385ac7b.png)

**Comment by mikhno-s** [comment]
Trying this workaround https://github.com/Vertamedia/clickhouse-grafana/pull/395

**Comment by vbichov** [comment]
@Slach  any progress on this ?

any way I or @mikhno-s  can help?

**Comment by Slach** [comment]
feel free to make pull request
no progress now
