### ISSUE TITLE
Publish 2.4.0 / 2.4.1 to grafana.com

### ISSUE THREAD

**Issue by ahayworth** [Vertamedia/clickhouse-grafana#394]
Hello -

Thank you so much for this plugin, I love it!

I am experiencing an issue that should be fixed by the latest release (`2.4.0`). Would it be possible to publish that to grafana.com? Since we use Grafana's managed service, it's not possible for me to install the latest release directly - I believe I can only install it from their plugin directory, and the latest release there is `2.3.1`.

If you have the time to submit the update to their system, I would certainly appreciate it greatly.

Thanks again for all the hard work on this plugin, it's really made a difference for us! ❤️

**Comment by Slach** [comment]
@ahayworth we already submit 2.4.0 release on grafana com on 29 Nov
but Grafana team not review it now. I don't know why this happens.

**Comment by ahayworth** [comment]
Oh, I see - I'm surprised they haven't reviewed it by now. I will open a support ticket, since we are a customer ... maybe that will kick things along.

**Comment by Slach** [comment]
@ahayworth thanks for your help
it will sad if review dealy will relate to new grafana owned plugin https://github.com/grafana/clickhouse-datasource

**Comment by Slach** [comment]
now i submitted 2.4.1

**Comment by ahayworth** [comment]
You're welcome. And yeah, I hope that's not the reason either. It's fine to have their own plugin, of course, but not fantastic if they are shutting out a popular one.

Right now I hope it's just "things got lost in the shuffle of holidays + covid + grafanacon". ❤️

**Comment by josiahg** [comment]
Hi! Jay from Grafana Labs here - our plugin review queue got a bit long during the holiday season, we are working to catch up as fast as we can.

We will be reviewing this particular plugin submission early next week.

Thank you all for being great members of the Grafana community!

**Comment by Slach** [comment]
@josiahg great news, thanks a lot for feedback

only one mention, previous review process via github repo was more transparent

**Comment by josiahg** [comment]
@Slach thanks for the feedback on the new process, I will share with the team and see what we can do to improve the transparency in the new one.

v2.4.2 of this plugin is now published! :)

**Comment by ahayworth** [comment]
Thank you all, this is exciting news to come back to! 😄
