### ISSUE TITLE
rawQuery occasionally do not match query in panel json

### ISSUE THREAD

**Issue by zaizhouh** [Vertamedia/clickhouse-grafana#406]
## version
- Grafana version: Grafana v6.7.4 (8e44bbc5f5)
- ClickHouse version: 2.1.0

## problem overview

I have multiple panels in a dashboard that all use clickhouse as datasource, I set up several alerts.  And alerting A(from panel A) is firing panel b's query metrics  (but the graph in the panel is all correct), then I checked the panel JSON, then find Panel A's query A is having the wrong raw query which is belongs to Panel B query A. 

the following screenshot is a sample dashboard that I reproduce.  

![image](https://user-images.githubusercontent.com/25854997/150306869-7bed028d-d755-417f-87f4-32d3af93da9f.png)

![image](https://user-images.githubusercontent.com/25854997/150306966-9e9f3bd7-157d-43a0-8b3a-8cc2e6258f2c.png)

## summary

I do not have specific steps to 100% reproduce the issue.  what I have done is click around different tabs from different panels. using Alerting tab to jump into panels.  You do not need to actually save the dashboard to reproduce.

![image](https://user-images.githubusercontent.com/25854997/150308803-bd7a086f-c829-4d24-8b39-5ca5fd3d93c5.png)

full dashboard json:

> {
  "annotations": {
    "list": [
      {
        "builtIn": 1,
        "datasource": "-- Grafana --",
        "enable": true,
        "hide": true,
        "iconColor": "rgba(0, 211, 255, 1)",
        "name": "Annotations & Alerts",
        "type": "dashboard"
      }
    ]
  },
  "editable": true,
  "gnetId": null,
  "graphTooltip": 0,
  "id": 65,
  "links": [],
  "panels": [
    {
      "collapsed": false,
      "datasource": null,
      "gridPos": {
        "h": 1,
        "w": 24,
        "x": 0,
        "y": 0
      },
      "id": 6,
      "panels": [],
      "title": "Row title",
      "type": "row"
    },
    {
      "aliasColors": {},
      "bars": false,
      "dashLength": 10,
      "dashes": false,
      "datasource": "ClickHouse testdb",
      "fill": 1,
      "fillGradient": 0,
      "gridPos": {
        "h": 9,
        "w": 12,
        "x": 0,
        "y": 1
      },
      "hiddenSeries": false,
      "id": 4,
      "legend": {
        "avg": false,
        "current": false,
        "max": false,
        "min": false,
        "show": true,
        "total": false,
        "values": false
      },
      "lines": true,
      "linewidth": 1,
      "nullPointMode": "null",
      "options": {
        "dataLinks": []
      },
      "percentage": false,
      "pointradius": 2,
      "points": false,
      "renderer": "flot",
      "seriesOverrides": [],
      "spaceLength": 10,
      "stack": false,
      "steppedLine": false,
      "targets": [
        {
          "database": "bili_bvc",
          "dateColDataType": "",
          "dateLoading": false,
          "dateTimeColDataType": "mtime",
          "dateTimeType": "DATETIME",
          "datetimeLoading": false,
          "extrapolate": true,
          "format": "time_series",
          "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
          "intervalFactor": 1,
          "query": "SELECT\n    toUnixTimestamp(concat(substr(log_date, 1, 4), '-', substr(log_date, 5, 2), '-', substr(log_date, 7, 2), ' 00:00:00'))*1000 as log_date,\n    avg(hits) * 0.5 as avg_hits555\nFROM bili_bvc.hits\nWHERE $timeFilter\ngroup by log_date\n",
          "rawQuery": "SELECT\n    toUnixTimestamp(concat(substr(log_date, 1, 4), '-', substr(log_date, 5, 2), '-', substr(log_date, 7, 2), ' 00:00:00'))*1000 as log_date,\n    avg(hits) as avg_hits666\nFROM bili_bvc.hits\nWHERE mtime >= toDateTime(1641990115)\ngroup by log_date",
          "refId": "A",
          "round": "0s",
          "skip_comments": true,
          "table": "hits",
          "tableLoading": false
        },
        {
          "database": "bili_bvc",
          "dateColDataType": "",
          "dateLoading": false,
          "dateTimeColDataType": "mtime",
          "dateTimeType": "DATETIME",
          "datetimeLoading": false,
          "extrapolate": true,
          "format": "time_series",
          "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
          "intervalFactor": 1,
          "query": "SELECT\n    toUnixTimestamp(concat(substr(log_date, 1, 4), '-', substr(log_date, 5, 2), '-', substr(log_date, 7, 2), ' 00:00:00'))*1000 as log_date,\n    avg(hits) * 0.7 as avg_hits777\nFROM bili_bvc.hits\nWHERE $timeFilter\ngroup by log_date\n",
          "rawQuery": "SELECT\n    toUnixTimestamp(concat(substr(log_date, 1, 4), '-', substr(log_date, 5, 2), '-', substr(log_date, 7, 2), ' 00:00:00'))*1000 as log_date,\n    avg(hits) * 0.7 as avg_hits777\nFROM bili_bvc.hits\nWHERE mtime >= toDateTime(1641989363)\ngroup by log_date",
          "refId": "B",
          "round": "0s",
          "skip_comments": true,
          "table": "hits",
          "tableLoading": false
        },
        {
          "database": "bili_bvc",
          "dateColDataType": "",
          "dateLoading": false,
          "dateTimeColDataType": "mtime",
          "dateTimeType": "DATETIME",
          "datetimeLoading": false,
          "extrapolate": true,
          "format": "time_series",
          "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
          "intervalFactor": 1,
          "query": "SELECT\n    toUnixTimestamp(concat(substr(log_date, 1, 4), '-', substr(log_date, 5, 2), '-', substr(log_date, 7, 2), ' 00:00:00'))*1000 as log_date,\n    avg(hits) * 0.8 as avg_hits888\nFROM bili_bvc.hits\nWHERE $timeFilter\ngroup by log_date\n",
          "rawQuery": "SELECT\n    toUnixTimestamp(concat(substr(log_date, 1, 4), '-', substr(log_date, 5, 2), '-', substr(log_date, 7, 2), ' 00:00:00'))*1000 as log_date,\n    avg(hits) * 0.8 as avg_hits888\nFROM bili_bvc.hits\nWHERE mtime >= toDateTime(1641989363)\ngroup by log_date",
          "refId": "C",
          "round": "0s",
          "skip_comments": true,
          "table": "hits",
          "tableLoading": false
        }
      ],
      "thresholds": [],
      "timeFrom": null,
      "timeRegions": [],
      "timeShift": null,
      "title": "5555",
      "tooltip": {
        "shared": true,
        "sort": 0,
        "value_type": "individual"
      },
      "type": "graph",
      "xaxis": {
        "buckets": null,
        "mode": "time",
        "name": null,
        "show": true,
        "values": []
      },
      "yaxes": [
        {
          "format": "short",
          "label": null,
          "logBase": 1,
          "max": null,
          "min": null,
          "show": true
        },
        {
          "format": "short",
          "label": null,
          "logBase": 1,
          "max": null,
          "min": null,
          "show": true
        }
      ],
      "yaxis": {
        "align": false,
        "alignLevel": null
      }
    },
    {
      "collapsed": false,
      "datasource": null,
      "gridPos": {
        "h": 1,
        "w": 24,
        "x": 0,
        "y": 10
      },
      "id": 8,
      "panels": [],
      "title": "Row title",
      "type": "row"
    },
    {
      "aliasColors": {},
      "bars": false,
      "dashLength": 10,
      "dashes": false,
      "datasource": "ClickHouse testdb",
      "fill": 1,
      "fillGradient": 0,
      "gridPos": {
        "h": 9,
        "w": 12,
        "x": 0,
        "y": 11
      },
      "hiddenSeries": false,
      "id": 2,
      "legend": {
        "avg": false,
        "current": false,
        "max": false,
        "min": false,
        "show": true,
        "total": false,
        "values": false
      },
      "lines": true,
      "linewidth": 1,
      "nullPointMode": "null",
      "options": {
        "dataLinks": []
      },
      "percentage": false,
      "pointradius": 2,
      "points": false,
      "renderer": "flot",
      "seriesOverrides": [],
      "spaceLength": 10,
      "stack": false,
      "steppedLine": false,
      "targets": [
        {
          "database": "bili_bvc",
          "dateColDataType": "",
          "dateLoading": false,
          "dateTimeColDataType": "mtime",
          "dateTimeType": "DATETIME",
          "datetimeLoading": false,
          "extrapolate": true,
          "format": "time_series",
          "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
          "intervalFactor": 1,
          "query": "SELECT\n    toUnixTimestamp(concat(substr(log_date, 1, 4), '-', substr(log_date, 5, 2), '-', substr(log_date, 7, 2), ' 00:00:00'))*1000 as log_date,\n    avg(hits) as avg_hits666\nFROM bili_bvc.hits\nWHERE $timeFilter\ngroup by log_date\n",
          "rawQuery": "SELECT\n    toUnixTimestamp(concat(substr(log_date, 1, 4), '-', substr(log_date, 5, 2), '-', substr(log_date, 7, 2), ' 00:00:00'))*1000 as log_date,\n    avg(hits) as avg_hits666\nFROM bili_bvc.hits\nWHERE mtime >= toDateTime(1641989225)\ngroup by log_date",
          "refId": "A",
          "round": "0s",
          "skip_comments": true,
          "table": "hits",
          "tableLoading": false
        }
      ],
      "thresholds": [],
      "timeFrom": null,
      "timeRegions": [],
      "timeShift": null,
      "title": "ck 1",
      "tooltip": {
        "shared": true,
        "sort": 0,
        "value_type": "individual"
      },
      "type": "graph",
      "xaxis": {
        "buckets": null,
        "mode": "time",
        "name": null,
        "show": true,
        "values": []
      },
      "yaxes": [
        {
          "format": "short",
          "label": null,
          "logBase": 1,
          "max": null,
          "min": null,
          "show": true
        },
        {
          "format": "short",
          "label": null,
          "logBase": 1,
          "max": null,
          "min": null,
          "show": true
        }
      ],
      "yaxis": {
        "align": false,
        "alignLevel": null
      }
    }
  ],
  "schemaVersion": 22,
  "style": "dark",
  "tags": [],
  "templating": {
    "list": []
  },
  "time": {
    "from": "now-7d",
    "to": "now"
  },
  "timepicker": {
    "refresh_intervals": [
      "5s",
      "10s",
      "30s",
      "1m",
      "5m",
      "15m",
      "30m",
      "1h",
      "2h",
      "1d"
    ]
  },
  "timezone": "",
  "title": "clickhouse rawQuery Debug",
  "uid": "HYN4QXJ7k",
  "variables": {
    "list": []
  },
  "version": 15
}

**Comment by Slach** [comment]
After change query in query editor
try to click "Generated SQL" and ensure query is the same
After it, press "Save Dashboard".

Moreover, I would like to recommend try to update to the latest 2.4.1 plugin version.

**Comment by zaizhouh** [comment]
> 
Thanks for the quick reply.

I don't think the problem occurs when I save panel A and it generates the wrong raw query for me. I think it is more likely that when I work on panel B and make some changes. It changes panel A's rawQuery for me. So it is impossible for me to click every panel in the dashboard and click generate SQL to ensure every rawquery is matched. 

But since 2.1.0 is quite an outdated version, I will try the version 2.4.1 plugin as recommended and see if this problem still exist or not

**Comment by zaizhouh** [comment]
Finally, I found a way to 100% reproduces this issue. 
1. have two rows in the dashboard, and each row should contain one or more panels (for simplicity let's say row A has panel A and row B has panel B).
2. expand row B and make some modifications on the query, then go back to dashboard.
3. then by expanding row A,  boom, panel B's rawQuery becomes inconsistent with his original query and becomes Panel A's raw query.


I also make a gif to record the process I reproduce issues. Feel free to check if my description is unclear to you. 

![rawQueryDebug](https://user-images.githubusercontent.com/25854997/150636359-97069f63-c0b1-4a95-922b-27074d451cd2.gif)

Looks like it only happening in the row expanding action (panel rendering process).  Because when two rows are expanding at the very beginning, this issue can not be reproduced.

**Even though it has no hurt to the panel graph, the wrong rawQuery will result in wrong alert result.**

**Comment by Slach** [comment]
Could you try to reproduce this behavior on grafana 7.x and 8.x?

**Comment by Slach** [comment]
Thanks a lot for reproducing anyway!

**Comment by zaizhouh** [comment]
> Could you try to reproduce this behavior on grafana 7.x and 8.x?

emmmm, interesting. 
did a few test, but can not reproduce on grafana current main branch ->8.4  (9fc0aee02b0dcc20996432801ab16a8c8ad3436f) and v7.5.6 branch (5fdad5bfe4fc97978a26b741ad8f067db900b673)

**Comment by Slach** [comment]
@zaizhouh wow, thanks a lot for solution!
