### ISSUE TITLE
don't support latest clickhouse which doesn't require date column

### ISSUE THREAD

**Issue by baoxiao** [Vertamedia/clickhouse-grafana#48]
The latest clickhouse support customized partition, so date column is not a must, but the plugin data ranger filter is still based on date column if we don't have data column and use datatime column for both Colum:date and Column:datetime variable, so for range fiter:
 where (event_time >= toDate(1518030541)) AND (event_time <= toDate(1522869530)) always return 0 records, should change to 
where (event_time >= toDateTime(1518030541)) AND (event_time <= toDateTime(1522869530))

event_time is datetime column.

Thanks

**Comment by hagen1778** [comment]
Hi @baoxiao 

I've checked CH documentation and Date type column is still mandatory for [MergeTree](https://clickhouse.yandex/docs/en/table_engines/mergetree/) engine.

**Comment by baoxiao** [comment]
they may not update their document, we already use mergetree table without
date column using custom partition

https://clickhouse.yandex/docs/en/table_engines/custom_partitioning_key/

**Comment by simPod** [comment]
@baoxiao do you need a date column to use this datasource then? I'm wondering whether I can switch to tables without date column already. Or do you have it there until this datasource supports it?

**Comment by ryn9** [comment]
I have also been bit by this, but have worked around it by tinkering a lot with my queries.
Code patching or documentation update should be in order, as this is not obvious

Here is an example table definition:
CREATE TABLE default.test
(
     time DateTime,
     dest_ip String
)
ENGINE = MergeTree
PARTITION BY toYYYYMMDD(time)
ORDER BY time

When configuring your query:
setup the Column:Date as whatever you want.
setup the Column:DateTime as 'time'


Here is what you can use as examples for your queries...


COUNT ALL OVER TIME EXAMPLE:
SELECT
    $timeSeries as t,
    count()
FROM $table
WHERE
    $dateTimeCol BETWEEN toDateTime($from) AND toDateTime($to)
GROUP BY t
ORDER BY t


COUNT BY dest_ip OVER TIME EXAMPLE:
SELECT 
     t, 
     groupArray((dest_ip, c)) as groupArr
FROM
(
     SELECT
          $timeSeries as t,
          dest_ip,
          count(*) c
     FROM $table
     WHERE $dateTimeCol BETWEEN toDateTime($from) AND toDateTime($to)
     GROUP BY t, dest_ip
     ORDER BY t, dest_ip
)
GROUP BY t
ORDER BY t

**Comment by hagen1778** [comment]
Please, see https://github.com/Vertamedia/clickhouse-grafana/releases/tag/1.8.0
