### ISSUE TITLE
Minimum step

### ISSUE THREAD

**Issue by leoluk** [Vertamedia/clickhouse-grafana#50]
There should be an additional "Minimum step" field that sets a lower bound for the auto interval/step.

Depending on timestamp precision, it can be necessary to specify a minimum step - there's no point in doing per-second aggregates when the precision of the underlying data is a multiple of that.

**Comment by hagen1778** [comment]
Hi @leoluk 
It sounds reasonable for performance. But situations when user browsing so short periods so that interval becomes too low (seconds) are pretty rare. And even if these situations are happening - it would be easy for CH to process so short periods. Or I missed something?

**Comment by ctaity** [comment]
HI some news about this?

**Comment by hagen1778** [comment]
Closed due to lack of activity

**Comment by alexz0000** [comment]
Let's say my interval is 15s,  it cannot specify a minimum step, there will be lots of null values. Could you support the feature?

**Comment by alexz0000** [comment]
I think we need an options same as this https://github.com/grafana/grafana/pull/8073

**Comment by alexz0000** [comment]
@hagen1778, any updates on this?
