### ISSUE TITLE
When joining with quoted identifier, it skips it in generated query

### ISSUE THREAD

**Issue by simPod** [Vertamedia/clickhouse-grafana#55]
When doing joins like this

```sql
ANY LEFT JOIN table USING `column`
```

The generated part of query is 

```sql
ANY LEFT JOIN table USING FORMAT JSON
```

Instead it should be

```sql
ANY LEFT JOIN table USING `column` FORMAT JSON
```

I believe it has something to do with https://github.com/Vertamedia/clickhouse-grafana/blob/f56fb8d0d257d067dc22925ab0e573547224b64b/src/scanner.ts#L252

It doesn't skip double quoted identifiers. 

```sql
ANY LEFT JOIN table USING "column"
->
ANY LEFT JOIN table USING "column" FORMAT JSON
```

But when `stringRe` value is modified to ``"('[^']*')|(`[^`]*`)|(\"[^\"]*\")"``, it skips them too. However reversed quotation marks should be used anyway http://clickhouse-docs.readthedocs.io/en/latest/query_language/syntax.html#identifiers

**Comment by hagen1778** [comment]
Hi @simPod 
I've tried following example:
```
$columns(AidName, count(*) c) FROM $table ANY LEFT JOIN aid_type USING `Aid`
```
And it converts into: 
```
SELECT t, groupArray((AidName, c)) as groupArr FROM ( SELECT (intDiv(toUInt32(EventTime), 2) * 2) * 1000 as t, AidName, count(*) c FROM default.events ANY LEFT JOIN aid_type USING `Aid` WHERE EventDate BETWEEN toDate(1519404644) AND toDate(1519405766) AND EventTime BETWEEN toDateTime(1519404644) AND toDateTime(1519405766) GROUP BY t, AidName  ORDER BY t, AidName) GROUP BY t ORDER BY t
```

Can u provide me with full query and version of plugin?

**Comment by simPod** [comment]
I had 1.4.1, it seems to be working with the latest. Sorry for false report ;)
