### ISSUE TITLE
Worldmap Panel Issue

### ISSUE THREAD

**Issue by ennio1991** [Vertamedia/clickhouse-grafana#57]
Hi, I have a click house table with the following schema:
`UserID	UInt32		
lat	Float64		
lon	Float64		
city	String		
country	String		
countryCode	String		
day	Date		
DateTimeValue	DateTime`

Data Sample:
![screen shot 2018-04-30 at 12 13 26](https://user-images.githubusercontent.com/14088522/39423989-e307d6f2-4c74-11e8-93be-f2b0295c7628.png)

I will like to set WorldMap based on countryCode field.

So I did this:

![screen shot 2018-04-30 at 12 09 10](https://user-images.githubusercontent.com/14088522/39424033-0c8f1ac6-4c75-11e8-8e97-12bed80c576a.png)

I am getting the following answer in the Query Inspector:
![screen shot 2018-04-30 at 12 54 11](https://user-images.githubusercontent.com/14088522/39424175-a1493c32-4c75-11e8-806e-0938fa1020ff.png)

`
{
  "xhrStatus": "complete",
  "request": {
    "method": "GET",
    "url": "api/datasources/proxy/1/?query=select%20countryCode%2C%20%20count(*)%20%20from%20rizk.userlogin%20%20where%20day%20%3E%3D%20toDate(1525085178)%20AND%20DateTimeValue%20%3E%3D%20toDateTime(1525085178)%20group%20by%20countryCode%20%20%20FORMAT%20JSON"
  },
  "response": {
    "meta": [
      {
        "name": "countryCode",
        "type": "String"
      },
      {
        "name": "count()",
        "type": "UInt64"
      }
    ],
    "data": [
      {
        "countryCode": "GB",
        "count()": "5"
      },
      {
        "countryCode": "NO",
        "count()": "13"
      },
      {
        "countryCode": "NL",
        "count()": "8"
      },
      {
        "countryCode": "AT",
        "count()": "1"
      },
      {
        "countryCode": "DE",
        "count()": "17"
      },
      {
        "countryCode": "FI",
        "count()": "27"
      },
      {
        "countryCode": "SE",
        "count()": "15"
      },
      {
        "countryCode": "NZ",
        "count()": "2"
      }
    ],
    "rows": 8,
    "statistics": {
      "elapsed": 0.001184305,
      "rows_read": 11146,
      "bytes_read": 137586
    }
  }
}
`

But as you can see the point are not displayed on the map.

**Comment by ennio1991** [comment]
Solved, 
I had to use the groupArray function.
Maybe this should be documented.

Query:
`SELECT 1, 
groupArray((c, Reqs)) AS groupArr
FROM (
SELECT countryCode as c,
count(*) as Reqs
from $table
where $timeFilter
Group  by c
order by Reqs desc
)`

**Comment by hagen1778** [comment]
Hi @ennio1991 
Yes, should be documented in README

**Comment by hagen1778** [comment]
https://github.com/Vertamedia/clickhouse-grafana#worldmap-panel-httpsgithubcomgrafanaworldmap-panel
