### ISSUE TITLE
Doesn't support macros in Query Variables

### ISSUE THREAD

**Issue by simPod** [Vertamedia/clickhouse-grafana#58]
Is there a way to use macros like `$from` or `$to` in Query Variables? The plugin doesn't seem to replace it in the query.

**Comment by hagen1778** [comment]
Hi @simPod 
Plz check https://github.com/Vertamedia/clickhouse-grafana/issues/10

**Comment by simPod** [comment]
Looks like you're right, just tried with postgres data source. Thanks for reply!
