### ISSUE TITLE
Does the plugin support "Series overrides"?

### ISSUE THREAD

**Issue by fr05t1k** [Vertamedia/clickhouse-grafana#59]
Is it possible to make graph for current period and from previous month for example? 
I tried to use Series Overrides but it seems like it doesn't work.

**Comment by hagen1778** [comment]
Hi @fr05t1k 
[Series Overrides](http://docs.grafana.org/features/panels/graph/#series-overrides) in Grafana allows to change only visual aspects, but not time range. I guess, there is misleading regex value for `alias or regex` in example.

If you are looking for time shifting - plz take a look on [time range](http://docs.grafana.org/features/panels/graph/#time-range) tab

**Comment by fr05t1k** [comment]
As I understand Time range allow to shift all metrics. I'm trying to do smth like [this](https://community.grafana.com/t/advanced-graphing-part2-visualize-timeshift/365)

**Comment by fr05t1k** [comment]
I got it. Seems like ge has 2 metrics which are shifted manually

**Comment by fr05t1k** [comment]
But when I do smth like this
```
SELECT
    $timeSeries as t,
    count() as users
FROM $table
WHERE 
  registeredDate BETWEEN toDate($from - 3600 * 24 * 30) and toDate($to - 3600 * 24 * 30) and 
  registeredAt BETWEEN toDateTime($from - 3600 * 24 * 30) and toDateTime($to - 3600 * 24 * 30) 
GROUP BY t
ORDER BY t
```

The data becomes outside of time range.

**Comment by fr05t1k** [comment]
Yes. That's what I need. Thanks ;)
