### ISSUE TITLE
Variables in templating query

### ISSUE THREAD

**Issue by adzhurinskij** [Vertamedia/clickhouse-grafana#62]
Hi,

How can i use $timeFilter in templating query?

Now, vars not build in query.

![clickhouse_timefilter](https://user-images.githubusercontent.com/12733926/40981136-e3bb472a-68e2-11e8-9730-b0e98f4bedbb.png)

**Comment by hagen1778** [comment]
Hi @adzhurinskij 
Plz check #10

**Comment by adzhurinskij** [comment]
Thanks. You are right.
