### ISSUE TITLE
Question:Expose timefilter in query variable ?

### ISSUE THREAD

**Issue by TH-HA** [Vertamedia/clickhouse-grafana#71]
Query variable to build dynamic filter and is a key feature of grafana. 
I'm looking to use this feature on the top of clickhouse to let him select an application and display some metrics. As there is thousand of applications , i want to display only a Top X application on those filter.
But to do that i need to access to the timefilter and update the variable when the time range is changed. 
I know it 's possible to do it for other datasources ( postgre , mysql ,influx ,example : https://github.com/grafana/grafana/pull/10069  ) , but i m not able to do it on clickhouse. 
The question is : 
   Is it doable with the current version of clickhouse datasource ?
   If not , is it an evolution of the grafana core engine ?
   If it rely on the data source to expose this timefilter , is it possible to  expose it ?

Thanks in advance.

**Comment by TH-HA** [comment]
Just to be exhaustive in my description , the query variable without allowing to access to the time range has 2  very negative effects : 
     - The list of possible value is not accurate and this can lead to empty dashboard ( as the query is done on all the data ) 
    - this can kill the system as querying the whole database can take dozen of seconds which make dashboard display very very slow.

**Comment by TH-HA** [comment]
just realize that you have commited the annotation query which may add such kind of feature.
If you want someone to test it. I'll be happy to do it.
Regards

**Comment by hagen1778** [comment]
Hi @TH-HA 

Yes, it would be nice to have such option as `$__timeFilter` in variable queries. And we have corresponding pr (#66) from community to add that option. I hope it will be added this or next week. Thank you!

**Comment by hagen1778** [comment]
Hi @TH-HA 

Take a look https://github.com/Vertamedia/clickhouse-grafana/releases/tag/1.6.0

**Comment by TH-HA** [comment]
Thanks a lot it works perfectly and open new usage of grafana with Clickhouse.
Thanks again.
