### ISSUE TITLE
Adhoc in subqueries

### ISSUE THREAD

**Issue by bobrik** [Vertamedia/clickhouse-grafana#74]
I have a dashboard with adhoc filter set to some customer. I want to plot rps for top X things on that customer. This doesn't work, because adhoc filters are only applied to outer queries, which is fair.

Let's have a variable that I can manually plug into the subquery.

cc @vavrusa

**Comment by hagen1778** [comment]
Hi @bobrik @vavrusa 

Thank you for contribution. The issue will be closed on release

**Comment by hagen1778** [comment]
Pls see https://github.com/Vertamedia/clickhouse-grafana/releases/tag/1.7.0
