### ISSUE TITLE
Allow setting database and table for adhoc filters

### ISSUE THREAD

**Issue by bobrik** [Vertamedia/clickhouse-grafana#75]
Currently the query is:

```sql
SELECT database, table, name, type FROM system.columns WHERE database != 'system' ORDER BY database, table FORMAT JSON
```

In our production instance this is unmanageable:

```
 :) SELECT count() FROM system.columns WHERE database != 'system'

SELECT count()
  FROM system.columns
 WHERE database != 'system'


┌─count()─┐
│   14016 │
└─────────┘

Ok. 1 row in set. Elapsed: 0.259 sec. Processed: 0.0  rows, 0.0B (0.0  rows/s, 0.0B/s)
```

Grafana gets 1.8MB of JSON just to show the list of fields available and the list with 14016 items is going to be usable for ad-hoc discovery.

Most of the time people are not interested in all databases and tables, but rather focus on one in a single dashboard. I propose to add some filtering capabilities, so I can add another filter (possibly using variables) to narrow down the list of fields.

**Comment by vavrusa** [comment]
If you set default database in the datasource, it will use that. AFAIK it's not possible to parametrize ad-hoc filters, Grafana would need to provide provide an interface for that first: https://github.com/grafana/grafana/blob/e1beaaa0f72dd3238dfda17bf31b82fb71a2ccc2/public/app/features/templating/editor_ctrl.ts#L91

**Comment by hagen1778** [comment]
Hi @bobrik @vavrusa 

Yep, adhoc filters can't be parametrized in current implementation. But we can try to create a constant variable with strictly defined name like `AdHocQuery` with value e.g. `SELECT database, table, name, type FROM system.columns WHERE table='myTable' ORDER BY database, table`. Then make it hidden to avoid displaying in the top of dashboard. Since adhoc queries are running when dashboard is already loaded our hidden variable will be visible in `getTagKeys()` func, so we will be able to substitute default adhoc query with our custom.

What do you think about this workaround?

**Comment by bobrik** [comment]
I'm fine with having something like `adhoc_query_filter`, let's make it happen.

In the meantime I filed an issue for Grafana itself: https://github.com/grafana/grafana/issues/13109.

**Comment by hagen1778** [comment]
Hi @bobrik 

Pls see https://github.com/Vertamedia/clickhouse-grafana/releases/tag/1.7.0
Check the Readme updates at https://github.com/Vertamedia/clickhouse-grafana#ad-hoc-filters

**Comment by bobrik** [comment]
@hagen1778, in developer tools I'm seeing this query:

```
SELECT database, table, name, type FROM system.columns WHERE database = 'open' AND table='requests_sample_anonymized' ORDER BY database, table FORMAT JSON
```

But in the dropdown I see fields duplicated with and without table name:

![image](https://user-images.githubusercontent.com/89186/46317711-c10ed900-c588-11e8-9ab4-1b420adb00b9.png)

I think only `zoneId` should be shown in this case.

**Comment by hagen1778** [comment]
Hi @bobrik 

it's intentional behavior. Pls see https://github.com/Vertamedia/clickhouse-grafana#ad-hoc-filters:
> If the ad-hoc filter doesn't specify table, it will apply to all queries regardless of the table. This is useful if the dashboard contains queries to multiple different tables.

Added in [commit](https://github.com/Vertamedia/clickhouse-grafana/commit/9c0774ec2ca4228f353a3fb64a714392cd17136e)

**Comment by bobrik** [comment]
Ah, I see. That sounds counter-intuitive from the start, but I like it. This covers some of my needs.

**Comment by vavrusa** [comment]
It would probably be more convenient to hide it if there was just one table after using `adhoc_query_filter` (or make it configurable).
