### ISSUE TITLE
Computing rate is sensitive to $step in grafana, rendering wrong results sometimes

### ISSUE THREAD

**Issue by JiriHorky** [Vertamedia/clickhouse-grafana#79]
I noticed that at certain zoom levels, the plots are rendered wrongly, exhibiting some saw-like behavior:

![image](https://user-images.githubusercontent.com/427968/45930336-20546400-bf5f-11e8-9ffc-ff1e02fa33f3.png)

whereas the real plot looks like:
![image](https://user-images.githubusercontent.com/427968/45930345-3e21c900-bf5f-11e8-9548-e8c2b2f3d653.png)

The trouble is that we collect metrics every 5 minutes and if the step is set to 2minutes by Grafana, the resulting time is rounded to 120s intervals:
`(intDiv(toUInt32(time), 120) * 120) * 1000 as t`

which produces difference between metrics to be either 240 or 360s.

> t                             diff
> 1537471680000   240000
> 1537471920000   360000
> 1537472280000   240000
> 1537472520000   360000
> 1537472880000   240000
> 1537473120000   360000
> 1537473480000   240000
> 1537473720000   360000
> 1537474080000   240000
> 
> 

Since the values are then divided by runningDifference() function, ie. by 240 or 360s, it creates the saw-like figure in the plot, which is obviosly wrong.

I am not sure what is the best solution for this, probably being able to specify the collection rate to the plugin somehow?

**Comment by hagen1778** [comment]
Hi @JiriHorky 

There is an option to set `step` manually in the graph params:
![screenshot](https://user-images.githubusercontent.com/2902918/46244841-c552bf00-c3ed-11e8-974c-710d0f7fdd6f.png)

**Comment by JiriHorky** [comment]
You are right. Setting it manually helped. Thanks.
