### ISSUE TITLE
[question]: есть ли возможность получить из одной "Metrics" несколько линий графика (series)?

### ISSUE THREAD

**Issue by lab79** [Vertamedia/clickhouse-grafana#8]
Пробовал задать Templating/Variables, но это получилось использовать только как sql-фильтр вроде
`...
and('All' in ($geo_country) or geo_country in ($geo_country))
...
`

PS: в плагине grafana-zabbix, например, возможность множить линии графика была.

**Comment by hagen1778** [comment]
Я не совсем понимаю Ваш вопрос. Не могли бы Вы привести пример задачи, которую нужно решить?

**Comment by lab79** [comment]
Нужно построить график, например, число запросов по каждой стране отдельной линией графика.
Т.е. прописать единственный запрос к базе и указать колонку-страну по которой будут разделяться линии графика (а не прописывать отдельную метрику под каждую страну)

Примерно [так](http://play.grafana.org/dashboard/db/grafana-play-home?panelId=2&fullscreen&edit&orgId=1)

**Comment by hagen1778** [comment]
Вы можете воспользоваться макросом $columns:
`$columns(OSName, count(*) c) FROM requests`

Описание макроса доступно в README.

**Comment by hagen1778** [comment]
Если вопрос решен - я закрываю issue
