### ISSUE TITLE
Templating variables miss dependencies

### ISSUE THREAD

**Issue by bobrik** [Vertamedia/clickhouse-grafana#82]
Continuing https://github.com/grafana/grafana/issues/13291

It seems like the variable is not populated when query is sent to Clickhouse, resulting in an error:

My templating variable:

![image](https://user-images.githubusercontent.com/89186/46266753-50af7b80-c4e6-11e8-89ce-f53bc79f73a4.png)

Turns into this query:

```
SELECT arrayJoin(range()) AS cpus FORMAT JSON
```

Dashboard JSON if you want to reproduce: 

* https://gist.github.com/bobrik/4d011d4c28f4729207fc2b933a02ede5

**Comment by hagen1778** [comment]
Hi @bobrik 

My config is following:
- plugin Version 1.7.0
- Grafana v5.2.5 (commit: 6f9b734)
- dashboard (I've changed queries to match my metrics) - https://gist.github.com/hagen1778/f448f5202d76c82ab9953b2382417a5a

In my case I see the same behavior for both: clickhouse and prometheus variables. Both requests were sent without variable value, got errors and automatically repeated successfully:
<img width="800" alt="screen shot 2018-10-03 at 17 40 35" src="https://user-images.githubusercontent.com/2902918/46418073-a62c9800-c733-11e8-832f-3e2e42e7575c.png">

I reproduced the same behavior at Grafana playground:
<img width="822" alt="screen shot 2018-10-03 at 17 35 47" src="https://user-images.githubusercontent.com/2902918/46418109-bcd2ef00-c733-11e8-990a-6eee32e30bca.png">

The gist for Grafana playground - https://gist.github.com/hagen1778/0bd00b0555cf8f4090a9b6195148f6b8

Unfortunately, it's "floating" bug and can't be reproduced with 100% probability.

Thank you!

**Comment by bobrik** [comment]
Can you update the Grafana issue and ask them to reopen if this can be reproduced in playground?

**Comment by hagen1778** [comment]
Yes, I will

**Comment by bobrik** [comment]
Looks like this was fixed with https://github.com/grafana/grafana/issues/11890.
