### ISSUE TITLE
Built in Smoothing Maros

### ISSUE THREAD

**Issue by volfco** [Vertamedia/clickhouse-grafana#83]
I've been trying to figure out how to write a moving average or moving median function to help smooth out some erratic data as seen in the provided screenshot.

![image](https://user-images.githubusercontent.com/433045/46328893-94ca7b00-c5cf-11e8-9611-5d187c044d71.png)

If this can be done, I think this would be an extremely useful macros to add.

**Comment by hagen1778** [comment]
Hi @volfco 

Do you have some idea how to implement such function? Could the following do what you need?
```
     SELECT
            (intDiv(toUInt32(Time), 120) * 120) * 1000 AS t,
            avg(Column)
     FROM $table
     WHERE Column > 0
     GROUP BY t
     ORDER BY t ASC
```
> where `(intDiv(toUInt32(Time), 120) * 120) * 1000 AS t` groups data by 2min intervals
and `avg(Column)` calculates average

Please, pay attention to condition `WHERE Column > 0` to avoid null values.

**Comment by Slach** [comment]
close issue during miss any activity
@volfco feel free to reopen the issue
Also, you could implement something for moving average use ideas from https://stackoverflow.com/questions/53416531/clickhouse-moving-average
