### ISSUE TITLE
Step alignment breaks rightmost bucket

### ISSUE THREAD

**Issue by bobrik** [Vertamedia/clickhouse-grafana#84]
This is related to #76.

Here's how it looks when I look at last 24h:

![image](https://user-images.githubusercontent.com/89186/46824800-d7662300-cd46-11e8-8824-12f29cc6823c.png)

But this is how it looks when I ask for a specific 24h:

![image](https://user-images.githubusercontent.com/89186/46824907-1ac09180-cd47-11e8-9af8-adfd2c5f5fe9.png)

Query editor is configured as follows:

![image](https://user-images.githubusercontent.com/89186/46825142-c23dc400-cd47-11e8-9fe8-bfe2227d9f64.png)

Query that ends up being sent:

```sql
SELECT   
   (intDiv(toUInt32(datetime), 900) * 900) * 1000 as time_msec,   
   count() / 0.01 / 900 as requests
FROM mytable
WHERE
   date BETWEEN toDate(1539194400) AND toDate(1539280800)
   AND
   datetime BETWEEN toDateTime(1539194400) AND toDateTime(1539280800)   
   AND
   time_msec
ORDER BY   
   time_msec
FORMAT JSON
```

The problem here is that `1539280800` is `Thu Oct 11 18:00:00 UTC 2018`, and it encompasses the right most bucket of requests. Every other bucket is 15m (900s), but this bucket is just 1s.

I think we need to cut off this last incomplete bucket somehow.

cc @vavrusa

**Comment by bobrik** [comment]
It should be `<11:05`, because `11:05:00` is already the next bucket.

I'm happy to test a PR locally if you have it.

**Comment by hagen1778** [comment]
Please, try with attached pr

**Comment by hagen1778** [comment]
Please, see https://github.com/Vertamedia/clickhouse-grafana/releases/tag/1.8.0
