### ISSUE TITLE
Comments not supported by sql language parser

### ISSUE THREAD

**Issue by simPod** [Vertamedia/clickhouse-grafana#95]
When `--` comment is used within query, it doesn't behave like comment
```sql
SELECT 
1
FROM
-- test
test2
```

The query produced is invalid and clickhouse server usually throws `DB::Exception: Syntax error`

**Comment by hagen1778** [comment]
Yep, we should implement comments support

**Comment by tlightsky** [comment]
we meet this problem too

**Comment by tlightsky** [comment]
can we just remove the comment before make the final sql

**Comment by alex-zaitsev** [comment]
Can you use /* comments */ instead? It should work.

**Comment by simPod** [comment]
Not instead unfortunately. `--` [are documented](https://clickhouse.yandex/docs/en/query_language/syntax/#comments) and default to most of the tooling from where I copy queries from.

**Comment by alex-zaitsev** [comment]
I know '--' comments are documented, but they are hard to use in APIs. In particular, '--' comments do not work well even in clickhouse-client. If you have multi-line statement with such comments, you can not use history (up arrow) to repeat the query.

**Comment by simPod** [comment]
But that's bug of clickhouse-client, not something related to those comments in general. Till they're part of clickhouse standard, they will be around.

**Comment by tlightsky** [comment]
we make a tool to make grafana variable could work in datagrip using comment,
really hope i can copy/paster from/to each other

**Comment by alex-zaitsev** [comment]
Sure. I like the idea of stripping comments before sending them to the server. Looks like the easiest way to fix it. Alternatively, we can replace '--' with '/* */'.

**Comment by Slach** [comment]
issue resolved via https://github.com/Altinity/clickhouse-grafana/commit/00d2e0bfb44a5fad623062cdde487e74fc211b1c
