### ISSUE TITLE
table panel treats string columns as numbers

### ISSUE THREAD

**Issue by vbichov** [Vertamedia/clickhouse-grafana#97]
there seems to be an issue with the way table element types are inferred:

the following function: https://github.com/Vertamedia/clickhouse-grafana/blob/master/src/sql_series.ts#L177

causes this bug:
https://github.com/grafana/grafana/issues/14660

**Comment by hagen1778** [comment]
https://github.com/Vertamedia/clickhouse-grafana/releases/tag/1.8.1
