### ISSUE TITLE
$table should be protected against table having spaces in their name

### ISSUE THREAD

**Issue by sbouchex** [Vertamedia/clickhouse-grafana#98]
My table is having spaces in the name, when using $table, Grafana reports a syntax error because back quote are missing in the table name.

Example My table should be replaced with `My table`

**Comment by hagen1778** [comment]
Hi @sbouchex 
I wasn't aware of this. Thank you for report!

**Comment by hagen1778** [comment]
fixed in https://github.com/Vertamedia/clickhouse-grafana/pull/120
