### ISSUE TITLE
Supporting Clickhouse merge() table function

### ISSUE THREAD

**Issue by vane4karock** [Vertamedia/clickhouse-grafana#99]
Hi guys,

I found that "clickhouse-grafana" doesn't supporting Clickhouse merge() table function when "GROUP BY" in sql-request. On graphs I have data without aggregation. But in "Query Inspector" I can see that plugin get data with aggregation.

Is that possible to create supporting Clickhouse table functions in "clickhouse-grafana"?

**Comment by hagen1778** [comment]
Hi @vane4karock!
Can you provide a query example, the actual response and expected response from CH?

**Comment by vane4karock** [comment]
Hi @hagen1778,

For example:

For query like this:
![default](https://user-images.githubusercontent.com/30746426/53321850-a5ff8580-38ea-11e9-887f-8858a115731d.png)
where

**Comment by vane4karock** [comment]
Hi @hagen1778,

For example:

For query like
![default](https://user-images.githubusercontent.com/30746426/53321894-cdeee900-38ea-11e9-8a30-d589568e9f5c.png)
where
![default](https://user-images.githubusercontent.com/30746426/53321924-e4954000-38ea-11e9-9652-440f25024580.png)
I have graph like
![default](https://user-images.githubusercontent.com/30746426/53321975-0a224980-38eb-11e9-9d33-fff27fda8215.png)
and in "Query Inspector" I have data like
![default](https://user-images.githubusercontent.com/30746426/53322077-5a99a700-38eb-11e9-855f-2a90d248ec58.png)

Here "merged_telemetry_tables.gameServer_Worker_commandCalls" created by Engine = Merge() and you can see that there is no problem to create graphs in Grafana

But

For query like
![default](https://user-images.githubusercontent.com/30746426/53322175-a9474100-38eb-11e9-8227-844af49a8ffc.png)
where I'm using table function merge() and don't use "Toggle Editor"
I have graph like
![default](https://user-images.githubusercontent.com/30746426/53322421-6f2a6f00-38ec-11e9-9179-1c14997c314c.png)
and in "Query Inspector" I have data like
![default](https://user-images.githubusercontent.com/30746426/53322455-849f9900-38ec-11e9-8096-9fbfa1f07d82.png)

Here you can see that I have the same data in "Query Inspector", but another graph.

**Comment by Slach** [comment]
@vane4karock look like latest `master` branch works fine with merge() table function
![image](https://user-images.githubusercontent.com/105560/86431740-01c3f500-bd0f-11ea-890c-0d191d7ee7ce.png)
i will add example with merge() function to clickhouse_dashboard.json

you can reproduce behavior with following steps
```
git clone https://github.com/Vertamedia/clickhouse-grafana
cd clickhouse-grafana
docker-compose up -d grafana
```
open http://localhost:3000/dashboards -> clickhouse dashboard
